### ISSUE TITLE
namespace "google" has no member "InitGoogleLogging"

### ISSUE THREAD

**Issue by mesakas** [google/glog#1061]
I use glog-0.6.0 in my program, but my vscode tell me: 
> namespace "google" has no member "InitGoogleLogging"

this is my code:
```c++
#include <glog/logging.h>

int main(int argc, char* argv[]) {
    google::InitGoogleLogging(argv[0]);
    return 0;
}

```

I don't know why have this error, and also I can't build my project of Cmake.
no need use this function in my program in 0.6.0?

**Comment by sergiud** [comment]
This is an issue with your setup. Make sure to read and follow the [documentation](https://github.com/google/glog?tab=readme-ov-file#usage-in-projects).

If this still does not help, I suggest you ask the question on Stackoverflow or the like.
