### ISSUE TITLE
FetchContent support

### ISSUE THREAD

**Issue by valaxkong** [google/glog#1063]
I saw the README said glog can be incorporated into custom projects using the CMake command `add_subdirectory`. I tried it like this
```CMake
FetchContent_Declare(
  glog
  GIT_REPOSITORY https://github.com/google/glog.git
  GIT_TAG        v0.6.0
)
FetchContent_GetProperties(glog)
if(NOT glog_POPULATED)
  FetchContent_Populate(glog)
  add_subdirectory(${glog_SOURCE_DIR})
endif()
```
When building as a submodule of my projects, I found those template codes in xxx.h.in files have not been replaced to generate xxx.h file. How to do things right? Thanks for your help.

**Comment by valaxkong** [comment]
I found the solutions.
```CMake
FetchContent_Declare(
  glog
  GIT_REPOSITORY https://github.com/google/glog.git
  GIT_TAG        v0.6.0
)
FetchContent_GetProperties(glog)
if(NOT glog_POPULATED)
  FetchContent_Populate(glog)
  add_subdirectory(${glog_SOURCE_DIR} `${glog_BINARY_DIR}`)
endif()
```
And I will give a PR later.

**Comment by sergiud** [comment]
`add_subdirectory` mentioned in the docs does not use `FetchContent`. You need to specify the build directory only for the latter explicitly.

**Comment by sergiud** [comment]
The issue is not actionable. You can however extend the `README` with a link to [CMake reference documentation](https://cmake.org/cmake/help/latest/module/FetchContent.html#overview) that explains how to use `FetchContent` correctly if you want.

**Comment by valaxkong** [comment]
@sergiud I opened a PR which gives an example to show the usage of FetchContent and add_subdirectory. https://github.com/google/glog/pull/1067
