### ISSUE TITLE
Customizing the Log Line Prefix

### ISSUE THREAD

**Issue by whitecat346** [google/glog#1073]
I tried to customizing the Log Line Prefix Format as in [Customizing the Log Line Prefix](https://github.com/google/glog?tab=readme-ov-file#id11), but he only prompts for the Connot resolve symbol "InstallPrefixFormatter". What should I do about this? 

- glog Version: 0.6.0 
- Visual Studio Version: Microsoft Visual Studio Community 2022 Preview 17.9.0 Preview 5.0 
- Re:Sharper Version: JetBrains ReSharper 2023.3.2 Build 233.0.20231218.91950 built on 2023-12-18 
- CMake version: 3.26.4

(This issue was created using a translator)

![glog](https://github.com/google/glog/assets/64885812/4f749a7d-3d9a-4242-b7c5-a14d77e61c69)

**Comment by sergiud** [comment]
You were looking at the documentation for the development version of glog 0.7.0 which introduced new functions. You need to [consult the documentation for version 0.6.0](https://github.com/google/glog/tree/v0.6.0?tab=readme-ov-file#custom-log-prefix-format) instead.

**Comment by whitecat346** [comment]
Ok, I'll try that, thanks for your reply.
