### ISSUE TITLE
Abseil or glog: what's the maintenance status?

### ISSUE THREAD

**Issue by JasonMarechal25** [google/glog#1095]
Hello
Stumble upon an issue mixing glog and ortools and found this comment:
https://github.com/google/or-tools/issues/2378#issuecomment-1413701949

> At this point, the only official google logging code is the abseil one. So I will close this issue.

Which logging library is considered "official" or supported?

**Comment by sergiud** [comment]
glog is a community maintained Google project. Anything else depends on your definition of "official" and "supported".
