### ISSUE TITLE
Cmake --build build Error

### ISSUE THREAD

**Issue by 7rwang** [google/glog#1096]
When I use `cmake --build build` I encountered some errors such as error:
 no member named 'exchange' in namespace 'std'
          ctr_(std::exchange(other.ctr_, 0)),
               ~~~~~^

I'm wondering whether the compiler default version matteres

**Comment by sergiud** [comment]
Aside from the incomplete log, latest glog requires a C++14 compliant compiler. Additionally, you need to take a look at the documentation that explains how to correctly integrate glog into own projects.

**Comment by sergiud** [comment]
I'm closing the issue since it is caused by incorrect usage of glog.
