### ISSUE TITLE
Stacktrace is not printed by failure signal handler when built with Bazel

### ISSUE THREAD

**Issue by kuntryn** [google/glog#1111]
When glog is built with Bazel, failure signal handler is unable to print stack trace.

*** Aborted at 1720166741 (unix time) try "date -d @1720166741" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x3e8000070c7) received by PID 28701 (TID 0x7ffff478aa40) from PID 28871; stack trace: ***

This problem has occurred before and has been fixed, but now it has reappeared. https://github.com/google/glog/issues/346

**Comment by sergiud** [comment]
According to #851 this should be working. What glog version are using?

**Comment by kuntryn** [comment]
My mistake. The stacktrace is indeed printed, but it's not interpreted as symbols (function names)，`LOG(FATAL)` doesn't interpret either.

I'm using version 0.7.1 on bazel central registry: https://registry.bazel.build/modules/glog, building in debug mode `bazel build @//:target -c dbg`

```
*** Aborted at 1720403914 (unix time) try "date -d @1720403914" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x3e800000c85) received by PID 3038 (TID 0x7ffff478aa40) from PID 3205; stack trace: ***
    @     0x5555571b5835 (unknown)
    @     0x5555571b57ed (unknown)
    @     0x5555571b57b4 (unknown)
    @     0x5555571b5784 (unknown)
    @     0x5555571b5751 (unknown)
    @     0x7ffff70a3ee8 (unknown)
    @     0x5555571b4c3b (unknown)
    @     0x5555571b5669 (unknown)
    @     0x5555571b490a (unknown)
    @     0x7ffff704c520 (unknown)
    @     0x7ffff712fe2e (unknown)
    @     0x555557277471 (unknown)
    @     0x55555727b48a (unknown)
    @     0x555557271bc7 (unknown)
    @     0x555557271a8e (unknown)
    @     0x5555563c94e1 (unknown)
    @     0x5555563c9b2a (unknown)
    @     0x7ffff7033d90 (unknown)
    @     0x7ffff7033e40 (unknown)
    @     0x5555563c7de5 (unknown)
    @                0x0 (unknown)
```
