### ISSUE TITLE
Why change to using cpp standard thread id instead of native os thread id?

### ISSUE THREAD

**Issue by kuntryn** [google/glog#1112]
https://github.com/google/glog/pull/1019
The thread id in log was changed to using cpp standard thread id starting from version 0.7.0. However, because the thread id of the standard library cannot be mapped to thread id of the operating system easily, it is less helpful when debugging, especially when used in combination with commands such as `ps` and `top`.

**Comment by sergiud** [comment]
As we switched to C++14 the goal was to eliminate platform specific boilerplate code. While your use case is probably valid, most of the users will be using standard threads which is the only well-defined approach to concurrency in C++. Also, with debuggers it is straightforward to identify the corresponding thread without any conversion.

**Comment by sergiud** [comment]
Closing the issue as the switch to portable code was deliberate.
