### ISSUE TITLE
build failed with clang-19

### ISSUE THREAD

**Issue by Patrick-ICT** [google/glog#1113]
I am following the build instruction in [Google Logging Library](https://google.github.io/glog/stable/build/#cmake).
The cmake command is 
`cmake -DCMAKE_CXX_COMPILER=clang++-19 -S . -B build -G "Unix Makefiles"`
then the build command generated the following error:
![err](https://github.com/user-attachments/assets/5c4a8c75-96b2-48f7-becb-893de8e2df85)
Does anyone know how to fix it?

**Comment by sergiud** [comment]
Thanks for the report.

Are you suggesting that the issue is specific to clang 19 and does not occur with a different compiler?

I believe the problem is rather similar to #823 and is in fact unrelated to clang 19.

**Comment by Patrick-ICT** [comment]
Oh yes, you are right. Thank you~
