### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by ForrestPi** [google/glog#1133]
/usr/bin/ld: /usr/local/lib/libgflags_nothreads.a(gflags.cc.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libgflags_nothreads.a(gflags_reporting.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libgflags_nothreads.a(gflags_completions.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

centos gcc 10
gflags 2.2.2
cmake ..
make & make install

glog 0.7.1
cmake ..
make & make install

**Comment by sergiud** [comment]
Please use the search: this gflags issue has been [discussed many times before](https://github.com/google/glog/issues/983#issuecomment-1845345695).
