### ISSUE TITLE
Many wrong NUL to the log file

### ISSUE THREAD

**Issue by BaiCai1990** [google/glog#1134]
![log bug](https://github.com/user-attachments/assets/00b0a476-8572-4e71-afb4-f2d41246d5c6)
![image](https://github.com/user-attachments/assets/337fcc8e-d4ff-4cf9-b9c7-b1667fcf21c6)
The first image is the original hexadecimal c_string,
The second image is the actual Glog output, with many NULs at the end.
Why is that?

**Comment by sergiud** [comment]
I've no idea what I'm looking at.

The provided issue description as such is not actionable as it's missing basic information.

**Comment by sergiud** [comment]
Closing due to lack of information.
