### ISSUE TITLE
doc/glog.html should be readable online (probably as google.github.io/glog)

### ISSUE THREAD

**Issue by nodakai** [google/glog#114]
Not nice:
* https://raw.githubusercontent.com/google/glog/master/doc/glog.html

_Cf._
* https://help.github.com/articles/user-organization-and-project-pages/

**Comment by david-y-lam** [comment]
merge into https://github.com/google/glog/issues/39?

**Comment by nodakai** [comment]
Closing in favor of #39. Saddened to see this project is no longer actively maintained.
