### ISSUE TITLE
Allow a log file to be simply named "foobar.log" with no appended string

### ISSUE THREAD

**Issue by KevinLucidyne** [google/glog#124]
I want to create a simple logfile of the form "foobar.log" without the time_pid_string being appended.  I have tried

```
google::SetLogDestination(google::INFO, "/lti/ImageProcessing/Backbone/logs/foobar.log");
google::InitGoogleLogging("");
```

but this results in a log file of the form "foobar.logyyyymmdd-mmmmm.nnnn".

**Comment by AlexandreBurel** [comment]
In the file https://github.com/google/glog/blob/master/src/glog/logging.h.in on line 270 you will find the following indication:
```
// Unless otherwise specified, logs will be written to the filename
// "<program name>.<hostname>.<user name>.log.<severity level>.", followed
// by the date, time, and pid (you can't prevent the date, time, and pid
// from being in the filename).
```
Even if you use SetLogFilenameExtension(".log"), you will get "foobar.logyyyymmdd-mmmmm.nnnn"

And I totally agree with you, it would be great to have logs with the expected extension (especially for Windows users)
