### ISSUE TITLE
 cannot find -lgflags

### ISSUE THREAD

**Issue by gaurav16gupta** [google/glog#128]
_I am building glog for Android NDK. Getting this error while building-_ 

[ 91%] Building CXX object CMakeFiles/stl_logging_unittest.dir/src/stl_logging_unittest.cc.o
/home/gaurav/deeplearning/caffe-android-lib/glog/src/logging_unittest.cc:641:3: error: #error There is no way to do glob.
 # error There is no way to do glob.
   ^
Linking CXX executable symbolize_unittest
cc1plus: warning: unrecognized command line option "-Wno-unnamed-type-template-args"
make[2]: **\* [CMakeFiles/logging_unittest.dir/src/logging_unittest.cc.o] Error 1
make[1]: **\* [CMakeFiles/logging_unittest.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
/home/gaurav/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lgflags
collect2: error: ld returned 1 exit status
make[2]: **\* [symbolize_unittest] Error 1
make[1]: **\* [CMakeFiles/symbolize_unittest.dir/all] Error 2
Linking CXX executable demangle_unittest
/home/gaurav/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lgflags
collect2: error: ld returned 1 exit status
make[2]: **\* [demangle_unittest] Error 1
make[1]: **\* [CMakeFiles/demangle_unittest.dir/all] Error 2
Linking CXX executable stl_logging_unittest
/home/gaurav/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lgflags
collect2: error: ld returned 1 exit status
make[2]: **\* [stl_logging_unittest] Error 1
make[1]: **\* [CMakeFiles/stl_logging_unittest.dir/all] Error 2
make: **\* [all] Error 2

_Any suggestion?_

**Comment by sergiud** [comment]
What's the output of `$ cmake -L <your-build-dir> | grep gflags_DIR`?

**Comment by Stark123** [comment]
_It is -_
gflags_DIR:PATH=/home/gaurav/deeplearning/caffe-android-lib/gflags-2.1.2/build

**Comment by sergiud** [comment]
Seems to be correctly set . Can you post the content of the CMake variable `gflags_LIBRARIES`, for instance by putting `message ("${gflags_LIBRARIES}")` below the `find_package (gflags)` line and running cmake?

**Comment by Stark123** [comment]
output is **gflags**
Does it mean it is not getting path for gflags_LIBRARIES ?

**Comment by Stark123** [comment]
Okay I manually provided the path for gflags_LIBRARIES. Now I am not getting "cannot find -lgflags" error. But still this last error remains-

caffe-android-lib/glog/src/logging_unittest.cc:641:3: error: #error There is no way to do glob.
 # error There is no way to do glob.
   ^
cc1plus: warning: unrecognized command line option "-Wno-unnamed-type-template-args"
make[2]: *** [CMakeFiles/logging_unittest.dir/src/logging_unittest.cc.o] Error 1
make[1]: *** [CMakeFiles/logging_unittest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....


In logging_unittest.cc the Flag HAVE_GLOB_H is not defined. 
Any suggestions?

**Comment by sergiud** [comment]
Have you  tried building glog using autotools, i.e., using `./configure && make`?
