### ISSUE TITLE
Set GLOG_FOUND, GLOG_INCLUDE_DIR and GLOG_LIBRARY variables in glog-config.cmake.in

### ISSUE THREAD

**Issue by flm8620** [google/glog#133]
I installed glog under Windows using VS2015 and CMake. I got the output libraries, headfiles together with `glog-config.cmake`. It seems that the generated file `glog-config.cmake` doesn't set these three variables.

According to:
https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file
https://coderwall.com/p/qej45g/use-cmake-enabled-libraries-in-your-cmake-project-iii
Maybe we should use `set_and_check ( foo_INCLUDE_DIRS "@PACKAGE_foo_INCLUDE_DIRS@")` ?
Or maybe I didn't run the cmake process correctly?

**Comment by sergiud** [comment]
Refer to the [documentation](https://github.com/google/glog/blob/master/cmake/INSTALL.md) on how to consume glog in a CMake project.

Regarding `GLOG_FOUND` see #112. As for the rest, glog provides an import target. `GLOG_INCLUDE_DIR` and `GLOG_LIBRARY`are thus not needed.

**Comment by flm8620** [comment]
Thank you. So that is to say, variables like `${FOO_LIBRARIES} `and `${FOO_INCLUDE_DIRS}` is not a  universal standard for CMake? Or it is more a method used by FindFoo.cmake, not foo-config.cmake ?

**Comment by sergiud** [comment]
It's a legacy way of providing access to cached variables in find modules in CMake up to version 2.6.  CMake now supports imported targets which are obviously much easier to use and therefore preferred over predefined variables. Imported targets also allow to create relocatable packages and manage their dependencies easily.

**Comment by flm8620** [comment]
Thanks for your explanation. Learnt a new thing today.

**Comment by sergiud** [comment]
Glad I could help.

By the way, you can use imported targets in find modules as well. In fact, CMake incrementally adds support for imported targets to existing find modules. See for example https://cmake.org/cmake/help/v3.6/module/FindBoost.html.

**Comment by flm8620** [comment]
Just to add one thing. I finally figured out why I'm doing it wrong.
I try to compile ceres-solver-1.11.0 using CMake together with MSVC. I had compiled and installed Glog in the same way. 
I tried to use directly the config mode of find_package(glog) in ceres-solver. Because I want to use some "simple direct" method without help of `FindGlog.cmake` which is provided by ceres-solver. But I didn't understand that `${FOO_LIBRARIES}` is not a standard.
In fact `FindGlog.cmake` provided by ceres-solver is aware of Glog's CMake strategy. And `FindGlog.cmake` will create `${GLOG_INCLUDE_DIR}` `${GLOG_LIBRARY}` once it found glog. So ceres-solver use FindGlog.cmake as a wrapper to use glog in a traditional way.
Quite a good lesson for me, and for anyone who doesn't fully understand cmake.
Thanks again.

**Comment by sergiud** [comment]
Ceres is one of the reasons I added CMake support to glog. Also, there oncoming native CMake support for [SuiteSparse and CXSparse](/sergiud/SuiteSparse/tree/cmake). I also [refactored Ceres](/sergiud/ceres-solver/tree/cmake) to support the CMakefied version of glog and SuiteSparse.

**Comment by flm8620** [comment]
I just failed to link Ceres to Glog because of Ceres' old way to use ${GLOG_LIBRARIES}.
I compile Glog as a static lib under VS2015. So `GOOGLE_GLOG_DLL_DECL ` is defined to `""` (while in dynamic library mode, this value is defined to `__declspec(dllimport)`)

And this macro should be propagated to any CMake target which links to static glog lib. This can be done automatically through `target_link_libraries(mylib glog::glog)`, as indicated in [Glog's CMake doc](https://github.com/google/glog/blob/master/cmake/INSTALL.md). Or more info in [cmake_buildsystem](https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#manual:cmake-buildsystem(7)) and [target_link_libraries()](https://cmake.org/cmake/help/v3.0/command/target_link_libraries.html#command:target_link_libraries).

But somehow Ceres uses its own FindGlog.cmake to wrap glog's lib location in `${GLOG_LIBRARIES}`, which is something like `C:\somepath\Lib\glog.lib`. And then Ceres uses directly `target_link_libraries(ceres ${CERES_LIBRARY_DEPENDENCIES})`, which contains the string  `${GLOG_LIBRARIES}`.  So no Import Target's properties is propagated to Ceres, including `GOOGLE_GLOG_DLL_DECL`. And VS2015 failed to link Ceres to Glog.

So it's important to let every cmake coder to adopt better cmake style of find_package()

**Comment by sergiud** [comment]
You can simply remove `FindGlog.cmake` and set `GLOG_LIBRARIES` to `glog::glog`. There maybe other places in Ceres `CMakeLists.txt` that may need adjustments though.
