### ISSUE TITLE
Errors occur with building visual studio 15

### ISSUE THREAD

**Issue by LorddBaelish** [google/glog#139]
Anyone tried building glog with visual studio 2015? .. 

It's visual studio 2015. I've included directories for headers and glog.lib file. but with build it shows following error massage.

error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function main

**Comment by sergiud** [comment]
So is it Visual Studio 15 or Visual Studio 2015? They are not the same thing.

**Comment by LorddBaelish** [comment]
I'm sorry for the lack of details... 
It's visual studio 2015. I've included directories for headers and glog.lib file. but with build it shows following error massage.

error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QEAAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function main

**Comment by sergiud** [comment]
My guess is that you built glog as a static library but linking it as dynamic. This can happen for instance if you compiled glog using CMake and integrated it into a Visual Studio 2015 project without passing all the relevant preprocessor flags set by CMake.

If you used CMake to build glog, please refer to the [documentation](/google/glog/blob/master/cmake/INSTALL.md) how to you use it correctly.

**Comment by LorddBaelish** [comment]
@sergiud  Thank you a lot for your detailed answer. But since being a newbie myself, could you please explain the proper steps to use glog static library with visual studio 2015? . My project contains a cpp file included with glog/logging.h .

A code segment related to my error massage from logging.h shown below..

#ifndef GOOGLE_GLOG_DLL_DECL
# if defined(_WIN32) && !defined(__CYGWIN__)
#   define GOOGLE_GLOG_DLL_DECL  __declspec(dllimport)
# else
#   define GOOGLE_GLOG_DLL_DECL
# endif
#endif
