### ISSUE TITLE
make error on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by ramanpreet9** [google/glog#140]
I am getting the following error after ./configure and  make

src/logging_unittest-logging_unittest.o: In function `__static_initialization_and_destruction_0(int, int)':
logging_unittest.cc:(.text+0xe4f4): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
logging_unittest.cc:(.text+0xe5b7): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
logging_unittest.cc:(.text+0xe634): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
logging_unittest.cc:(.text+0xe669): undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
collect2: error: ld returned 1 exit status
make: *** [logging_unittest] Error 1

I am not sure what needs to be done to run it without error.

**Comment by Google1234** [comment]
encounter same question

**Comment by Vimos** [comment]
Please print 
    
    ldconfig -p | grep gflag

**Comment by Google1234** [comment]
libgflags_nothreads.so.2.1 (libc6,x86-64) => /usr/lib64/libgflags_nothreads.so.2.1
	libgflags_nothreads.so (libc6,x86-64) => /usr/lib64/libgflas_nothreads.so
	libgflags.so.2.1 (libc6,x86-64) => /usr/lib64/libgflags.so.2.1
	libgflags.so (libc6,x86-64) => /usr/lib64/libgflags.so
Thanks,but it doent work.
Maybe i install gflags berfore glog .

**Comment by Vimos** [comment]
OK, my version is 2.2, maybe you can give it a try.

**Comment by Google1234** [comment]
how to unintall or upgrade gflags? @Vimos

**Comment by Google1234** [comment]
In caffe official website：
Note that glog does not compile with the most recent gflags version (2.1), so before that is resolved you will need to build with glog first.
So,I think i need uninstall or upgrade gflags first 
THX

**Comment by Vimos** [comment]
I used their master head, https://github.com/gflags/gflags.git.

**Comment by jupinter** [comment]
use  libgflags.a compiled from source code, not installed using apt-get
glog has the same problem

**Comment by sergiud** [comment]
I assume, the issue is not present anymore.
