### ISSUE TITLE
【make error】googletest.h:100: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'

### ISSUE THREAD

**Issue by jaikonee** [google/glog#142]
$  make 
as following：
libtool: link: g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -g -O2 -pthread -o .libs/logging_unittest src/logging_unittest-logging_unittest.o  ./.libs/libglog.so -lgflags -lpthread -pthread
src/logging_unittest-logging_unittest.o: In function `__static_initialization_and_destruction_0':
/home/jie/Downloads/glog-master/src/googletest.h:93: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
/home/jie/Downloads/glog-master/src/googletest.h:94: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
/home/jie/Downloads/glog-master/src/googletest.h:96: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/home/jie/Downloads/glog-master/src/googletest.h:100: undefined reference to `google::FlagRegisterer::**FlagRegisterer**<int>(char const*, char const*, char const*, int*, int*)'
collect2: error: ld returned 1 exit status
make: *** [logging_unittest] Error **1**
 so,how to solve them ?

**Comment by chetgnegy** [comment]
Looks like you're missing gFlags.
https://github.com/gflags/gflags

It looks like there is also a cmake option where you can tell it whether or not you actually have gFlags. I'm building with bazel rather than make or cmake, so I don't have much more information on that procedure.

**Comment by zheng-rong** [comment]
Hi I encounter the similar problem. 
My environment is :
Ubuntu 14.04 LTS,
cmake 3.2.2
gflags: latest version from Github master, installed using
```
ccmake..
make
sudo make install
```
glog: release 0.3.5, installed using
```
./configure
make
sudo make install
```
I didn't set the namespace of these two lib explicitly.
I encountered similar error during building glog:
undefined reference to google::FlagRegisterer::FlagRegisterer
But after I clean everything and re-build gflags and flog, passsed.
Then I tried to build Google-Cartographer, failed again.

```
[ 70%] Linking CXX executable ../bin/libmv_homography
Building CXX object internal/ceres/CMakeFiles/autodiff_test.dir/autodiff_test.cc.o
/usr/local/lib/libglog.a(libglog_la-logging.o): In function `__static_initialization_and_destruction_0':
/home/arkin/ros_code/glog-0.3.5/src/logging.cc:106: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/home/arkin/ros_code/glog-0.3.5/src/logging.cc:108: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
......
```
Is the error of making Cartographer caused by gflags and glog? 
How to fix this?

Thanks.

**Comment by mengjiahao** [comment]
as newer gflags changes the google namespace to gflags, i compiled with gflags_2.0 and it works

**Comment by jinfagang** [comment]
@mengjiahao  I think glog better catch up gflag updates. It built always error which both gflags 2.2 or master branch.... Why google own lib conflict each other?
