### ISSUE TITLE
Expose DumpStackTraceToString to application/user

### ISSUE THREAD

**Issue by sudhagarc** [google/glog#144]
Currently, it seems like only way to get call stack (backtrace or stack trace) is to set FLAGS_log_backtrace_at variable with the desired filename and line number. However, this is a global variable and when used in multithreaded environment, it leads to data corruption issue, hence process crash. One way to prevent it would be to use locks and allow only one thread to dump the call stack.

I'm wondering whether it's possible to expose DumpStackTraceToString utility to application or user. Would that make it lock-free to get the stack trace and make it performant? or, is there any other alternative to achieve the same i.e., get call stack in multithreaded application where more than one thread can simultaneously invoke logging with backtrace set.

**Comment by ijesonchen** [comment]
Since it's a function and you can declear it any where, e.g. in your own header and just use it. Don't forget to link glog library.
In my code, I declare it in my header file like this:

namespace google {
namespace glog_internal_namespace_ {
    void DumpStackTraceToString(std::string *stacktrace);
}
}  // namespace google

And use it like this:

if (condition){
    std::string stack;
    google::glog_internal_namespace_::DumpStackTraceToString(&stack);
    LOG(ERROR) << "ERROR " << err_string << ". stack\n" << stack;
}

And it seems working well.

**Comment by amosbird** [comment]
It generates a hidden symbol by default:

```
❯ readelf --demangle -s --wide contrib/glog/libglogd.so.0.5.0 | rg DumpStackTraceToString
   980: 00000000000317e0    39 FUNC    LOCAL  HIDDEN    13 google::glog_internal_namespace_::DumpStackTraceToString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)
```

static build works fine though.

Am I miss anything?
