### ISSUE TITLE
dllimport is defined even when glog is built as a static library causing compilation error

### ISSUE THREAD

**Issue by jasjuang** [google/glog#155]
I am on Windows 10, Visual Studio 2015. I install glog through the standard procedure of

``````
git clone https://github.com/google/glog/
mkdir build 
cd build
cmake -A x64 ..
``````

It generates a solution file. I build the entire solution and build the INSTALL project.

A static library is generated. However, when I am linking glog with my own code I get compilation error similar to #139

``````
error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessage::LogMessage(char const *,int)" (__imp_??0LogMessage@google@@QEAA@PEBDH@Z) 
`````` 

It is treating glog as if it's build as shared dll library instead of a static library. When I back trace and look into logging.h, GOOGLE_GLOG_DLL_DECL is defined as __declspec(dllimport) which is the root cause of the error. I can work around this if I force define GOOGLE_GLOG_DLL_DECL to be nothing by myself. No other external libraries I am using requires me to define a macro myself to get over this problem, so I am assuming glog should have the capability to take care of this itself. Can someone please fix this?

**Comment by sergiud** [comment]
Do you get the error if you use the build directory package config?

**Comment by sergiud** [comment]
Right now it's not clear in what configuration this can happen. `GOOGLE_GLOG_DLL_DECL` is defined as `__declspec(dllimport)` only if `GOOGLE_GLOG_DLL_DECL` has not been previously defined.

In CMakeLists.txt you can check that for static builds `GOOGLE_GLOG_DLL_DECL` is [transitively defined](/google/glog/blob/master/CMakeLists.txt#L434), overriding the definition of `GOOGLE_GLOG_DLL_DECL` in logging.h.

Under this circumstances, it seems likely that your target does not link to the imported target `glog::glog`.

**Comment by jasjuang** [comment]
I was able to build and install glog without a problem. The problem happens when I am linking glog with my own code. Below is my CMakeLists with glog related section

``````
find_package( GLOG REQUIRED)
include_directories(${GLOG_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} ${GLOG_LIBRARIES})
``````

For some reason if I use `find_package` in "config" mode, `${GLOG_INCLUDE_DIRS}` is empty, resulting in compilation error (is this another potential bug?)

``````
C1083	Cannot open include file: 'glog/logging.h': No such file or directory	
``````

so I am forced to write my own FindGLOG.cmake and use `find_package` in "module" mode, my FindGLOG.cmake is fairly standard like below

``````
set(PFX86 "PROGRAMFILES(X86)")

# Look for the header file.
find_path(GLOG_INCLUDE_DIRS NAMES glog/logging.h HINTS
        $ENV{${PFX86}}/glog/include
        $ENV{${PFX86}}/google-glog/include)

# Look for the library.
find_library(GLOG_LIBRARY NAMES libglog glog HINTS
            $ENV{${PFX86}}/glog/lib
            $ENV{${PFX86}}/google-glog/lib)

set(GLOG_LIBRARIES ${GLOG_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLOG DEFAULT_MSG GLOG_LIBRARIES
                                GLOG_INCLUDE_DIRS)
``````

And for the full compilation arguments it's 

``````
/GS /TP /W4 /wd"4127" /Zc:wchar_t /I"C:\Program Files (x86)\glog\include" /I"C:\Program Files (x86)\gflags\Include" /Gm- /O2 /Ob2 /sdl /Fd"testlib.dir\Release\vc140.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "GFLAGS_IS_A_DLL=0" /D "CMAKE_INTDIR=\"Release\"" /D "testlib_EXPORTS" /D "_WINDLL" /D "_MBCS" /errorReport:prompt /WX /Zc:forScope /GR /Gd /MD /Fa"Release/" /EHsc /nologo /Fo"testlib.dir\Release\" /Fp"testlib.dir\Release\testlib.pch" 
``````

**Comment by sergiud** [comment]
glog does not export neither `GLOG_INCLUDE_DIRS` nor `GLOG_LIBRARIES` variables. You're using a third party find module. Please refer the documentation in glog's `cmake` directory on how to use glog.

**Comment by jasjuang** [comment]
Wow, `target_link_libraries (myapp glog::glog)` actually works. I am still confused how it's able to find logging.h without specifying any `include_directories` though ....

**Comment by jasjuang** [comment]
Another thing I would like to add is `target_link_libraries (myapp glog::glog)` does not work on Ubuntu if glog is installed through `sudo apt-get install libgoogle-glog-dev`. I had to build glog from source just like I did in windows to make it work

**Comment by sergiud** [comment]
No wonder. CMake support was added after the latest release (i.e., 0.3.4) of glog.
