### ISSUE TITLE
Calling glog module bugs before entering main function

### ISSUE THREAD

**Issue by snoopspy** [google/glog#17]
Hi, thank you for your great product, glog. This time, I've found an abnormal bug in glog.

glog code can be called before entring main function on condition that
1. There is a class that contains a constructor, and in this constructor, glog module is called.
2. There is a global object of the class.

In this case, an application terminates unexpectedly when executed. Here is a sample code(based on glog v0.3.3).
https://gist.github.com/snoopspy/642195da3f91cca811bc

Thank you in advance.

**Comment by ukai** [comment]
you should avoid such coding.

https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables
> The order in which class constructors and initializers for static variables are called is only partially specified in C++ and can even change from build to build, which can cause bugs that are difficult to find.
