### ISSUE TITLE
Logging to the same file from multiple processes

### ISSUE THREAD

**Issue by bharathmysore** [google/glog#170]
I have a multi process server and want to log entries from all the process to the same file.
I am using 0.3.3 which provides separate log file for each process, in our case the servers are short leaved and we accumulate a lot of small file.

In my envirornment, i can remove the PidHasChanged() and get it working to some extent. Since I have multiple writer and no synchronization between them they may overwrite one another.

Is there any solution to handle this issue ?
Any glog server running locally on my machine, to which i can send the logs over local socket ? 
Or any LOCKFILE kind of mechanism

**Comment by Huangyong657** [comment]
excuse me. I would like to ask where is the merge and how could I logging to the same file from multiple processes?
could I change every file's name from every process to the same to solve the problem now?
