### ISSUE TITLE
Remove autoconf dependencies

### ISSUE THREAD

**Issue by inspire1989** [google/glog#178]
Hi,
is it possible to remove the autoconf dependency when compiling glog? I'd like to get rid of this, because it must be installed on every persons' computer who works with it. Alternatively, is it possible to use autoconf just ONCE and then skip the autoconf execution because all necessary files were already generated? I could not figure out how this can be done. Can you help me?
Thanks!

**Comment by sergiud** [comment]
Not sure what are you asking.
