### ISSUE TITLE
How to disable implicit endl with LOG(INFO)

### ISSUE THREAD

**Issue by jasjuang** [google/glog#180]
I have a code that will be running iteratively for 1000 loops and I want to print out the progress. If I do something like

``````
for (int i = 0; i < 1000; ++i) {
 LOG(INFO) << "iteration " << i;

 // heavy calculation
}
``````
This will print out 1000 lines on the console which is not very desirable, so there is a standard trick that can be used to solve this is 

``````
for (int i = 0; i < 1000; ++i) {
  std::cout << "\r" << i << std::flush;

 // heavy calculation
}
``````

This will only print one line and the numbers will be changing from 1 to 1000, however the below does not work

``````
for (int i = 0; i < 1000; ++i) {
  LOG(INFO) << "\r" << i << std::flush;

 // heavy calculation
}
``````

Because there is an implicit endl with LOG(INFO) so the flush doesn't work. Is there a way to disable it?

**Comment by sergiud** [comment]
This kind of output does not make any sense for a logging framework where the goal is to log every bit of information. Just use standard output for this.
