### ISSUE TITLE
error LNK2001: unresolved external symbol(on windows,vs 2013)

### ISSUE THREAD

**Issue by laixiaodong** [google/glog#181]
__declspec(dllimport) public: __cdecl google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)" (__imp_??0CheckOpMessageBuilder@base@google@@QEAA@PEBD@Z)

I got the source code and cmake, Compiler it with vs2013,then i got the problem 
anyone know?please!
thanks~~

**Comment by sergiud** [comment]
You need to provide more details. Closing the issue for now.
