### ISSUE TITLE
configure: error: working directory cannot be determined

### ISSUE THREAD

**Issue by LazyPlanet** [google/glog#183]
when install on

[game@iZ2zeerthpe64c45eu5v7eZ glog]$ cat /etc/redhat-release 
**CentOS release 6.8 (Final)**

[game@iZ2zeerthpe64c45eu5v7eZ glog]$ ./configure 
**configure: error: working directory cannot be determined**

**Comment by kamalelsaaid** [comment]
same error in ubuntu ? did you find a solution ?

**Comment by LazyPlanet** [comment]
I give it up, spdlog is better.
