### ISSUE TITLE
Version number for 0.3.5 in CMakeLists.txt is still 0.3.4

### ISSUE THREAD

**Issue by ttencate** [google/glog#187]
Thank you @shinh for rolling a new release! Unfortunately there seems to be another place where the version number should have been bumped:
https://github.com/google/glog/blob/v0.3.5/CMakeLists.txt#L17

**Comment by shinh** [comment]
Thanks a lot for the quick report! I've created v035 branch (because I don't want  https://github.com/google/glog/pull/186 which isn't tested well yet in 0.3.5) and updated the tag. I hope this works.

https://github.com/google/glog/commit/a6a166db069520dbbd653c97c2e5b12e08a8bb26
