### ISSUE TITLE
Homebrew SHA256 mismatch

### ISSUE THREAD

**Issue by lorenzb** [google/glog#189]
Mac OS users using homebrew currently cannot install glog due to a SHA256 checksum mismatch that was likely triggered by retagging the glog 0.3.5 release:
https://github.com/Homebrew/homebrew-core/issues/13495

Could you please confirm that the issue was indeed caused by retagging v035 and that the commit that is now tagged with v035 is valid?

Thank you for working on glog! Your project is very useful to me and many others.

**Comment by ilovezfs** [comment]
@shinh @ukai gentle ping on this.

**Comment by shinh** [comment]
Sorry for the problem and the latency. Yeah I have re-tagged to include https://github.com/google/glog/commit/a6a166db069520dbbd653c97c2e5b12e08a8bb26. I didn't realize adjusting a release 1 day after the release could cause this kind of issue. I won't modify tags in future releases.

**Comment by ilovezfs** [comment]
@shinh thank you for confirming. :heart:

>I won't modify tags in future releases.

Thank you!
