### ISSUE TITLE
Why there is no debug level

### ISSUE THREAD

**Issue by zhimingxie** [google/glog#190]
Mostly it is useful to print more detail info under no production environment by same binary which is not compiled with NDEBUG .

**Comment by shinh** [comment]
I guess DLOG, DCHECK, and DFATAL are what you want.

**Comment by zhimingxie** [comment]
Those have to rebuild the binary rather than can be controlled by config file easily.

**Comment by to0** [comment]
I guess VLOG levels is what you want if looking for runtime control.

**Comment by zhimingxie** [comment]
Yes, VLOG looks like something what I want
