### ISSUE TITLE
Allow coredump to be generated upon LOG(FATAL)

### ISSUE THREAD

**Issue by zhitaoli** [google/glog#192]
In certain environment, it's pretty hard to debug any problem once the process has aborted due to LOG(FATAL).

Can we add some support to optionally generate a coredump before calling exit()?

**Comment by DariuszOstolski** [comment]
When LOG(FATAL) is executed glog calls abort function and if configured properly it will generate a core dump, but you have to configure your environment.  By default on most Linux systems generating core dump is turned off that's why you don't get a core dump when LOG(FATAL) is executed.
