### ISSUE TITLE
try_compile in DetermineGflagsNamespace generates invalid compile command

### ISSUE THREAD

**Issue by ambasta** [google/glog#193]
Hi,

Currently try_compile is specified as..

```
try_compile (${VARIABLE}
        "${CMAKE_BINARY_DIR}" "${_check_file}"
        COMPILE_DEFINITIONS "${CMAKE_REQUIRED_DEFINITIONS}" -DGFLAGS_NAMESPACE=${_namespace}
        LINK_LIBRARIES "${gflags_LIBRARIES}"
        CMAKE_FLAGS -DINCLUDE_DIRECTORIES:STRING="${gflags_INCLUDE_DIR}"
        OUTPUT_VARIABLE OUTPUT)
```

However, when `${CMAKE_BINARY_DIR}` is set to `/home/amitprakash/CLionProjects/or-tools/cmake-build-manual/glog_project/src/glog` and `${gflags_INCLUDE_DIR}` is set to `/home/amitprakash/CLionProjects/or-tools/cmake-build-manual/gflags_project/src/gflags/include`, the build command generated by try_compile is ..

`/usr/bin/c++  -DGFLAGS_NAMESPACE=google -I/home/amitprakash/CLionProjects/or-tools/cmake-build-manual/glog_project/src/glog/CMakeFiles/CMakeTmp/\"/home/amitprakash/CLionProjects/or-tools/cmake-build-manual/gflags_project/src/gflags/include\"  -fPIE   -o CMakeFiles/cmTC_6795b.dir/DetermineGflagsNamespace.cxx.o -c /home/amitprakash/CLionProjects/or-tools/cmake-build-manual/glog_project/src/glog/CMakeFiles/CMakeTmp/DetermineGflagsNamespace.cxx
`

I'm unsure why, but the include dir has changed from an ABSPATH to a RELPATH of the form `${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/${gflags_INCLUDE_DIR}`

The same happens when glog is installed to /usr/include, but the try_compile succeeds anyways, since /usr/include is part of system include dirs

**Comment by ambasta** [comment]
Rewriting it as 

```
try_compile (${VARIABLE}
        "${CMAKE_BINARY_DIR}" "${_check_file}"
        COMPILE_DEFINITIONS "${CMAKE_REQUIRED_DEFINITIONS}" -DGFLAGS_NAMESPACE=${_namespace}
        LINK_LIBRARIES "${gflags_LIBRARIES}"
        CMAKE_FLAGS "-DINCLUDE_DIRECTORIES:STRING=${gflags_INCLUDE_DIR}"
        OUTPUT_VARIABLE OUTPUT)
```
fixes the issue

**Comment by sergiud** [comment]
I don't follow. What's the difference between the two `try_compile` calls and what part of the original command is invalid?

**Comment by ambasta** [comment]
` 
CMAKE_FLAGS -DINCLUDE_DIRECTORIES:STRING="${gflags_INCLUDE_DIR}"
`
vs 
`
CMAKE_FLAGS "-DINCLUDE_DIRECTORIES:STRING=${gflags_INCLUDE_DIR}"
`

The difference is quotations

**Comment by sergiud** [comment]
Please give #209 a try and let me if the PR works for you.
