### ISSUE TITLE
[0.3.5] errors during make check

### ISSUE THREAD

**Issue by wookietreiber** [google/glog#194]
```console
$ make check
make  logging_striplog_test_sh demangle_unittest_sh signalhandler_unittest_sh
make[1]: Entering directory '/tmp/makepkg/google-glog/src/glog-0.3.5'
./src/logging_striplog_test.sh
In DBG mode; not checking strings
./src/logging_striplog_test.sh: line 76: 31221 Segmentation fault      (core dumped) ./logging_striptest2 2> /dev/null
PASS
./demangle_unittest  # force to create lt-demangle_unittest
Passed 3 tests

PASS
./src/demangle_unittest.sh
Mangled symbols (28 out of 381) found in demangle.dm:
_ZN3fLS13FLAGS_log_dirB5cxx11E
_ZN3fLS13FLAGS_vmoduleB5cxx11E
_ZN3fLS14FLAGS_log_linkB5cxx11E
_ZN3fLS15FLAGS_logmailerB5cxx11E
_ZN3fLS17FLAGS_log_dir_bufB5cxx11E
_ZN3fLS17FLAGS_vmodule_bufB5cxx11E
_ZN3fLS18FLAGS_log_link_bufB5cxx11E
_ZN3fLS19FLAGS_logmailer_bufB5cxx11E
_ZN3fLS20FLAGS_alsologtoemailB5cxx11E
_ZN3fLS22FLAGS_log_backtrace_atB5cxx11E
_ZN3fLS24FLAGS_alsologtoemail_bufB5cxx11E
_ZN3fLS26FLAGS_log_backtrace_at_bufB5cxx11E
_ZN6google14LogDestination10addresses_B5cxx11E
_ZN6google14LogDestination8hostnameB5cxx11Ev
_ZN6google14LogDestination9hostname_B5cxx11E
_ZN6google19CheckstrcmptrueImplB5cxx11EPKcS1_S1_
_ZN6google20CheckstrcmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google21GetLoggingDirectoriesB5cxx11Ev
_ZN6google23CheckstrcasecmptrueImplB5cxx11EPKcS1_S1_
_ZN6google24CheckstrcasecmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google24glog_internal_namespace_10MyUserNameB5cxx11Ev
_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev
_ZN6google7LogSink8ToStringB5cxx11EiPKciPK2tmS2_m
_ZN6google8StrErrorB5cxx11Ei
_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE12emplace_backIJS5_EEEvDpOT_
_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_M_realloc_insertIJRKS5_EEEvN9__gnu_cxx17__normal_iteratorIPS5_S7_EEDpOT_
_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_M_realloc_insertIJS5_EEEvN9__gnu_cxx17__normal_iteratorIPS5_S7_EEDpOT_
_ZNSt6vectorIPN6google7LogSinkESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_
Mangled symbols (28 out of 381) found in demangle.dm
make[1]: *** [Makefile:2062: demangle_unittest_sh] Error 1
make[1]: Leaving directory '/tmp/makepkg/google-glog/src/glog-0.3.5'
make: *** [Makefile:1907: check-am] Error 2
```

Even the first one - how could a segfault / core dump pass as a test?

**Comment by rganesan** [comment]
I'm running into this as well. This is with fedora 25 which defaults to GCC 6 as the compiler.

**Comment by vielmetti** [comment]
Also running into this, with Ubuntu 16.04 LTS on ARM64.

```
Mangled symbols (24 out of 380) found in demangle.dm:
_ZN3fLS13FLAGS_log_dirB5cxx11E
_ZN3fLS13FLAGS_vmoduleB5cxx11E
_ZN3fLS14FLAGS_log_linkB5cxx11E
_ZN3fLS15FLAGS_logmailerB5cxx11E
_ZN3fLS17FLAGS_log_dir_bufB5cxx11E
_ZN3fLS17FLAGS_vmodule_bufB5cxx11E
_ZN3fLS18FLAGS_log_link_bufB5cxx11E
_ZN3fLS19FLAGS_logmailer_bufB5cxx11E
_ZN3fLS20FLAGS_alsologtoemailB5cxx11E
_ZN3fLS22FLAGS_log_backtrace_atB5cxx11E
_ZN3fLS24FLAGS_alsologtoemail_bufB5cxx11E
_ZN3fLS26FLAGS_log_backtrace_at_bufB5cxx11E
_ZN6google14LogDestination10addresses_B5cxx11E
_ZN6google14LogDestination8hostnameB5cxx11Ev
_ZN6google14LogDestination9hostname_B5cxx11E
_ZN6google19CheckstrcmptrueImplB5cxx11EPKcS1_S1_
_ZN6google20CheckstrcmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google21GetLoggingDirectoriesB5cxx11Ev
_ZN6google23CheckstrcasecmptrueImplB5cxx11EPKcS1_S1_
_ZN6google24CheckstrcasecmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google24glog_internal_namespace_10MyUserNameB5cxx11Ev
_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev
_ZN6google7LogSink8ToStringB5cxx11EiPKciPK2tmS2_m
_ZN6google8StrErrorB5cxx11Ei
Mangled symbols (24 out of 380) found in demangle.dm
Makefile:2062: recipe for target 'demangle_unittest_sh' failed
make[1]: *** [demangle_unittest_sh] Error 1
```

**Comment by rosset** [comment]
issues with gcc-7.1.1 (fedora rawhide)

+ cd glog-0.3.5
+ make check
make  logging_striplog_test_sh demangle_unittest_sh signalhandler_unittest_sh
make[1]: Entering directory '/home/filiperosset/rpmbuild/extras/glog/glog-0.3.5'
./src/logging_striplog_test.sh
In DBG mode; not checking strings
./src/logging_striplog_test.sh: line 76: 20539 Segmentation fault      (core dumped) ./logging_striptest2 2> /dev/null
PASS
./demangle_unittest  # force to create lt-demangle_unittest
Passed 3 tests

PASS
./src/demangle_unittest.sh
Mangled symbols (22 out of 402) found in demangle.dm:
_ZN3fLS13FLAGS_log_dirB5cxx11E
_ZN3fLS13FLAGS_vmoduleB5cxx11E
_ZN3fLS14FLAGS_log_linkB5cxx11E
_ZN3fLS15FLAGS_logmailerB5cxx11E
_ZN3fLS20FLAGS_alsologtoemailB5cxx11E
_ZN3fLS22FLAGS_log_backtrace_atB5cxx11E
_ZN6google14LogDestination10addresses_B5cxx11E
_ZN6google14LogDestination8hostnameB5cxx11Ev
_ZN6google14LogDestination9hostname_B5cxx11E
_ZN6google19CheckstrcmptrueImplB5cxx11EPKcS1_S1_
_ZN6google20CheckstrcmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google21GetLoggingDirectoriesB5cxx11Ev
_ZN6google23CheckstrcasecmptrueImplB5cxx11EPKcS1_S1_
_ZN6google24CheckstrcasecmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google24glog_internal_namespace_10MyUserNameB5cxx11Ev
_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev
_ZN6google7LogSink8ToStringB5cxx11EiPKciPK2tmS2_m
_ZN6google8StrErrorB5cxx11Ei
_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE12emplace_backIJS5_EEEvDpOT_
_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_M_realloc_insertIJRKS5_EEEvN9__gnu_cxx17__normal_iteratorIPS5_S7_EEDpOT_
_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_M_realloc_insertIJS5_EEEvN9__gnu_cxx17__normal_iteratorIPS5_S7_EEDpOT_
_ZNSt6vectorIPN6google7LogSinkESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_
Mangled symbols (22 out of 402) found in demangle.dm
make[1]: *** [Makefile:2050: demangle_unittest_sh] Error 1
make[1]: Leaving directory '/home/filiperosset/rpmbuild/extras/glog/glog-0.3.5'
make: *** [Makefile:1897: check-am] Error 2
erro: Status de saída de /var/tmp/rpm-tmp.ftyk1a inválido (%check)


Erros na construção do RPM:
    Status de saída de /var/tmp/rpm-tmp.ftyk1a inválido (%check)
[filiperosset@raw glog]$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.1.1 20170718 (Red Hat 7.1.1-6) (GCC)

**Comment by vielmetti** [comment]
With the latest master, on aarch64, Ubuntu 16.04:

gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

```
Mangled symbols (18 out of 403) found in demangle.dm:
_ZN3fLS13FLAGS_log_dirB5cxx11E
_ZN3fLS13FLAGS_vmoduleB5cxx11E
_ZN3fLS14FLAGS_log_linkB5cxx11E
_ZN3fLS15FLAGS_logmailerB5cxx11E
_ZN3fLS20FLAGS_alsologtoemailB5cxx11E
_ZN3fLS22FLAGS_log_backtrace_atB5cxx11E
_ZN6google14LogDestination10addresses_B5cxx11E
_ZN6google14LogDestination8hostnameB5cxx11Ev
_ZN6google14LogDestination9hostname_B5cxx11E
_ZN6google19CheckstrcmptrueImplB5cxx11EPKcS1_S1_
_ZN6google20CheckstrcmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google21GetLoggingDirectoriesB5cxx11Ev
_ZN6google23CheckstrcasecmptrueImplB5cxx11EPKcS1_S1_
_ZN6google24CheckstrcasecmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google24glog_internal_namespace_10MyUserNameB5cxx11Ev
_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev
_ZN6google7LogSink8ToStringB5cxx11EiPKciPK2tmS2_m
_ZN6google8StrErrorB5cxx11Ei
Mangled symbols (18 out of 403) found in demangle.dm
```
