### ISSUE TITLE
autoconf build does not version the library

### ISSUE THREAD

**Issue by ahundt** [google/glog#196]
./configure; make install and cmake ..; make install produce different libraries

The cmake version doesn't create this missing library/symlink:
```
  /usr/local/opt/glog/lib/libglog.0.dylib
```
discovered in:
https://github.com/Homebrew/homebrew-core/pull/14379

**Comment by ilovezfs** [comment]
@shinh any idea what the problem here is? Thanks!

**Comment by andschwa** [comment]
CMake, not being Autotools, doesn't make use of libtool to version shared libraries (I imagine this is what's happening here). CMake can certainly be setup to add versions to libraries; it's just up to the owner to decide if they want that.

**Comment by sergiud** [comment]
Actually, CMake does [set the library version](https://github.com/google/glog/blob/master/CMakeLists.txt#L435-L436). However, I don't understand why `libglog.0.dylib` is expected instead of `libglog.3.dylib`? @ahundt Can you elaborate?

**Comment by andschwa** [comment]
(I stand corrected, Glog's is even setup to version the libraries. Nice!)

**Comment by ahundt** [comment]
Homebrew has automated compilation and install scripts. As of the latest release at the time of writing the dylib file that was placed in the folder by the make script was `libglog.0.dylib`. I think the issue is that the library names should be consistent between the build tools, and the installed CMake config files, like glogConfig.cmake should also be set up in a consistent way across builds.

I think the other issue

```
failed: brew linkage --test folly
Stacktrace

        Missing libraries:
  /usr/local/opt/glog/lib/libglog.0.dylib
```
Is something I should report to github.com/facebook/folly.

**Comment by ahundt** [comment]
I created an equivalent folly issue:
https://github.com/facebook/folly/issues/648

**Comment by sergiud** [comment]
autconf build of glog does not version the library. Hence, the major version is zero which is obviously incorrect.

With regard to CMake build of glog. What are the issues exactly? Can you attach the build and install log for the CMake version of glog?

**Comment by ahundt** [comment]
> Edit: Why do you need both the autoconf and the CMake version of glog to package it?

The versions need to be consistent in a single release so other packages that use glog can find and link against it correctly regardless of the installer used.

In my case, once that is fixed I can switch homebrew from installing with autoconf to CMake. In particular, I'm looking for `glogConfig.cmake` to be generated.

**Comment by sergiud** [comment]
CMake already generates a package config for glog called `glog-config.cmake`.

**Comment by ahundt** [comment]
The issue is the library name, which needs to be consistent with different build systems.

**Comment by sergiud** [comment]
OK, please attach the log. Otherwise I'm not able to help you.

**Comment by ahundt** [comment]
my understanding is autoconf will create:
`/usr/local/opt/glog/lib/libglog.0.dylib`

and cmake will create:
`/usr/local/opt/glog/lib/libglog.3.dylib`

Is anything still unclear?

**Comment by sergiud** [comment]
Yes, please post the log. This is the fourth time I'm asking you to do so.

**Comment by ahundt** [comment]
https://gist.github.com/784479e5b60d4e8f36a002bd6f7df80f

**Comment by sergiud** [comment]
From the log:
```
-- Installing: /usr/local/lib/libglog.0.dylib
```

**Comment by ahundt** [comment]
As mentioned in the original post, the installers still created different dylibs/symlinks. autoconf did not create `/usr/local/lib/libglog.0.3.5.dylib`. I didn't really worry about the path I set since that's not the issue.

**Comment by sergiud** [comment]
> As mentioned in the original post, the installers still created different dylibs/symlinks. autoconf did not create `/usr/local/lib/libglog.0.3.5.dylib`.

You actually didn't. This is what you reported:

> The cmake version doesn't create this missing library/symlink: `/usr/local/opt/glog/lib/libglog.0.dylib`

Could please change the issue's title to something along the lines "autoconf build does not version the library"? Thanks!

**Comment by ahundt** [comment]
done, sorry about the mistake.

**Comment by sergiud** [comment]
@ahundt Thanks!

**Comment by ahundt** [comment]
Are there any next steps for this?

**Comment by sergiud** [comment]
Not until someone provides a patch. In the meantime you can use the CMake build.
