### ISSUE TITLE
Test stl_logging fails in macOS CMake build

### ISSUE THREAD

**Issue by jakirkham** [google/glog#201]
Running into a test failure on macOS 10.10 using AppleClang 6.1.0.6020053 with CMake when building glog 0.3.5. [1] When building with regular Make using the same macOS configuration, the same failure does not occur. [2] Neither CMake nor Make fail on Linux. Perhaps there is a bug in the CMake build w.r.t. macOS?

1: https://travis-ci.org/conda-forge/glog-feedstock/builds/246915696#L466
2: https://travis-ci.org/conda-forge/glog-feedstock/builds/246912247#L540

**Comment by emmenlau** [comment]
With glog 0.4.0 I still get this error in stl_logging:
```
test 5
    Start 5: stl_logging

5: Test command: /data/bdaci01/BioDataAnalysis/tmp-MacOSX-Core2-10.13-x86_64-clang9.1.0/Debug/glog-0.4.0-x86_64/stl_logging_unittest
5: Test timeout computed to be: 1500
5: Check failed: ss.str() == "10 20 30"
5/5 Test #5: stl_logging ......................***Failed    0.01 sec
```

**Comment by yiakwy** [comment]
@emmenlau Have you solved it? I hit the some problem when I am mitigrating my building codes  with upate of new cmake commands into a new mac book. And previously it worked very well.

**Comment by emmenlau** [comment]
Its still the same for me, tests fail.
