### ISSUE TITLE
Windows CMake 64-bit build fails logging test

### ISSUE THREAD

**Issue by jakirkham** [google/glog#202]
Trying to build a 64-bit Windows build with VS 2015 results in the `logging` test failing. [1] The same does not occur when building for 32-bit Windows with VS 2015. [2]

1: https://ci.appveyor.com/project/conda-forge/glog-feedstock/build/1.0.4/job/809v1f9cfsk5soy4#L592
2: https://ci.appveyor.com/project/conda-forge/glog-feedstock/build/1.0.4/job/jn1pcsnv49spte0y#L571

**Comment by andschwa** [comment]
Yeah, this is #134, and #93 attempts to fix it.
