### ISSUE TITLE
win32 vs2015 glog cannot log out to file

### ISSUE THREAD

**Issue by beichen2012** [google/glog#206]
platform: win10
env: vs2015 win32 debug console application
whatever `FLAGS_logtostderr` set to true or false,  the log file cannot be generated, and the console will always show log messages.

**Comment by xiaodongkirin** [comment]
platform: win7
env: vs2015 win32 debug console application

Use vs2015 compiler error

1.严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "bool __cdecl google::Symbolize(void *,char *,int)" (?Symbolize@google@@YA_NPAXPADH@Z)，该符号在函数 "void __cdecl google::DumpPCAndSymbol(void (__cdecl*)(char const *,void *),void *,void *,char const * const)" (?DumpPCAndSymbol@google@@YAXP6AXPBDPAX@Z11QBD@Z) 中被引用	libglog	D:\Tools\glog\glog\vsprojects\libglog\utilities.obj	1	
2.严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "bool __cdecl google::glog_internal_namespace_::IsFailureSignalHandlerInstalled(void)" (?IsFailureSignalHandlerInstalled@glog_internal_namespace_@google@@YA_NXZ)，该符号在函数 "void __cdecl google::DumpStackTraceAndExit(void)" (?DumpStackTraceAndExit@google@@YAXXZ) 中被引用	libglog	D:\Tools\glog\glog\vsprojects\libglog\utilities.obj	1	

3.严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1120	2 个无法解析的外部命令	libglog	D:\Tools\glog\glog\vsprojects\libglog\Debug\libglog.dll	1

**Comment by andschwa** [comment]
@beichen2012 I believe that `FLAGS_logtostderr` changes whether glog logs to `stdout` or `stderr`, which are streams generally output to your console. How exactly are you trying to use a log file?

**Comment by andschwa** [comment]
@xiaodongkirin your comment doesn't seem related to this issue.

**Comment by andschwa** [comment]
@beichen2012 hm, it [does seem](https://github.com/google/glog/blob/master/src/logging.cc#L106) that `GOOGLE_LOGTOSTDERR = false` should mean log files are used instead of `stderr`. Interesting...

**Comment by andschwa** [comment]
Do you see [this message at all](https://github.com/google/glog/blob/master/src/logging.cc#L1009)?

**Comment by beichen2012** [comment]
@andschwa 
Thank you, please refer to the below code snips:
```c++
GLogHelper::GLogHelper(const char* argv0, bool log2file, const char* log_dir )
{
    if(0 != _access(log_dir, 0))
    {
#ifdef _MSC_VER
        _mkdir(log_dir);
#else
        mkdir(log_dir);
#endif
    }
    FLAGS_log_dir = log_dir;
    google::InitGoogleLogging(argv0);
    FLAGS_logtostderr = (!log2file);
    google::SetStderrLogging(google::INFO);     
    FLAGS_colorlogtostderr=true;               
    FLAGS_logbufsecs = 0;        
    FLAGS_max_log_size =100;    
    FLAGS_stop_logging_if_full_disk = true;        
    google::InstallFailureSignalHandler();        
    google::InstallFailureWriter(&SignalHandle);   
}
```

**Comment by beichen2012** [comment]
@xiaodongkirin 
你用cmake编译一个静态库试试，直接用他的sln编译出来的dll感觉有问题。

**Comment by andschwa** [comment]
It's not reproing for me on Windows 10 with VS 2017. I ran:

```
> ./src/mesos-tests --log_dir=logs --gtest_filter="*Process*"
> ls logs


    Directory: C:\Users\andschwa\src\mesos\build\logs


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        8/14/2017   9:46 AM            305 mesos-tests.exe.ANDSCHWA1.andschwa.log.INFO.20170814-094641.12892
-a----        8/14/2017   9:46 AM            305 mesos-tests.exe.ANDSCHWA1.andschwa.log.INFO.20170814-094645.256
```

The logs are getting created by default, and it respected sending them to another directory.

We're using Glog [like this](https://github.com/apache/mesos/blob/master/src/logging/logging.cpp#L122).

**Comment by beichen2012** [comment]
@andschwa 
Thank you.
I built the glog lib with cmake and it works now.
so I would close the issue.
Thanks again.

**Comment by andschwa** [comment]
Awesome!

**Comment by wlbe4** [comment]
I had the same issue and found the root cause:
The vs project (libglog_static) was old and hence some functions were missing.
All you need to do is add the following files:
demangle.cc
signalhandler.cc
symbolize.cc
