### ISSUE TITLE
Failed to build glog with android ndk r11c using api 17 on 4.2.2

### ISSUE THREAD

**Issue by DevilGragon** [google/glog#207]
I have successfully built glog with r11c using api 21 on 5.1 but when i want to move glog to older android version using api 17 on 4.2.2, i met these following errors:

logging.cc:`` In member function 'virtual void google::{anonymous}::LogFileObject::Write(bool, time_t, const char*, int)':
./glog/src/logging.cc:1157:46: error: 'POSIX_FADV_DONTNEED' was not declared in this scope
         posix_fadvise(fileno(file_), 0, len, POSIX_FADV_DONTNEED);
                                              ^
./glog/src/logging.cc:1157:65: error: 'posix_fadvise' was not declared in this scope
         posix_fadvise(fileno(file_), 0, len, POSIX_FADV_DONTNEED);
                                                                 ^

and i have known that this POSIX_FADV_DONTNEED is defined at fcntl.h and logging.cc have already included it. 
Why it works with api 21 but doesn't work with api 17? Could anyone help me, thanks.

**Comment by sergiud** [comment]
Does it work if you add
```c++
#define _XOPEN_SOURCE 600
```
at the top of `logging.cc`?

**Comment by DevilGragon** [comment]
And I also find that in android ndk platforms android-17, the fcntl.h file only has the following declaration:

#ifndef _FCNTL_H
#define _FCNTL_H
#include <sys/cdefs.h>
#include <sys/types.h>
#include <linux/fcntl.h>
#include <unistd.h>  /* this is not required, but makes client code much happier */
__BEGIN_DECLS
#ifndef O_ASYNC
#define O_ASYNC  FASYNC
#endif
#ifndef O_CLOEXEC
#define O_CLOEXEC  02000000
#endif
extern int  open(const char*  path, int  mode, ...);
extern int  openat(int fd, const char*  path, int  mode, ...);
extern int  unlinkat(int dirfd, const char *pathname, int flags);
extern int  fcntl(int   fd, int   command, ...);
extern int  creat(const char*  path, mode_t  mode);
__END_DECLS
#endif /* _FCNTL_H `*/

But in android ndk platforms android-21, the fcntl.h file has the following declaration:

....
extern int posix_fadvise64(int, off64_t, off64_t, int);
extern int posix_fadvise(int, off_t, off_t, int);
extern int posix_fallocate64(int, off64_t, off64_t);
extern int posix_fallocate(int, off_t, off_t);
....
which cannot be find in 17's fcntl.h file.

Does this means that it can't be built on android 17?

**Comment by ChaoPei** [comment]
@DevilGragon Did you resolve this problem ?

**Comment by TomTasche** [comment]
Should be resolved with https://github.com/google/glog/pull/312
