### ISSUE TITLE
Can error log print the stacktrace?

### ISSUE THREAD

**Issue by jianghuiyou** [google/glog#210]
Now I have known fatal level log can print the stacktrace. Can error level log also have this function but without exiting the process

**Comment by ccdavid** [comment]
Any answer to this?

**Comment by david-y-lam** [comment]
The closest thing I know of is `FLAGS_log_backtrace_at`, which will print a backtrace for a given file:linenum: 

https://github.com/google/glog/blob/d72e3be82c832601e1d8f6fba580d2edf8be13da/src/logging.cc#L178-L179
