### ISSUE TITLE
Data race in raw_logging.cc?

### ISSUE THREAD

**Issue by adityamarella** [google/glog#212]
Helgrind shows a possible datarace with the following stack trace

```
==18== Possible data race during write of size 8 at 0xD01620 by thread #1
==18== Locks held: none
==18==    at 0x57AFC9: memcpy (string3.h:51)
==18==    by 0x57AFC9: google::RawLog__SetLastTime(tm const&, int) (raw_logging.cc:78)
==18==    by 0x572DC9: google::LogMessage::Init(char const*, int, int, void (google::LogMessage::*)()) (logging.cc:1217)
==18==    by 0x573491: google::LogMessage::LogMessage(char const*, int, int, int, void (google::LogMessage::*)()) (logging.cc:1142)
```
After going through the code, this indeed seems like a data race. What happens if multiple threads call `google::RawLog__SetLastTime` at the same time?

**Comment by adityamarella** [comment]
@shinh could you please comment on this. Thanks!

**Comment by shinh** [comment]
Indeed this is a race. It seems Google's internal version has removed datetime from raw log at all. If no one objects, I'd remove it from glog, too.

Same report: https://code.google.com/archive/p/google-glog/issues/62

**Comment by adityamarella** [comment]
Thanks for confirming that this is an issue. I have no objection to removing datetime from raw log, in fact I am patching my local copy to fix this.

**Comment by shinh** [comment]
I was reading the internal code wrongly. It seems the internal code still outputs timestamp at least on Linux. Hmm.
