### ISSUE TITLE
VS2008(win 10) build error

### ISSUE THREAD

**Issue by UnadXiao** [google/glog#214]
When i building the glog code gives the error：
```
1>..\..\src\logging.cc(1162) : error C2039: 'reset' : is not a member of 'google::LogMessage::LogStream'
1>d:\program files (x86)\glog-master\glog-master\src\symbolize.h(133) : error C2065: 'uint64_t' : undeclared identifier
1>d:\program files (x86)\glog-master\glog-master\src\symbolize.h(133) : error C2146: syntax error : missing ')' before identifier 'pc'
1>d:\program files (x86)\glog-master\glog-master\src\symbolize.h(133) : error C2513: 'int *' : no variable declared before '='
1>d:\program files (x86)\glog-master\glog-master\src\symbolize.h(137) : error C2059: syntax error : ')'
```

**Comment by andschwa** [comment]
VS2008 doesn't have `uint64_t` (or really any of `<stdint.h>`). Can you try a recent compiler?

[This implies](https://stackoverflow.com/questions/12970293/why-microsoft-visual-studio-cannot-find-stdint-h) that at least VS2012 and up will work.

**Comment by UnadXiao** [comment]
Thx
I tried the MSVC2015/2017 compiler, unfortunately, got the same error:
vs2015 target platform version 8.1 platform toolset visual studio 2015(v140)
vs2017 target platform version 10.0.15063.0 platform toolset visual studio 2017(v141)
Win10 Release x64
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2375	'snprintf': redefinition; different linkage	libglog	D:\Program Files (x86)\glog-master\glog-master\src\windows\port.h	115	
Error	C2039	'reset': is not a member of 'google::LogMessage::LogStream'	libglog	D:\Program Files (x86)\glog-master\glog-master\src\logging.cc	1162	
Error	C2375	'snprintf': redefinition; different linkage	libglog	D:\Program Files (x86)\glog-master\glog-master\src\windows\port.h	115	
Error	C2375	'snprintf': redefinition; different linkage	libglog	D:\Program Files (x86)\glog-master\glog-master\src\windows\port.h	115	
Error	C2375	'google::GetStackTrace': redefinition; different linkage	libglog	d:\program files (x86)\glog-master\glog-master\src\stacktrace_windows-inl.h	42	
Error	C2375	'snprintf': redefinition; different linkage	libglog	D:\Program Files (x86)\glog-master\glog-master\src\windows\port.h	115	
Error	C2375	'snprintf': redefinition; different linkage	libglog	d:\program files (x86)\glog-master\glog-master\src\windows\port.h	115	
```

**Comment by andschwa** [comment]
Those are very different errors!

How did you run CMake?

**Comment by andschwa** [comment]
If I had to take a guess, I think you might have used [google-glog.sln](https://github.com/google/glog/blob/master/google-glog.sln), which hasn't been touched in nine years and should probably be deleted.

**Comment by UnadXiao** [comment]
sorry. I mean VS2015 and 2017 get the same error message.
In vs2017 I did not use CMake(I don't know how to use), just use the IDE Build.
However, I used vs2008 in <glog: 0.3.4> compiled successfully.

**Comment by UnadXiao** [comment]
yes, I used **google-glog.sln** to open the project.
It seems that I need to learn to use CMake to compile glog, thank you.

**Comment by andschwa** [comment]
Should be pretty simple. Get it installed, and run `cmake .` Then open the solution it creates in Visual Studio and everything should be like you're used to.

CMake generates build systems, like a VS Solution.

**Comment by UnadXiao** [comment]
Got it, thank you very much !!!  : )

**Comment by xietao1233** [comment]
same problem in vs2013
