### ISSUE TITLE
Commit hash of latest release 0.3.5 (a6a166d) does not exist in master, causing git describe --tags to fail

### ISSUE THREAD

**Issue by jasjuang** [google/glog#220]
Step to reproduce:

``````
git clone https://github.com/google/glog
cd glog
git describe --tags
``````

shows 

``````
v0.3.4-133-gb3695ee
``````

while I am expecting 

``````
v0.3.5-41-gb3695ee
``````

I checked the commit history, and noticed that commit `a6a166d` does not exist in master branch and it's actually identical to commit `de66ae3`. How did this happen? Could someone please fix it? Thanks in advance.

**Comment by shinh** [comment]
See https://github.com/google/glog/issues/189 Sorry for the confusion.
