### ISSUE TITLE
DBUILD_SHARED_LIBS in Windows is broken for master

### ISSUE THREAD

**Issue by dashesy** [google/glog#227]
When I use this

    cmake .. -Dgflags_DIR=/c/devel/gflags/tmp/ -DBUILD_SHARED_LIBS=1

To build glog shared library on Windows I get this error when I try to build the solution:

```
1>c:\devel\glog\src\stacktrace_windows-inl.h(42): error C2375: 'google::GetStackTrace': redefinition; different linkage

```

That line is this:

```c++
    GOOGLE_GLOG_DLL_DECL
    int GetStackTrace(void** result, int max_depth, int skip_count) {

```

During build it must be export, during usage it must be import. I think `GOOGLE_GLOG_DLL_DECL` definition is not complete.

-----------------
This error is the current master. The release v0.3.5 compiles fine. Issue #103 is related.

**Comment by andschwa** [comment]
That's odd. I was fairly certain I'd tested this scenario (and hence added that `GOOGLE_GLOG_DLL_DECL` to fix it), must have messed it up though somehow.

**Comment by sergiud** [comment]
@andschwa The `GOOGLE_GLOG_DLL_DECL` for `GetStackTrace` had to be added in `stacktrace.h` instead of the windows implementation header. Also, `GOOGLE_GLOG_DLL_DECL` is missing in a few places.

I have a patch ready which I will submit soon.

**Comment by andschwa** [comment]
OH! Thank you @sergiud.

**Comment by sergiud** [comment]
@andschwa You're welcome. 

I've submitted #227.
