### ISSUE TITLE
VS2015 win32 compile glog error

### ISSUE THREAD

**Issue by xiaodongkirin** [google/glog#230]
How to use vs2015 compiler glog generated dll and lib files

**Comment by andschwa** [comment]
@xiaodongkirin why are you spamming other issues with your errors, but you open your own issue and don't include any details? I'd really like to help you, but please, perhaps you [could read this](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and then provide us with the information we need in order to help you.

And _please_, don't spam issues unrelated to your problem.

**Comment by xiaodongkirin** [comment]
I will  produce you with the information like this:
use platform vs2015 win32
win7 

use vs2015 complier error 

1.Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	2 unresolved externals	libglog	C:\Users\XiaoDong\Desktop\glog-master\glog\vsprojects\libglog\Debug\libglog.dll	1	

2.Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "bool __cdecl google::glog_internal_namespace_::IsFailureSignalHandlerInstalled(void)" (?IsFailureSignalHandlerInstalled@glog_internal_namespace_@google@@YA_NXZ) referenced in function "void __cdecl google::DumpStackTraceAndExit(void)" (?DumpStackTraceAndExit@google@@YAXXZ)	libglog	C:\Users\XiaoDong\Desktop\glog-master\glog\vsprojects\libglog\utilities.obj	1	

3.Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "bool __cdecl google::Symbolize(void *,char *,int)" (?Symbolize@google@@YA_NPAXPADH@Z) referenced in function "void __cdecl google::DumpPCAndSymbol(void (__cdecl*)(char const *,void *),void *,void *,char const * const)" (?DumpPCAndSymbol@google@@YAXP6AXPBDPAX@Z11QBD@Z)	libglog	C:\Users\XiaoDong\Desktop\glog-master\glog\vsprojects\libglog\utilities.obj	1

**Comment by andschwa** [comment]
Okay, but how did you build? What exact commands did you run?

**Comment by xiaodongkirin** [comment]
platform vs2015 Denug win32 
Right-click the project  libglog then Build

**Comment by andschwa** [comment]
There is no provided solution file. How did you run CMake to generate your
solution?

**Comment by xiaodongkirin** [comment]
Default setting Cmake ， only generate 
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>  Checking Build System
1>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: glog, Configuration: Debug Win32 ------
2>  Building Custom Rule C:/Users/XiaoDong/Desktop/glog-master/glog/CMakeLists.txt
2>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
2>  demangle.cc
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
2>  logging.cc
2>  raw_logging.cc
2>  symbolize.cc
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
2>  utilities.cc
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
2>C:\Program Files (x86)\Windows Kits\8.1\Include\um\DbgHelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
2>  vlog_is_on.cc
2>  signalhandler.cc
2>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility(2372): warning C4996: 'std::copy::_Unchecked_iterators::_Deprecate': Call to 'std::copy' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility(2372): note: see declaration of 'std::copy::_Unchecked_iterators::_Deprecate'
2>  C:\Users\XiaoDong\Desktop\glog-master\glog\src\signalhandler.cc(135): note: see reference to function template instantiation '_OutIt *std::copy<char*,char*>(_InIt,_InIt,_OutIt)' being compiled
2>          with
2>          [
2>              _OutIt=char *,
2>              _InIt=char *
2>          ]
2>  Generating Code...
2>  port.cc
2>  glog.vcxproj -> C:\Users\XiaoDong\Desktop\glog-master\cmake\Debug\glog.lib
3>------ Build started: Project: demangle_unittest, Configuration: Debug Win32 ------
4>------ Build started: Project: logging_unittest, Configuration: Debug Win32 ------
5>------ Build started: Project: signalhandler_unittest, Configuration: Debug Win32 ------
6>------ Build started: Project: stacktrace_unittest, Configuration: Debug Win32 ------
3>  Building Custom Rule C:/Users/XiaoDong/Desktop/glog-master/glog/CMakeLists.txt
3>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
3>  demangle_unittest.cc
4>  Building Custom Rule C:/Users/XiaoDong/Desktop/glog-master/glog/CMakeLists.txt
4>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
6>  Building Custom Rule C:/Users/XiaoDong/Desktop/glog-master/glog/CMakeLists.txt
6>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
4>  logging_unittest.cc
5>  Building Custom Rule C:/Users/XiaoDong/Desktop/glog-master/glog/CMakeLists.txt
6>  stacktrace_unittest.cc
5>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
5>  signalhandler_unittest.cc
3>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(579): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
3>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(586): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
4>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(579): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
4>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(586): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
3>  demangle_unittest.vcxproj -> C:\Users\XiaoDong\Desktop\glog-master\cmake\Debug\demangle_unittest.exe
7>------ Build started: Project: stl_logging_unittest, Configuration: Debug Win32 ------
6>  stacktrace_unittest.vcxproj -> C:\Users\XiaoDong\Desktop\glog-master\cmake\Debug\stacktrace_unittest.exe
8>------ Build started: Project: symbolize_unittest, Configuration: Debug Win32 ------
7>  Building Custom Rule C:/Users/XiaoDong/Desktop/glog-master/glog/CMakeLists.txt
7>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
8>  Building Custom Rule C:/Users/XiaoDong/Desktop/glog-master/glog/CMakeLists.txt
8>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
7>  stl_logging_unittest.cc
5>  signalhandler_unittest.vcxproj -> C:\Users\XiaoDong\Desktop\glog-master\cmake\Debug\signalhandler_unittest.exe
8>  symbolize_unittest.cc
9>------ Build started: Project: utilities_unittest, Configuration: Debug Win32 ------
9>  Building Custom Rule C:/Users/XiaoDong/Desktop/glog-master/glog/CMakeLists.txt
9>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
9>  utilities_unittest.cc
4>  logging_unittest.vcxproj -> C:\Users\XiaoDong\Desktop\glog-master\cmake\Debug\logging_unittest.exe
7>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(579): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
8>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(579): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
7>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(586): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
8>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(586): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
9>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(579): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
9>c:\users\xiaodong\desktop\glog-master\glog\src\googletest.h(586): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
8>  symbolize_unittest.vcxproj -> C:\Users\XiaoDong\Desktop\glog-master\cmake\Debug\symbolize_unittest.exe
7>  stl_logging_unittest.vcxproj -> C:\Users\XiaoDong\Desktop\glog-master\cmake\Debug\stl_logging_unittest.exe
9>  utilities_unittest.vcxproj -> C:\Users\XiaoDong\Desktop\glog-master\cmake\Debug\utilities_unittest.exe
10>------ Build started: Project: ALL_BUILD, Configuration: Debug Win32 ------
10>  Building Custom Rule C:/Users/XiaoDong/Desktop/glog-master/glog/CMakeLists.txt
10>  CMake does not need to re-run because C:/Users/XiaoDong/Desktop/glog-master/cmake/CMakeFiles/generate.stamp is up-to-date.
========== Build: 10 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by xiaodongkirin** [comment]
use vs2015 compiler generate result 

1>------ Build started: Project: INSTALL, Configuration: Debug Win32 ------
1>  -- Install configuration: "Debug"
1>  -- Installing: C:/Program Files (x86)/glog/lib/glog.lib
1>  -- Installing: C:/Program Files (x86)/glog/include/glog/config.h
1>  -- Installing: C:/Program Files (x86)/glog/include/glog/logging.h
1>  -- Installing: C:/Program Files (x86)/glog/include/glog/raw_logging.h
1>  -- Installing: C:/Program Files (x86)/glog/include/glog/stl_logging.h
1>  -- Installing: C:/Program Files (x86)/glog/include/glog/vlog_is_on.h
1>  -- Installing: C:/Program Files (x86)/glog/include/glog/log_severity.h
1>  -- Installing: C:/Program Files (x86)/glog/lib/cmake/glog/glog-config.cmake
1>  -- Installing: C:/Program Files (x86)/glog/lib/cmake/glog/glog-config-version.cmake
1>  -- Installing: C:/Program Files (x86)/glog/lib/cmake/glog/glog-targets.cmake
1>  -- Installing: C:/Program Files (x86)/glog/lib/cmake/glog/glog-targets-debug.cmake
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by xiaodongkirin** [comment]
I did not see glog.dll file

**Comment by andschwa** [comment]
Thank you. Have you tried linking against glog.lib? The default settings will produce a static library only, no glog.dll. What errors do you get when using glog.lib, and do the unit tests build and pass?

**Comment by xiaodongkirin** [comment]
run application use glog.lib like this
1.Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	4 unresolved externals	testDemo	D:\projects\testDemo\Debug\testDemo.exe	1	

2.Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QAEAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function _main	testDemo	D:\projects\testDemo\testDemo\Source.obj	1	

3.Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __thiscall google::LogMessage::LogMessage(char const *,int)" (__imp_??0LogMessage@google@@QAE@PBDH@Z) referenced in function _main	testDemo	D:\projects\testDemo\testDemo\Source.obj	1	

4.Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __thiscall google::LogMessage::~LogMessage(void)" (__imp_??1LogMessage@google@@QAE@XZ) referenced in function _main	testDemo	D:\projects\testDemo\testDemo\Source.obj	1	

5.Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl google::InitGoogleLogging(char const *)" (__imp_?InitGoogleLogging@google@@YAXPBD@Z) referenced in function _main	testDemo	D:\projects\testDemo\testDemo\Source.obj	1

**Comment by xiaodongkirin** [comment]
please how to configure cmake thank you

**Comment by andschwa** [comment]
May I see how you're trying to link to glog, that is, your build setup for `testDemo`?

If you want shared libraries out of CMake, you run `cmake . -DBUILD_SHARED_LIBS=ON`, then you'll have the `glog.dll` shared library and the import library `glog.lib`.

**Comment by andschwa** [comment]
Take a look [here](https://github.com/google/glog/blob/master/cmake/INSTALL.md) for how to link to glog correctly automatically.
