### ISSUE TITLE
Macro Redefinition and Header Conflicts Causes Issue Installing

### ISSUE THREAD

**Issue by atkawa7** [google/glog#236]
I am using [vcpkg](https://github.com/Microsoft/vcpkg) on windows whenever I try to install `glog`

```
vcpkg install glog
``` 
I get macro redefinition  errors. The issue is caused by two google projects `ctemplate` and `glog` which use same macros for different purposes.  See this line. 

https://github.com/OlafvdSpek/ctemplate/blob/master/src/windows/config.h#L19

```cpp
#define GOOGLE_NAMESPACE  ctemplate
```

and  on this https://github.com/google/glog/blob/master/src/windows/config.h#L4

```cpp
#define GOOGLE_NAMESPACE  google
```

see issue microsoft/vcpkg#1514 and OlafvdSpek/ctemplate#127

**Comment by OlafvdSpek** [comment]
Is glog/config.h supposed to be a public header?

**Comment by atkawa7** [comment]
@OlafvdSpek I am going to open this for them to answer your question
