### ISSUE TITLE
when a very long log message is printed by LOG(INFO), it will be truncated.

### ISSUE THREAD

**Issue by lcy-seso** [google/glog#240]
I am a member of the PaddlePaddle project.  I run into a problem when using glog and hope to get some help.

- PaddlePaddle is a deep learning framework. In PaddlePaddle `PrintLayer.cpp` uses  [`LOG(INFO)`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/PrintLayer.cpp#L51) to print a layer's output matrix and sequence information (if the output is a sequence).
- Float values in a layer's output matrix are [first formatted into an `ostringstream`]( https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/PrintLayer.cpp#L33). Because a layer's output may contain many float numbers (batch size × layer's size,  for example, 128 × 128), as a result, the formatted string is always very long.
- I found when using LOG(INFO) to print such a long formatted string, the string is truncated. (I change `LOG(INFO)` into `std::cout` the string can be printed correctly)
- It seems that the `LOG(INFO)` macro has a buffer to cache the logging information, and its size is not large enough in my cases.
- I searched and tried `GLOG FLAGS` defined in glog, but still, do not success to explicitly change the buffer size of LOG(INFO), or using LOG(INFO) to print the entire information.

I am not sure what is the reason to this problem? 
I also hope to know is there some way to explicitly change buffer size of LOG(INFO), or I have to split such a long string into several parts and then use LOG(INFO).

Thanks very much for your help.

I also create this issue in PaddlePaddle project https://github.com/PaddlePaddle/Paddle/issues/3809

**Comment by lcy-seso** [comment]
I searched the codes and found this line: https://github.com/google/glog/blob/a835da8e088273066c32c3cb0e8ff69d54071217/src/logging.cc#L330

Is my problem caused by this limitation?

**Comment by Justso2012** [comment]
I have the same problem.
I use the glog in my program to print the picture content.As  the picture is large,most of the logs were truncated,so I can't get the complete content.Now I change the num of kMaxLogMessageLen  in logging.cc  to 200000  and recomplie,and the new library works, but some picture content is still oversized.
Is there any method to solve the problem?
