### ISSUE TITLE
Compiling error: undefined references

### ISSUE THREAD

**Issue by Guozht** [google/glog#241]
guozht@guozht-Lenovo-G400:~/WorkStation/TestEvpp/src$ g++ -static -o test test.c -L ../lib -lglog
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Mutex()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:245：对‘pthread_rwlock_init’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::~Mutex()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:247：对‘pthread_rwlock_destroy’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::ReaderLock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:255：对‘pthread_rwlock_rdlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::ReaderLock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:255：对‘pthread_rwlock_rdlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:255：对‘pthread_rwlock_rdlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::~Mutex()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:247：对‘pthread_rwlock_destroy’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘__static_initialization_and_destruction_0’中：
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:102：对‘google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:104：对‘google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:106：对‘google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:109：对‘google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:125：对‘google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:130：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:133：对‘google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:135：对‘google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:137：对‘google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:141：对‘google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:143：对‘google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:147：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:164：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:167：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:170：对‘google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:174：对‘google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/logging.cc:177：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Mutex()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:245：对‘pthread_rwlock_init’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-logging.o)：在函数‘glog_internal_namespace_::Mutex::ReaderLock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:255：对‘pthread_rwlock_rdlock’未定义的引用
../lib/libglog.a(libglog_la-vlog_is_on.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-vlog_is_on.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-vlog_is_on.o)：在函数‘glog_internal_namespace_::Mutex::Lock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:248：对‘pthread_rwlock_wrlock’未定义的引用
../lib/libglog.a(libglog_la-vlog_is_on.o)：在函数‘glog_internal_namespace_::Mutex::Unlock()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:249：对‘pthread_rwlock_unlock’未定义的引用
../lib/libglog.a(libglog_la-vlog_is_on.o)：在函数‘__static_initialization_and_destruction_0’中：
/home/guozht/WorkStation/glog-0.3.4/src/vlog_is_on.cc:52：对‘google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)’未定义的引用
/home/guozht/WorkStation/glog-0.3.4/src/vlog_is_on.cc:55：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
../lib/libglog.a(libglog_la-vlog_is_on.o)：在函数‘glog_internal_namespace_::Mutex::Mutex()’中：
/home/guozht/WorkStation/glog-0.3.4/src/base/mutex.h:245：对‘pthread_rwlock_init’未定义的引用
../lib/libglog.a(libglog_la-utilities.o)：在函数‘google::glog_internal_namespace_::is_default_thread()’中：
/home/guozht/WorkStation/glog-0.3.4/src/utilities.cc:180：对‘pthread_self’未定义的引用
../lib/libglog.a(libglog_la-utilities.o)：在函数‘google::glog_internal_namespace_::InitGoogleLoggingUtilities(char const*)’中：
/home/guozht/WorkStation/glog-0.3.4/src/utilities.cc:327：对‘pthread_self’未定义的引用
../lib/libglog.a(libglog_la-utilities.o)：在函数‘__static_initialization_and_destruction_0’中：
/home/guozht/WorkStation/glog-0.3.4/src/utilities.cc:69：对‘google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)’未定义的引用
collect2: 错误：ld 返回 1

**Comment by Guozht** [comment]
Compile command:g++ -static -o test test.c -L ../lib -lglog

**Comment by sergiud** [comment]
Your compile command is incorrect. You're not linking against pthreads, gflags and other glog dependencies which is exactly your compiler complains about.

**Comment by Guozht** [comment]
@sergiud 
Doesn't it just need a static library（libglog.a）?
Can you tell me what libraries glog relies on?

**Comment by sergiud** [comment]
@Guozht No, static libraries do not embed their dependencies. You need to link against these dependencies explicitly. The three libraries I mentioned previously are the libraries you must link against.

**Comment by Guozht** [comment]
@sergiud Thank you very much. I succeeded in solving the problem

**Comment by sergiud** [comment]
@Guozht Great!

**Comment by Guozht** [comment]
@sergiud

**Comment by ibroheem** [comment]
> Your compile command is incorrect. You're not linking against pthreads, gflags and other glog dependencies which is exactly what your compiler complains about.

Maybe you list that in the Wiki too, I think it's a common problem too

**Comment by sergiud** [comment]
If this is a common problem, you can go ahead and start adding information on required dependencies to the wiki yourself. No need to wait until someone else does it for you.
