### ISSUE TITLE
CMake Windows 10 - RUN_TESTS All Fail

### ISSUE THREAD

**Issue by mathjones** [google/glog#248]
Navigate to

`
drive:\path\to\glog\bin
`

run

`
cmake ..\
`

to build the build files

Options: attached in
[CMakeCache.txt](https://github.com/google/glog/files/1345321/CMakeCache.txt)

I build by opening glog.sln in Visual Studio 2017, and building _ALL_BUILD_
I install by building _INSTALL_
When I run tests by building _RUN_TESTS_, all tests fail ... despite build and install steps complete without any errors or warnings. Is there something I'm missing? I've tried building shared libraries, and the issue remains.

**Comment by sergiud** [comment]
I guess glog cannot find the gflags DLL. Run `ctest --verbose` in your build directory and please attach the log.
