### ISSUE TITLE
./autogen.sh: line 5: autoreconf: command not found

### ISSUE THREAD

**Issue by pharekoppa** [google/glog#250]
I cloned the repository and tried to follow the installation steps:
./autogen.sh && ./configure && make && make install

I get this error:
./autogen.sh: line 5: autoreconf: command not found

Any idea what is missing?

**Comment by andschwa** [comment]
You should install the Autotools package(s) for your platform. (The package is `autoconf` on Ubuntu.)

**Comment by majiqiang** [comment]
我应该怎么安装autoconf呢？

**Comment by ASONG0506** [comment]
> 我应该怎么安装autoconf呢？

sudo apt-get install autoconf

**Comment by majiqiang** [comment]
> > 我应该怎么安装autoconf呢？
> 
> sudo apt-get install autoconf
thanks for your reply! I try to operate it in ROS, but when I catkin_make the package (handeye_calib_camodocal) this error appears:
`CMake Error at handeye_calib_camodocal/CMakeLists.txt:30 (find_package):
By not providing "FindGlog.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Glog", but
CMake did not find one.
Could not find a package configuration file provided by "Glog" with any of
the following names:
GlogConfig.cmake
glog-config.cmake`
I do something by approaches in the installation section of the readme and i also install these dependencies,such as glog,gflags and so on,how should I do?
