### ISSUE TITLE
Windows CMAKE 3.9.1/VS2017 build issue

### ISSUE THREAD

**Issue by hokiedsp** [google/glog#252]
Hi,

I'm trying to build glog from the source that I just checked out from the repo. After what appears to be a successful configure & generate steps, I'm encountering compiler errors when I run "cmake --build ." with the following message:

"[...]\glog\build\ALL_BUILD.vcxproj" (default target) (1) ->
"[...]\glog\build\logging_unittest.vcxproj" (default target) (5) ->
(ClCompile target) ->
  [...]\glog\src\logging_unittest.cc(276): error C2039: 'ERROR': is not a member of 'google' [C:\Users\tikuma\glog\build\logging_unittest.vcxproj]
  [...]\glog\src\logging_unittest.cc(276): error C2065: 'ERROR': undeclared identifier [C:\Users\tikuma\glog\build\logging_unittest.vcxproj]

Looking at the source file (logging_unittest.cc), the problem line is:

    google::LogMessage outer(__FILE__, __LINE__, google::ERROR);

Am I missing a dependency here? I have built & installed gflags just prior to this build.

Thanks, Kesh

**Comment by andschwa** [comment]
Ah, I have an idea. There's this issue where the standard Windows headers (e.g. `<windows.h>`) _also_ define `ERROR`. So the macro [`GLOG_NO_ABBREVIATED_SEVERITIES`](https://github.com/google/glog/blob/0472b91c5defdf90cff7292e3bf7bd86770a9a0a/doc/glog.html#L548) was added to help deal with this problem. Unfortunately, it kind of becomes configuration dependent, and that macro is [defined by default](https://github.com/google/glog/blob/d0531421fd5437ae3e5249106c6fc4247996e526/CMakeLists.txt#L440) on Windows.

So if you're somehow not already defining `ERROR` (but not including any Windows headers, or maybe using `WIN32_LEAN_AND_MEAN` correctly), you'll end up with neither Windows nor Glog defining `ERROR`, which I think is what's happening here.

**Comment by hokiedsp** [comment]
Andrew, thanks for a quick response. I saw the page discussing GLOG_NO_ABBREVIATED_SEVERITIES, but I figured it's about using the library and not compiling it. I did search for "google::ERROR" in the glog sources, but I couldn't pin point who is defining it by a casual observation.

Are there any additional info or files from my build I can send your way for you to get better idea of what's going on?

**Comment by shinh** [comment]
This was due to a very recent change. @hokiedsp: Could you check if the issue was fixed?

https://github.com/google/glog/pull/226/files#diff-05d0d0546f7ffa50e1da7ce80e0400b8R276

**Comment by hokiedsp** [comment]
@shinh - Without the latest patch and reverting Line 275-280 to 

"LOG(ERROR) << (&LOG(ERROR) && 0) << " nested LOG";"

the compilation succeeds. Am I correct to assume that this issue does not affect the glog DLL and I can move on to the dependent project?

**Comment by sergiud** [comment]
@shinh Missed that one. The fix works well, thanks!
@hokiedsp That's correct.

**Comment by ypengf** [comment]
@shinh solves the problem, thanks!
