### ISSUE TITLE
glog cost too much time in tmpfs

### ISSUE THREAD

**Issue by journey-wang** [google/glog#258]
/run is tmpfs

`#include <glog/logging.h>
#include <iostream>
#include <chrono>
#include <ctime>

using namespace std;

int main(int /*argc*/, char** argv)
{
    FLAGS_logbuflevel = -1;
    google::SetLogDestination(google::GLOG_INFO,"/run/" );
    google::InitGoogleLogging(argv[0]);

    auto i = 0;
    while(1) {
       i++;
        auto start = std::chrono::steady_clock::now();
        LOG(INFO) << "This is INFO " << i ;
        auto end = std::chrono::steady_clock::now();
        auto diff = end - start;
        std::cout << chrono::duration <double, milli> (diff).count() << " ms" << std::endl;
        if (i > 100000) {
           break;
        }
    }

    return 0;
}`

1.  diff value increases each time.
2. much bigger than c++ fstream.

**Comment by journey-wang** [comment]
fstream output:
0.001066 ms
0.001029 ms
0.000845 ms
0.000789 ms
0.001142 ms
0.000821 ms
0.001033 ms
0.00088 ms
0.000907 ms
0.000892 ms
0.00102 ms
0.001065 ms
0.000867 ms
0.000952 ms
0.00354 ms
0.000941 ms
0.000947 ms
0.000859 ms
0.000835 ms
0.000785 ms

glog output:
0.222152 ms
0.222159 ms
0.235292 ms
0.22608 ms
0.222618 ms
0.222228 ms
0.234361 ms
0.225806 ms
0.222544 ms
0.222273 ms
0.234233 ms
0.228794 ms
0.222817 ms
0.222504 ms
0.222498 ms
0.241291 ms
0.228223 ms
0.222612 ms
0.222242 ms
0.234675 ms
0.226064 ms
0.222333 ms
0.222397 ms
0.233245 ms
0.228247 ms
0.222702 ms
0.222263 ms
0.222374 ms
0.234915 ms
0.22568 ms
0.222506 ms
0.222194 ms
0.235929 ms
0.226583 ms
0.222462 ms
0.222198 ms
0.235051 ms
0.228957 ms
0.222552 ms
0.222465 ms
0.222369 ms
0.23572 ms
0.225912 ms
0.222345 ms
0.222174 ms
0.233733 ms
0.225668 ms
0.222294 ms
0.222251 ms
0.239553 ms
0.235103 ms
0.222768 ms
0.222181 ms
0.222307 ms
0.238804 ms
0.226886 ms
0.222657 ms
0.222701 ms
0.24064 ms
0.228964 ms
0.223048 ms
0.222748 ms
0.235263 ms
0.229475 ms
0.223048 ms
0.222713 ms
0.222713 ms
0.236152 ms
0.226738 ms
0.222632 ms
0.222502 ms
0.235267 ms
0.226641 ms
0.223003 ms
0.222643 ms
0.238734 ms
0.227726 ms
0.222889 ms
0.222493 ms
0.222706 ms
0.236567 ms
0.226525 ms
0.222821 ms
0.222452 ms
0.237261 ms
0.226835 ms
0.223039 ms
0.222828 ms
0.236446 ms
0.229436 ms
0.22306 ms
0.222636 ms
0.222662 ms
0.238341 ms
0.226919 ms
0.222798 ms
0.222493 ms
0.234375 ms
0.225937 ms
0.222713 ms
0.222631 ms
0.236412 ms
0.229679 ms
0.2231 ms
0.222937 ms
0.222591 ms
0.236757 ms
0.226344 ms
0.222856 ms

**Comment by sergiud** [comment]
How did you compile your test program?

**Comment by sergiud** [comment]
Closing as no feedback.
