### ISSUE TITLE
Conan package for glog

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [google/glog#262]
Hello,
Do you know about Conan package manager? Can you add Conan package for the library and maintain it? Here you can find example of my conan recipe for libpng: https://github.com/ZaMaZaN4iK/conan-libpng

**Comment by sergiud** [comment]
Never heard of it. You're welcome to propose a patch though.

**Comment by DariuszOstolski** [comment]
Hi,

I've go a recipe for glog conan package, just take a look at my repositories.

Best Regards,
Darek

**Comment by DariuszOstolski** [comment]
Here is a link to conan recipe repository: https://github.com/DariuszOstolski/conan_glog

Tested on linux only, but should work on all platforms

**Comment by ZaMaZaN4iK** [comment]
Do you want to support Conan package? I can move your package to Bincrafters repo and Bincrafters team will support package for your library. Also you of course can do it manually :-)

**Comment by DariuszOstolski** [comment]
I've just joined bincrafters team, so soon it should be published officially under bincrafters flag.

**Comment by ZaMaZaN4iK** [comment]
https://cpplang.now.sh/
