### ISSUE TITLE
FlagRegisterer::FlagRegisterer<int>

### ISSUE THREAD

**Issue by jianhuaixie** [google/glog#265]
/googletest.h:100: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
collect2: error: ld returned 1 exit status
Makefile:1114: recipe for target 'logging_unittest' failed
make: *** [logging_unittest] Error 1

**Comment by sergiud** [comment]
Have you checked the [Wiki](../wiki/Installing-Glog-on-Ubuntu-14.04)?
