### ISSUE TITLE
build error with VS2015

### ISSUE THREAD

**Issue by mxgbs** [google/glog#267]
Use cmake to generate the .sln (I installed the gflags first and linked to the cmake)
and then build the glog with VS2015, x64, debug/release. Following errors occur. Can someone help me with this? Thank you.
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'ERROR': is not a member of 'google'	logging_unittest	
Documents\glog\glog-master\src\logging_unittest.cc	276	
Error	C2065	'ERROR': undeclared identifier	logging_unittest	
Documents\glog\glog-master\src\logging_unittest.cc	276

**Comment by graugans** [comment]
```
Google glog defines a severity level ERROR, which is also defined in windows.h . You can make glog not define INFO, WARNING, ERROR, and FATAL by defining GLOG_NO_ABBREVIATED_SEVERITIES before including glog/logging.h``` Take a look at [this article](http://rpg.ifi.uzh.ch/docs/glog.html). 

When using the provided [glog's cmake config module](https://github.com/google/glog/blob/master/cmake/INSTALL.md) this should already set by magic cmake hocus pocus.
