### ISSUE TITLE
 ‘GFLAGS_NAMESPACE’ is not a namespace-name

### ISSUE THREAD

**Issue by luxuan** [google/glog#273]
When I build with: ./autogen.sh && ./configure && make
Build system: CentOS Linux release 7.3.1611 (Core) 
those error happend:
src/logging_unittest.cc:64:17: error: ‘GFLAGS_NAMESPACE’ is not a namespace-name
 using namespace GFLAGS_NAMESPACE;
                 ^
src/logging_unittest.cc:64:33: error: expected namespace-name before ‘;’ token
 using namespace GFLAGS_NAMESPACE;
                                 ^
src/logging_unittest.cc: In function ‘int main(int, char**)’:
src/logging_unittest.cc:180:43: error: ‘ParseCommandLineFlags’ was not declared in this scope
   ParseCommandLineFlags(&argc, &argv, true);

**Comment by Crista23** [comment]
I am encountering the same error. Did you find a solution?

**Comment by luxuan** [comment]
I have turned to this install doc and fixed: https://github.com/gflags/gflags/blob/master/INSTALL.md
and build with:
$ mkdir build && cd build
$ ccmake ..
  - Continue pressing 'c' until the option 'g' is available.
  - Then press 'g' to generate the configuration files for GNU Make.
$ make

**Comment by luxuan** [comment]
I changed the build system: CentOS Linux release 7.4.1708 (Core) 
and no more those error,  I didn't find what the difference between them

**Comment by krips89** [comment]
Update? 
I got the problem too. 
Why is this closed? what is the solution?
