### ISSUE TITLE
Improve using glog as cmake subproject

### ISSUE THREAD

**Issue by maksbotan** [google/glog#274]
Some glog users like to include it in sources and use `add_subdirectory`. However, that results in a problem: `install()` commands are processed and may interfere with other things.

Here's a concrete scenario:

- `gflags` is included with `add_subdirectory`, therefore `gflags` target is defined (as `ALIAS` in fact)
- `glog` is included the same way, with `WITH_GFLAGS=OFF`, but `gflags_FOUND=ON`. This way `find_package(gflags)` does not run (which would fail), but `gflags` support is activated and `target_link_libraries(glog gflags)` runs successfully, because the target is defined

However, when `glog` calls `install(TARGETS glog EXPORTS glog-targets...)`, cmake wants `gflags` target installed in the same export set and, of course, fails.

I propose to use the same workaround used in `gflags` project: add cmake option `GLOG_IS_SUBPROJECT` and, if it's defined, do not call any `install()` commands. This way consuming project will be able to link to `gflags` static library without any problems.

See:

https://github.com/gflags/gflags/blob/master/CMakeLists.txt#L12
https://github.com/gflags/gflags/blob/master/CMakeLists.txt#L162

**Comment by sergiud** [comment]
What's wrong with `CMAKE_SKIP_INSTALL_RULES` or using `ExternalProject`? In general, I'm against adding dirty hacks/workarounds which are useful only to a handful of people while making the maintenance of CMake support more difficult.

**Comment by maksbotan** [comment]
Sorry, did not know about `CMAKE_SKIP_INSTALL_RULES`. It works indeed.
