### ISSUE TITLE
EXC_BAD_ACCESS on iOS

### ISSUE THREAD

**Issue by MayPau** [google/glog#275]
After updating glog from version 0.3.3 to 0.3.5 it crashes on iOS with `Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)` at [line 1218 in logging.cc](https://github.com/google/glog/blob/a6a166db069520dbbd653c97c2e5b12e08a8bb26/src/logging.cc#L1216)

This is the code triggering the crash:
google::InitGoogleLogging("Test SDK");
DLOG(INFO) << "Test logging";

The same code works fine on Android.

Same problem with version 0.3.4

**Comment by sergiud** [comment]
Does it work if you disable TLS? This can be done using the command-line as follows:

```bash
$ cmake <glog-build-dir> -DWITH_TLS=OFF
```

Afterwards you need to compile glog again.

**Comment by Lightolx** [comment]
how to build glog in ios?
