### ISSUE TITLE
Is glog support ANDROID?

### ISSUE THREAD

**Issue by sbilgi** [google/glog#280]
Hello all,

when try compile glog for android, i get  error: "use of undeclared identifier 'posix_advice' ";
is glog support android? if it,  how can i compile glog for android?
(Compile env= Windows 10, NDK 16b, mingw make).

**Comment by daquexian** [comment]
Yes, it supports Android.
I haven't met this error. But do not use NDK 16, or will get `undefined reference to stderr` like [this](https://github.com/openssl/openssl/issues/3826)
