### ISSUE TITLE
VLOG before InitGoogleLogging causes crash

### ISSUE THREAD

**Issue by oliverdain** [google/glog#290]
I have some static initializers that call VLOG. On Linux (but not on OSX) these cause a segfault because they happen before InitGoogleLogging is called. If I change the `VLOG(1)` bits to `LOG(INFO)` I get the expected `WARNING: Logging before InitGoogleLogging() is written to STDERR` message and I see the logs, but everything works fine.

Looking at things in a debugger it appears that the first call to `VLOG` causes a call to `InitVLOG3__` which then calls `VLOG2Initializer` which tries to access a bunch of uninitialized variables (e.g. `vmodule`) and that causes a segfault.

**Comment by zxtwonder** [comment]
In my case, not all binaries generating logs before InitGoogleLogging() crash, but when it does crash, both LOG and VLOG cause crash.
