### ISSUE TITLE
can't link glog when compiling the project in vs 2013

### ISSUE THREAD

**Issue by seayfhzl001** [google/glog#293]
hello guys,
I try to import the glog to my project in visual studio 2013,every thinking is working, but finally i got the following errors when i was compiling the project:
Error	16	error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl google::InitGoogleLogging(char const *)" (__imp_?InitGoogleLogging@google@@YAXPBD@Z) referenced in function _main	C:\workspace\TargetRecovery\TargetRecovery\Main.obj	TargetRecovery
Error	17	error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl google::ShutdownGoogleLogging(void)" (__imp_?ShutdownGoogleLogging@google@@YAXXZ) referenced in function _main	C:\workspace\TargetRecovery\TargetRecovery\Main.obj	TargetRecovery

I already included the lib in my program like this:#pragma comment(lib,"libs/glogd.lib")

Would you like to give me some suggestions ?
Thank u a lot!!

**Comment by sergiud** [comment]
It seems you do not use CMake (or bazel) to incorporate glog into your project. You therefore need to replicate all compile options and flags used by glog (which are also visible externally), and apply them to your project.
