### ISSUE TITLE
cmake 3.10.2 error

### ISSUE THREAD

**Issue by sayyoume** [google/glog#296]
Make Warning at CMakeLists.txt:55 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" (requested
  version 2.2.0) with any of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.

how to solve?

**Comment by sergiud** [comment]
The message is pretty clear. Compile and install gflags.

**Comment by MariaFischer** [comment]
yea except that doesn't work I installed libgflags-dev ["sudo apt-get install libgflags-dev"], and I still get the same message as op

**Comment by ugnelis** [comment]
I get same error. It would be nice to have GLOG standalone without installing GFLAGS. Cheers!

**Comment by sergiud** [comment]
Make sure to read the CMake error messages carefully. You need at least version of 2.2.0 of gflags. The version of gflags that comes packaged with Ubuntu 15.10 is way too old. As a workaround, you can compile gflags from source.

**Comment by ugnelis** [comment]
I just set `WITH_GFLAGS` off and it seems it's compiling

**Comment by WorldLanguageZq** [comment]
sudo apt-get install libgflags-dev

**Comment by BrytonLee** [comment]
How to make it without have to install gflags on the system?  

My project depends on both gflags and glog, and I use CMake add_subdirectory() to include these two libraries. However, cmake step still throw out this warning.  It seems that gflags is not visible to glog under the CMake progress.

**Comment by StartAt24** [comment]
> How to make it without have to install gflags on the system?
> 
> My project depends on both gflags and glog, and I use CMake add_subdirectory() to include these two libraries. However, cmake step still throw out this warning. It seems that gflags is not visible to glog under the CMake progress.

I'v found a way to do this.
1. git clone glfags and glog.
2. go to the gflags and glog dirs.  
3. mkdir build && cd build && cmake .. && make
4. in your project add the following codes to CMakelists.txt
```
set(gflags_DIR /path/to/gflags/build)
find_package( gflags  REQUIRED PATHS ${CMAKE_SOURCE_DIR}/third_party/gflags NO_DEFAULT_PATH)

set(glog_DIR /path/to/glog/build)
find_package( glog  REQUIRED PATHS ${CMAKE_SOURCE_DIR}/third_party/glog NO_DEFAULT_PATH)
```
than the usage may like bellow:
```
add_executable(sample sample.cpp )
target_link_libraries(sample glog::glog)
```
