### ISSUE TITLE
Static linking fails on Visual Studio 2017

### ISSUE THREAD

**Issue by martingalvan** [google/glog#301]
Hi all, I'm using Visual Studio 2017 15.6.2 on Windows 7 (x86_64) to build an application that's statically linked to glog. I built and installed glog itself through the Visual Studio solution generated by CMake (that is, I built the `ALL_BUILD` and `INSTALL` projects on the generated solution). On my own project, I added the path to glog.lib to my project's `Linker->Input->Additional Dependencies` list, and the path to glog's include folder to `C/C++->Additional Include Directories`. However, when I try to build my solution, I get several link errors such as:

`LNK2001	unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > & fLS::FLAGS_log_dir" (__imp_?FLAGS_log_dir@fLS@@3AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@EA)`

I saw that someone else was having this same problem, but his project was based on CMake whereas mine just uses Visual Studio solutions. Am I doing something wrong?

EDIT: I just noticed that the linker errors seem to go away if I `#define GOOGLE_GLOG_DLL_DECL` before including glog/logging.h. Is this behavior normal? If so, where is it documented?

**Comment by martingalvan** [comment]
I just noticed that the linker errors seem to go away if I `#define GOOGLE_GLOG_DLL_DECL` before including glog/logging.h. Is this behavior normal? If so, where is it documented?

**Comment by sergiud** [comment]
See #293, #241 for related problems. It is your responsibility to replicate the defines and other compiler options if you do not use CMake or bazel.

**Comment by martingalvan** [comment]
@sergiud Ok, what are these defines? Where is this all documented?

**Comment by sergiud** [comment]
No, they are not. You must grep the generated `glog-targets.cmake` to determine which compile definitions must be applied to your build.

**Comment by martingalvan** [comment]
Ok, so where is *that* step documented?

I'm asking because these seem like pretty serious usability issues, and it's not very nice for users to have to scour through Github issues for clues on how to use the library. I haven't seen any documentation mentioning that you must use CMake when linking on Windows either, though perhaps I didn't check in the right place.

**Comment by sergiud** [comment]
That step is now documented in my answer to your question. You can edit the Wiki If you need a more accessible document for such details.

**Comment by martingalvan** [comment]
Github issues aren't documentation, nor it's the user's responsibility to document your code.

In any case, looks like I won't be using glog due to some of its other limitations. Thanks anyway.

**Comment by sergiud** [comment]
Product? This is a user-contributed open-source project for which you have not paid a dime. You are welcome to improve the documentation if this is a showstopper for you.

**Comment by zhylmzr** [comment]
As a reference (Win32 static build), I need to define the macro `GLOG_NO_ABBREVIATED_SEVERITIES; GOOGLE_GLOG_DLL_DECL=` in `Properties -> C/C++ -> Preprocessor -> Preprocessor Definitions`.
It is also very important to ensure that the compilation target of glog is consistent with the main project target.
