### ISSUE TITLE
glog can't be compiled using Android NDK r16

### ISSUE THREAD

**Issue by daquexian** [google/glog#306]
When glog is built by Android NDK r15 or r14, there will be an error `undefined reference to 'stderr'`(like [this issue](https://github.com/google/glog/issues/247)) when glog is built as static library and linked to other programs. Please refer to [this document](https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeaders.md). As shown in above document, this error can be avoided by adding a specific flag. But in Android NDK r16 there is no such flag. So glog can't be built by NDK r16.

Are there any ways to solve it?

**Comment by daquexian** [comment]
Adding -DANDROID_PLATFORM="android-21" solves it.

**Comment by knsong** [comment]
@daquexian Do you know why there is no glog output in logcat of android studio when debugging native code?

**Comment by daquexian** [comment]
@knsong glog print logs to stdout or a log file instead of android logcat. For android logcat support you can try https://github.com/tzutalin/miniglog

**Comment by knsong** [comment]
@daquexian thanks!

**Comment by designerMichael** [comment]
[Adding -DANDROID_PLATFORM="android-21" solves it.]
I also meet this problem, but it work by Adding
-DANDROID_PLATFORM="android-23" to solve the undefined "stderr" problem.
