### ISSUE TITLE
__declspec(dllimport) public: __thiscall google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)

### ISSUE THREAD

**Issue by LingjieLi** [google/glog#316]
I include the .h directory,and the .lib library in QtCreator,but appear this bug.Can you put forward some suggestion about this problem.I appreciate it.

**Comment by NeroBurner** [comment]
is this still an issue?

if yes, please try with the latest commit from master, and please provide more information about your build setup (Compiler used, Operating System, ...)
