### ISSUE TITLE
glog detected wrong gflags namespace.

### ISSUE THREAD

**Issue by loop0day** [google/glog#317]
- Build System
  - Ubuntu 18.04
  - gcc 7.3.0
  - cmake 3.10.2
  - gflags 2.2.1
  - glog ~~0.3.5~~ 2faa186
- I compile gflags with `cmake -DBUILD_SHARED_LIBS=ON -DGFLAGS_NAMESPACE=google -DCMAKE_INSTALL_PREFIX=/opt/gflags -DCMAKE_CXX_FLAGS=-fPIC ..` and `sudo make -j2 && sudo make install`
- I write a gflags demo file, and it works.
```c++
#include <iostream>
#include <gflags/gflags.h>

int main(int argc, char *argv[])
{
  google::ParseCommandLineFlags(&argc, &argv, true);

  return EXIT_SUCCESS;
}

```
- compile it with `g++ -Wall -Wextra -Werror -std=c++11 -Wl,-rpath=/opt/gflags/lib/ -o proc main.cc -L /opt/gflags/lib -lgflags`, and it works fine.
- However glog detected wrong gflags namespace when I compile it from source. I run `cmake -DCMAKE_INSTALL_RPATH=/opt/gflags/lib -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/opt/glog -DCMAKE_BUILD_TYPE=RELEASE -DWITH_GFLAGS=ON -DCMAKE_CXX_FLAGS=-fPIC ..`, but it show that 
> -- Looking for gflags namespace
> -- Looking for gflags namespace - gflags
- Then I run `cmake -L ..`, it shows **gflags_DIR** is detected correctly.
> gflags_DIR:PATH=/opt/gflags/lib/cmake/gflags
- Then i write a glog demo
```c++
#include <iostream>
#include <glog/logging.h>

int main(int , char *argv[])
{
  google::InitGoogleLogging(argv[0]);

  LOG(INFO) << "Hello Glog!";

  return EXIT_SUCCESS;
}
```
- compile it with `g++ -Wall -Wextra -Werror -std=c++11 -Wl,-rpath=/opt/glog/lib -o proc main.cc -L /opt/glog/lib -lglog`
- `./proc --logtostderr=1` doesn't work. It doesn't print message to stderr.
- `GLOG_logtostderr=1 ./proc` works fine surely.
- Thanks.

**Comment by loop0day** [comment]
```bash
git diff DetermineGflagsNamespace.cmake
-        CMAKE_FLAGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
+        CMAKE_FLAGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} "-DINCLUDE_DIRECTORIES:STRING=${gflags_INCLUDE_DIR}"
```
- I recompile it with `cmake -Dgflags_INCLUDE_DIR:STRING=/opt/gflag/include -DCMAKE_INSTALL_RPATH=/opt/gflags/lib -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/opt/glog -DCMAKE_BUILD_TYPE=RELEASE -DWITH_GFLAGS=ON -DCMAKE_CXX_FLAGS=-fPIC ..`, but it still shows that.
> -- Looking for gflags namespace
> -- Looking for gflags namespace - gflags
- So the prog program still doesn't work with `--logtostderr=1`.

**Comment by sergiud** [comment]
Which commit did you use?

**Comment by loop0day** [comment]
My issue looks like #286.

**Comment by sergiud** [comment]
> Please try the **latest** commit and report back.

**Comment by loop0day** [comment]
I am sorry my English is not very good. Did you mean the lastest commit (#316) or the lastest commit (#209)of issue #193 you mentioned before.

**Comment by sergiud** [comment]
The latest commit (2faa186 at the time of writing)  is the head of the master branch which you get after a fresh clone of the glog repository. Is that what you use?

**Comment by sergiud** [comment]
I'm totally confused now. You mention two separate issues: incorrect gflags namespace detection (the title) and non-working ``--logtostderr=1``. How are they related?

**Comment by loop0day** [comment]
At first, glog detected wrong gflags namespace(gflags instead of google), I changed the order of _NAMESPACE from (gflags to google), it could get correct namespace (google), but when I set —logtostderr=1, my program is still not working.

**Comment by loop0day** [comment]
It could detect correct gflags namespace google after I changed the order of _NAMESPACES from (gflags google) to (google gflags) in cmake/DetermineGflagsNamespace.cmake. But why DGFLAGS_IS_A_DLL was not true while I was using libgflags.so compiled by myself? Even more why gflags namespace could try compile passed in my machine (I don't have another libgflags)? I'm thinking it is the wrong detection that causes the command line not work.
```bash
CMakeFiles/CMakeOutput.log:643:/usr/bin/c++  -DGFLAGS_IS_A_DLL=0 -DGFLAGS_NAMESPACE=google -isystem /opt/gflags/include  -fPIC  -O3 -DNDEBUG   -o CMakeFiles/cmTC_bf483.dir/DetermineGflagsNamespace.cxx.o -c /home/fish/Workspace/Repos/glog/build/CMakeFiles/CMakeTmp/DetermineGflagsNamespace.cxx
```
Much appreciated for your patience.

**Comment by loop0day** [comment]
@sergiud I succeeded in logging to stderr by add `google::ParseCommandLineFlags(&argc, &argv, true);` before `google::InitGoogleLogging(argv[0]);`. Perhaps you could add it in the wiki.
By the way, I found a small bug in the  `try_compile` of `cmake/DetermineGflagsNamespace.cmake`. It tried to compile `_check_file` by defining `GFLAGS_NAMESPACE` to each item in `_NAMESPACES`, but `GFLAGS_NAMESPACE` was hard coded in the `gflags_declare.h`, so try_compile always return true no matter which namespace was selected.
