### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by whjxnyzh** [google/glog#32]
```src/logging_unittest.cc' || echo './'`src/logging_unittest.cc
src/logging_unittest.cc: In function ‘int main(int, char*_)’:
src/logging_unittest.cc:179: error: ‘ParseCommandLineFlags’ was not declared in this scope
src/logging_unittest.cc: In static member function ‘static void Test_DeathNoAllocNewHook_logging::Run()’:
src/logging_unittest.cc:296: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:296: error: expected ‘;’ before ‘fs’
src/logging_unittest.cc: In function ‘void TestRawLogging()’:
src/logging_unittest.cc:308: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:308: error: expected ‘;’ before ‘saver’
src/logging_unittest.cc: In function ‘void LogWithLevels(int, int, bool, bool)’:
src/logging_unittest.cc:363: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:363: error: expected ‘;’ before ‘saver’
src/logging_unittest.cc: In static member function ‘static void Test_DeathRawCHECK_logging::Run()’:
src/logging_unittest.cc:436: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:436: error: expected ‘;’ before ‘fs’
src/logging_unittest.cc: In static member function ‘static void Test_DeathSTREQ_logging::Run()’:
src/logging_unittest.cc:586: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:586: error: expected ‘;’ before ‘fs’
src/logging_unittest.cc: In static member function ‘static void Test_CheckNOTNULL_Simple::Run()’:
src/logging_unittest.cc:596: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:596: error: expected ‘;’ before ‘fs’
src/logging_unittest.cc: In static member function ‘static void Test_DeathCheckNN_Simple::Run()’:
src/logging_unittest.cc:607: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:607: error: expected ‘;’ before ‘fs’
src/logging_unittest.cc: In static member function ‘static void Test_SafeFNMatch_logging::Run()’:
src/logging_unittest.cc:866: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:866: error: expected ‘;’ before ‘fs’
src/logging_unittest.cc: In static member function ‘static void Test_Strerror_logging::Run()’:
src/logging_unittest.cc:1041: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:1041: error: expected ‘;’ before ‘fs’
src/logging_unittest.cc: In static member function ‘static void Test_UserDefinedClass_logging::Run()’:
src/logging_unittest.cc:1207: error: ‘FlagSaver’ was not declared in this scope
src/logging_unittest.cc:1207: error: expected ‘;’ before ‘fs’
make: *_\* [src/logging_unittest-logging_unittest.o] Error 1

```
```

**Comment by ukai** [comment]
which platform? how configured?

**Comment by gelidus** [comment]
This happens to me on Fedora23, this is my configuration log:
http://pastebin.com/7gDtdYvK

**Comment by kyu-sz** [comment]
This is probably because the current GLOG depends on a GFLAGS version higher than default provided in your system.

I got this fixed on my CentOS system by cleaning everything, compiling and installing the latest GFLAGS cloned from Github, and build GLOG again.

**Comment by sergiud** [comment]
The issue doesn't seem to be active anymore.
