### ISSUE TITLE
Static declaration of 'pread' follows non-static declaration error while building in xcode

### ISSUE THREAD

**Issue by RameshkrishnanV** [google/glog#326]
Hi,

    I'm working on ios app n i m using glog 0.3.4 in that app, when i build that app in xcode i'm getting error like 
"Static declaration of 'pread' follows non-static declaration"
using xcode 9.

Please help me on this,
Thank you

**Comment by NeroBurner** [comment]
please try with glog 0.3.5, and if that does not work with current master
