### ISSUE TITLE
When might 0.3.6 be released?

### ISSUE THREAD

**Issue by andschwa** [google/glog#345]
Not to rush anyone, but I'd like to move on from downloading 0.3.5 and applying patches. A 0.3.6 release would be awesome 😄

**Comment by xmnlab** [comment]
that would be very awesome! any idea about the 0.3.6 release? :)

**Comment by sergiud** [comment]
@shinh @ukai Would someone of you guys would be willing to manage the release?

**Comment by vielmetti** [comment]
For reference, this is coming in part from https://issues.apache.org/jira/browse/MESOS-3394 which has been open since 2015.

**Comment by andschwa** [comment]
@vielmetti It's been THREE years?! That went fast...
