### ISSUE TITLE
Compilation Error; pointer/integer comparison.

### ISSUE THREAD

**Issue by Jordan-Effinger** [google/glog#359]
Trying to compile with make aborts with the two following errors:

src/demangle.cc: In function 'bool google::AtLeastNumCharsRemaining(const char*, int)':
src/demangle.cc:170:16: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     if (str == '\0') {

src/demangle.cc: In function 'bool google::ParseCharClass(google::State*, const char*)':
src/demangle.cc:226:29: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   if (state->mangled_cur == '\0') {

**Comment by NeroBurner** [comment]
fixed in https://github.com/google/glog/commit/a5ffa884137f7687d0393ccba22557d583654a25#diff-81af9f0eab9a04e1d26013a0af666c73

you seem to be using a very old release. In the future please add the used version of glog for reference
