### ISSUE TITLE
Add support for deleting old logs

### ISSUE THREAD

**Issue by isaoa** [google/glog#36]
Hi,
Can we add a support for deleting old logs?
As of now, log just keeps accumulating until it takes entire disk space.
If we set the max log size to 10MB, glog keeps generating 10MB log files never deleting.
I'd like to keep only latest 4 logs (of 10MB or smaller).

I know there are tools which can be run to do the cleanup such as logrotate.
We make Windows DLL which runs on embedded machine made by another company.  We don't have control on this embedded machine, so we cannot run any program to rotate the log.

I've added RotateLogFile function which checks for number of log files and deletes old logs.
RotateLogFile is run in LogFileObject::Write as it log is rolled over and new log file is created (when max_log_size is reached).

so if we have following 4 logs,

log_20150617-141944.8600
 log_20150618-166949.8600
 log_20150619-119953.8600
 log_20150620-107957.8600

And if a new one is created, the oldest one is deleted leaving 4 logs
 log_20150617-141944.8600 <-Deleted
 log_20150618-163949.8600
 log_20150619-112953.8600
 log_20150620-101957.8600
 log_20150621-103957.8600  <-- Created

Has this feature been considered before?  Can you add this?

Thanks,

Isao

**Comment by bitkevin** [comment]
I have the same problem, can't use linux `logrotate` to delete old log files.

**Comment by ezegomez** [comment]
See also https://github.com/google/glog/pull/19 for a possible solution that enables logrotate support (I still need to update it to the latest master though)

**Comment by isaoa** [comment]
Hi ezegomez,
Thanks for the suggestions.

I'm not sure the suggested change would solve my problem.
If I understand correctly, your change would append to existing log after restart.
We need to keep ability to limit the total size of the log, let's say to 10MB.

1. start program.  it sets max_log_size to 10MB.
2. program writes to myapp.log.
3. program restarts
4. program appends to myapp.log
what would happen once it reaches the size limit of 10MB?

would it keep writing past 10MB or delete myapp.log and recreates the same file?

Either way, it won't work for us, as we want to limit the amount of logs and at the same time don't want to lose all logs when log rotates.

**Comment by sudhi-vm** [comment]
+1 for this feature.

**Comment by hanzeil** [comment]
+1 for this feature.

**Comment by njpillitteri** [comment]
+1 for this feature

**Comment by WangAndrew2016** [comment]
+1 for this feature

**Comment by asierguti** [comment]
+1 for this feature

**Comment by hyperwang** [comment]
+1 for this feature

**Comment by hyperwang** [comment]
+1 for this feature, otherwise I need to write scripts to rotate these files.

**Comment by yyh-graphsql** [comment]
+1 for this feature.

**Comment by rockuw** [comment]
+1

**Comment by chanfr** [comment]
+1

**Comment by elithnever** [comment]
+1

**Comment by saifhhasan** [comment]
Any updates on this feature ?

**Comment by CaptD** [comment]
+1

**Comment by grahamkenville** [comment]
+1

**Comment by bartsimpson89** [comment]
+1 for this feature

**Comment by ruanchen** [comment]
+1 for this feature

**Comment by kubeway** [comment]
+1 for this feature

**Comment by bitkevin** [comment]
+1 for this feature

**Comment by sergiud** [comment]
Locking the issue due to spam.
