### ISSUE TITLE
static google::log_mutex destroyed on exit, while other still existing threads want to log

### ISSUE THREAD

**Issue by lazarvlad** [google/glog#363]
Hello, I've got an issue that causes my program using glog to crash uppon exit. For example if I start a separate thread in which I LOG stuff, when exiting the program, the destructor for the Mutex google::log_mutex is called (from the main thread) before a Mutex::Lock() (caused by the LOG function on the child thread) triggering pthread_rwlock_wrlock to return an error code 22 (EINVAL). Is there a way to set glog framework to be deleted last (or another way to fix this)?

**Comment by wangguibao** [comment]
I'm having the same issue
