### ISSUE TITLE
Memory leak detected with valgrind memcheck

### ISSUE THREAD

**Issue by junoon53** [google/glog#37]
got this output running valgrind memcheck:

228 ==9178== 22 bytes in 1 blocks are possibly lost in loss record 69 of 174        
229 ==9178==    at 0x402A6BC: operator new(unsigned int) (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
230 ==9178==    by 0x43A6FD5: std::string::_Rep::_S_create(unsigned int, unsigned int, std::allocator<char> const&) (in /usr/lib/i386-linux-gnu/libstdc++.so.6.0.20)
231 ==9178==    by 0x4245E45: char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) (in /usr/lib/i386-linux-gnu/libboost_regex.so.1.55.0)
232 ==9178==    by 0x43A95D7: std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (in /usr/lib/i386-linux-gnu/libstdc++.so.6.0.20)
233 ==9178==    by 0x40672D3: dont_pass0toDEFINE_string (gflags.h:533)              
234 ==9178==    by 0x40672D3: __static_initialization_and_destruction_0 (logging.cc:147)
235 ==9178==    by 0x40672D3: _GLOBAL__sub_I_logging.cc (logging.cc:2079)           
236 ==9178==    by 0x400ED26: call_init.part.0 (dl-init.c:78)                       
237 ==9178==    by 0x400EE13: call_init (dl-init.c:36)                              
238 ==9178==    by 0x400EE13: _dl_init (dl-init.c:126)                              
239 ==9178==    by 0x400104E: ??? (in /lib/i386-linux-gnu/ld-2.19.so)

**Comment by ukai** [comment]
maybe, it's gflags leak?
