### ISSUE TITLE
debug build fails with "reference binding to misaligned address for type 'struct basic_ostream', which requires 8 byte alignment"

### ISSUE THREAD

**Issue by romange** [google/glog#373]
when building with gcc sanitizer "-fsanitize=undefined" i get the error above. The reason for that is when GLOG_THREAD_LOCAL_STORAGE is defined, LogMessageData is allocated using placement new in unaligned address.

**Comment by sergiud** [comment]
Fixed in 6adf6d7ae554911a9175bc6a27ad7d3f0b320fea.
