### ISSUE TITLE
CMake support question

### ISSUE THREAD

**Issue by xsun2001** [google/glog#381]
Recently I want to include glog library in my project, which use CMake as its build system. I want to use it as a submodule of my project so the glog repo was put in a directory called ThirdParty/glog. I also want to use gflags. So I put it into ThirdParty/gflags. At first, I add the following code to my CMakeLists.txt:

```
add_subdirectory(ThirdParty/gflags)
add_subdirectory(ThirdParty/glog)

add_executable(MyProject ${SRC_LIST})
target_link_libraries(MyProject gflags::gflags glog::glog)
```

But CMake cannot find gflags. I don't know whether glog can use gflags. 
I also use the code like that:
```
set(gflags_DIR ${CMAKE_CURRENT_BINARY_DIR}/ThirdParty/gflags)
set(glog_DIR ${CMAKE_CURRENT_BINARY_DIR}/ThirdParty/glog)

add_subdirectory(ThirdParty/gflags)
add_subdirectory(ThirdParty/glog)

find_package(gflags REQUIRED)
find_package(glog REQUIRED)

add_executable(MyProject ${SRC_LIST})
target_link_libraries(MyProject gflags::gflags glog::glog)
```
But it turns out to have some more strange error:
```
CMake Error at cmake-build-debug/ThirdParty/gflags/gflags-config.cmake:17 (include):
  The file

    /Users/xsun2001/Documents/projects/LLTC/LBFL/cmake-build-debug/ThirdParty/gflags/gflags-nonamespace-targets.cmake

  was generated by the export() command.  It may not be used as the argument
  to the include() command.  Use ALIAS targets instead to refer to targets by
  alternative names.
```

Sorry for my poor English, but I really need you help to config it properly.

**Comment by NeroBurner** [comment]
are you using  a recent version? since https://github.com/google/glog/commit/cbfd86a1d8f92dc38c6c1bae689c84ebeb4da558 the alias is part of the cmake project. Please try with the current master

**Comment by sergiud** [comment]
Looks like a gflags issue.
