### ISSUE TITLE
Make the documentation browsable online

### ISSUE THREAD

**Issue by ldionne** [google/glog#39]
It would be super easy to setup a gh-pages branch with the documentation on it.

**Comment by david-y-lam** [comment]
I would like it too. 👍

**Comment by egon010** [comment]
+1

**Comment by nodakai** [comment]
Meanwhile... http://rpg.ifi.uzh.ch/docs/glog.html

**Comment by pmateusz** [comment]
@shinh, a repo administrator has privileges to enable GitHub pages. Could you assign the issue to the relevant person? Documentation is already in the doc folder, so everything else seems to be in place already.

**Comment by RasmusFonseca** [comment]
Yes please! @sergiud maybe
