### ISSUE TITLE
header file problems

### ISSUE THREAD

**Issue by lsdy** [google/glog#390]
The following code is included in the two header files "logging.h" and "raw_logging.h".
`namespace google{
#include "glog/log_severity.h"
#include "glog/vlog_is_on.h"
...
}`
Why not change it to
#include "glog/log_severity.h"
#include "glog/vlog_is_on.h"`
namespace google{
...
}`
Then add namespace in "log_severity.h" and "vlog_is_on.h".
Because when I code in eclipse,it always tips problems like "Function 'InitVLOG3__' could not be resolved".

**Comment by sergiud** [comment]
I cannot figure out what are you asking. Please rephrase your question.
