### ISSUE TITLE
Win32 VS2017 build error with dynamic glog lib

### ISSUE THREAD

**Issue by VeblenXSYK** [google/glog#396]
when I use ’FLAGS_logbufsecs‘  in my project，build error output as below：
’ unresolved external symbol "int fLI::FLAGS_logbufsecs" (?FLAGS_logbufsecs@fLI@@3HA)‘
I should how to solve the problem？Thank you in advance for your feedback！！！

**Comment by sergiud** [comment]
Looks like a gflags problem. Please provide a minimal example that allows to reproduce the issue.

**Comment by VeblenXSYK** [comment]
use example as below:
`LogModule(const char *name, const char *logfilepath, int logsecs = 0)
	{
		google::InitGoogleLogging(name);

		google::SetLogDestination(google::GLOG_INFO, logfilepath);

		FLAGS_logbufsecs = logsecs;

		//FLAGS_max_log_size = 5;

		//FLAGS_stop_logging_if_full_disk = true;

		google::InstallFailureSignalHandler();

		google::InstallFailureWriter(&SignalHandle);
	}`

build output error as allows:
`unresolved external symbol "int fLI::FLAGS_logbufsecs`

What needs to be explained is that I not have build glog lib with gflags，as below：
![image](https://user-images.githubusercontent.com/9734740/49000908-f9502380-f195-11e8-9268-7589cdfdabd9.png)

because when I build glog lib with gflags, I get build error as below:
`glog-master\src\logging.cc(106): error C2370: “fLB::FLAGS_logtostderr”: Redefining; different storage classes
glog-master\mybuild\glog\logging.h(334): note: reference “fLB::FLAGS_logtostderr” declaration
glog-master\src\logging.cc(108): error C2370: “fLB::FLAGS_alsologtostderr”: Redefining; different storage classes
glog-master\mybuild\glog\logging.h(337): note: reference “fLB::FLAGS_alsologtostderr” declaration
glog-master\src\logging.cc(110): error C2370: “fLB::FLAGS_colorlogtostderr”: Redefining; different storage classes
glog-master\mybuild\glog\logging.h(340): note: reference “fLB::FLAGS_colorlogtostderr” declaration`

**Comment by VeblenXSYK** [comment]
use the latest release google-glog 0.3.5，not have the problem

**Comment by sergiud** [comment]
Which gflags version did you use?

**Comment by VeblenXSYK** [comment]
![image](https://user-images.githubusercontent.com/9734740/49067976-7942c000-f260-11e8-9fa4-73045b5bef91.png)

**Comment by VeblenXSYK** [comment]
I know， but when build the latest release google-glog 0.3.5. I don't have use gflags and build success.

**Comment by Yukimura-2K** [comment]
Up to now, Is there a further progress in this problem. I was getting troubles with it in the span of days.
