### ISSUE TITLE
@majiqiang It looks like Arch uses ``configure`` [to build](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/google-glog#n18) the package thus the cmake stuff is not generated. So you can add a comment or vote on their issue tracker to the already opened issue about this.

### ISSUE THREAD

**Issue by majiqiang** [google/glog#398]
[FS#55185 - [google-glog] use cmake to build to generate cmake import configs](https://bugs.archlinux.org/task/55185?project=5&string=google-glog) maybe adding a link to this issue might shed some lights.

_Originally posted by @graugans in https://github.com/google/glog/issues/4#issuecomment-442001197_

**Comment by graugans** [comment]
@majiqiang this is an issue in ARCH not in glog

**Comment by majiqiang** [comment]
> @majiqiang this is an issue in ARCH not in glog

oh! sorry, but i really want to know the problem about cmake error:
`CMake Error at handeye_calib_camodocal/CMakeLists.txt:30 (find_package):
  By not providing "FindGlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Glog", but
  CMake did not find one.

  Could not find a package configuration file provided by "Glog" with any of
  the following names:

    GlogConfig.cmake
    glog-config.cmake

  Add the installation prefix of "Glog" to CMAKE_PREFIX_PATH or set
  "Glog_DIR" to a directory containing one of the above files.  If "Glog"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/mjq/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/mjq/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed`

**Comment by graugans** [comment]
The error is related to the fact that the file ``GlogConfig.cmake`` is only generated and installed if you build glog with CMake. The Arch maintainers have decided to build glog with the buildsystem based on autotools (configure). This sort of buildsystem does not generate the config files required by catkin and CMake. So you can build glog with cmake after removing the package from Arch. This will install the GlogConfig.cmake. But this maybe breaks dependencies with other packages in Arch.

**Comment by sergiud** [comment]
Please discuss the issue on Arch Linux bug tracker.

**Comment by majiqiang** [comment]
> Please discuss the issue on Arch Linux bug tracker.

thank  you! I have solved it!

**Comment by 850977164** [comment]
@graugans I'm sure glog is already installed, however, cmake is still making errors. After reading your description, I decided to try it
