### ISSUE TITLE
demangle_unittest.sh fails with GCC 5 (configured --with-default-libstdcxx-abi=new, which is the default)

### ISSUE THREAD

**Issue by doko42** [google/glog#40]
./src/demangle_unittest.sh
Mangled symbols (21 out of 796) found in demangle.dm:
_ZN3fLS13FLAGS_log_dirB5cxx11E
_ZN3fLS13FLAGS_vmoduleB5cxx11E
_ZN3fLS14FLAGS_log_linkB5cxx11E
_ZN3fLS15FLAGS_logmailerB5cxx11E
_ZN3fLS20FLAGS_alsologtoemailB5cxx11E
_ZN3fLS22FLAGS_log_backtrace_atB5cxx11E
_ZN3fLS25dont_pass0toDEFINE_stringB5cxx11EPcPKc
_ZN6google12Check_GEImplB5cxx11EiiPKc
_ZN6google12Check_LTImplB5cxx11EiiPKc
_ZN6google14LogDestination10addresses_B5cxx11E
_ZN6google14LogDestination8hostnameB5cxx11Ev
_ZN6google14LogDestination9hostname_B5cxx11E
_ZN6google19CheckstrcmptrueImplB5cxx11EPKcS1_S1_
_ZN6google20CheckstrcmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google21GetLoggingDirectoriesB5cxx11Ev
_ZN6google23CheckstrcasecmptrueImplB5cxx11EPKcS1_S1_
_ZN6google24CheckstrcasecmpfalseImplB5cxx11EPKcS1_S1_
_ZN6google24glog_internal_namespace_10MyUserNameB5cxx11Ev
_ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev
_ZN6google7LogSink8ToStringB5cxx11EiPKciPK2tmS2_m
_ZN6google8StrErrorB5cxx11Ei
Mangled symbols (21 out of 796) found in demangle.dm
Makefile:2060: recipe for target 'demangle_unittest_sh' failed
make[3]: **\* [demangle_unittest_sh] Error 1
make[3]: Leaving directory '/scratch/packages/tmp/google-glog-0.3.4'
Makefile:1906: recipe for target 'check-am' failed
make[2]: **\* [check-am] Error 2

**Comment by theopolis** [comment]
Seems related to #14, and like the set of GCC versions there 5.0 has a different set of C++ symbols that fail the unmangling.
