### ISSUE TITLE
README.md has not been changed for all

### ISSUE THREAD

**Issue by Wangyz2017** [google/glog#407]
build will fail

**Comment by jackwish** [comment]
@Wangyz2017  you can try my branch :)

**Comment by walterzhaoJR** [comment]
me too.
./configure
configure: error: cannot find sources (README) in . or ..

**Comment by jackwish** [comment]
@walterzhaoJR PR #408 will fix this issue. You guys can try [my branch](https://github.com/jackwish/glog/tree/fix/build/readme) before it's merged.

**Comment by walterzhaoJR** [comment]
@jackwish ok,let me have a try.THX

**Comment by sergiud** [comment]
Fixed by #408 .
