### ISSUE TITLE
visual studio 2015 error 

### ISSUE THREAD

**Issue by ml232528** [google/glog#41]
error C2084: 函数“int snprintf(char *const ,const size_t,const char *const ,...)”已有主体
error C2280: “std::basic_ios<char,std::char_traits<char>>::basic_ios(const std::basic_ios<char,std::char_traits<char>> &)”: 尝试引用已删除的函数

**Comment by ml232528** [comment]
modify logging.h
class GOOGLE_GLOG_DLL_DECL LogStream : public std::ostream {
...
  public:
	  LogStream(const LogStream &) = delete;
	  void operator=(const LogStream &) = delete; 
 };

modify port.cc
#if !(defined(_MSC_VER) && (_MSC_VER >= 1900))
int snprintf(char *str, size_t size, const char *format, ...) {
  va_list ap;
  va_start(ap, format);
  const int r = vsnprintf(str, size, format, ap);
  va_end(ap);
  return r;
}
#endif

**Comment by ukai** [comment]
which is better?  #43 and #30 
do we need both?

**Comment by sergiud** [comment]
Neither. 856ff81a8268a5c22d026a65d4c12a2e1136f73f and f9def39a465725c1b2a60f64200fba5d1614da36 already fixed VS2015 issues.

**Comment by ukai** [comment]
ok. fixed by #7
