### ISSUE TITLE
Glog should delete old log files automaticly

### ISSUE THREAD

**Issue by DinoStray** [google/glog#423]
For example, I wanna keep log files for only 7 days.
Then the  glog should delete all the log files which last modify time before 7 days.

**Comment by aesophor** [comment]
I think a cron job can do it

This deletes the logs produced by glog under /tmp that are last modified 7 days ago.
```
$ find /tmp -name 'YourProjectName.*' -mtime +7 -delete
```

Then `$ crontab -e` and add this line to run it daily at 00:00 AM
```
0 0 * * * find /tmp -name 'YourProjectName.*' -mtime +7 -delete
```

**Comment by DinoStray** [comment]
> I think a cron job can do it
> 
> This deletes the logs produced by glog under /tmp that are last modified 7 days ago.
> 
> ```
> $ find /tmp -name 'YourProjectName.*' -mtime +7 -delete
> ```
> Then `$ crontab -e` and add this line to run it daily at 00:00 AM
> 
> ```
> 0 0 * * * find /tmp -name 'YourProjectName.*' -mtime +7 -delete
> ```

But If I use docker or  k8s, there is no crontab.
Clean old logs should done by the glog itself

**Comment by aesophor** [comment]
@DinoStray I've written the code to automatically remove old logs, but they are not yet integrated into the original codebase.
@sergiud I'm not sure when to call it. Calling it at the end of LogFileObject::FlushUnlocked() seems really unwise, since that scans for old logs too frequently. Could you please help me with this? Thank you!

**Comment by letrthong** [comment]
Raspberry doesn't have real time clock so can not get timestamp. Please check the case

**Comment by letrthong** [comment]
i wrote code to limit maximum size of all  files about  3M which is running on raspberry pi.

**Comment by aesophor** [comment]
@DinoStray I tried to implement this and it works on my linux box! :smile: (gentoo-4.19.66) But I haven't tested it on Windows, I'll do it once I have spare time.

---

Simply add this to your project to enable **log cleaner**, it is disabled by default. Once enabled, it will automatically remove old logs that are last modified over 3 days. Only the logs produced by the project which glog is linked in will be removed, logs from other projects won't be touched.
```
google::EnableLogCleaner(3);
```

You can also disable it at anytime by calling
```
google::DisableLogCleaner();
```

Please see here for technical details.
https://github.com/google/glog/pull/432#issuecomment-523680414

**Comment by aesophor** [comment]
> I read your code but Raspberry doesn't have real time clock so can not get correct timestamp. Please check the case

So there's no way get the timestamp for a file on Raspberry pi? I'll try to see if I there are other ways.

**Comment by aesophor** [comment]
@DinoStray I think you could close this now
