### ISSUE TITLE
How do I write logs to files only?

### ISSUE THREAD

**Issue by findingBalance** [google/glog#436]
I want to write logs to files only.I set the FLAGS_logtostderr=false,but I still found that it wrote both the file and the  terminal.

How do I slove this?

Anyway, thanks first.

**Comment by serhatgiydiren** [comment]
Hi.
This flag is used to log messages to stderr instead of log files. Maybe another flag is needed for this case.
@sergiud If this issue is seen as an enhancement, i am ready to send a PR.
Thanks. Regards.
