### ISSUE TITLE
libglog_la-utilities Error on cygwin

### ISSUE THREAD

**Issue by chenruichou** [google/glog#44]
src/utilities.cc:268:29: error: 'GetCurrentThreadId' was not declared in this scope
   return GetCurrentThreadId();
                             ^
src/utilities.cc:273:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:1191: recipe for target 'src/libglog_la-utilities.lo' failed
make: **\* [src/libglog_la-utilities.lo] Error 1

I am installing glog on cygwin configuration. Not sure what went wrong. Could anyone give a clue/solution?

Thanks,

**Comment by rhlbhrgv-art** [comment]
utilities.cc:267 checks for OS_CYGWIN being defined. If so, it attempts to call GetCurrentThreadId() which is not found.
Similarly, googletest.h:524 and :557 performs the same test.

All three tests are unnecessary on cygwin, I believe, and commenting them allows building.

**Comment by ldemailly** [comment]
it would be nice to patch this so it compiles out of the box
```
Index: src/utilities.cc
===================================================================
--- src/utilities.cc    (revision 143)
+++ src/utilities.cc    (working copy)
@@ -264,7 +264,7 @@
   // If gettid() could not be used, we use one of the following.
 #if defined OS_LINUX
   return getpid();  // Linux:  getpid returns thread ID when gettid is absent
-#elif defined OS_WINDOWS || defined OS_CYGWIN
+#elif defined OS_WINDOWS && !defined OS_CYGWIN
   return GetCurrentThreadId();
 #else
   // If none of the techniques above worked, we use pthread_self().
```
but that doesn't cover install and the tests...

**Comment by trayres** [comment]
That leaves a number of compile errors to fix.

**Comment by sergiud** [comment]
Please test a97d6b0e1ce34e4e1956c63de8ddd325ff164512 and report back if there are problems.
