### ISSUE TITLE
Write only INFO file?

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [google/glog#442]
Is it possible to write only the INFO file and suppress others (WARNING, ERROR)? INFO will contain the information from everything, so I don't want to have the other files. Does GLOG do this automatically?

**Comment by sergiud** [comment]
One could use a custom `LogSink` to redirect the output into a single file. See [code documentation](https://github.com/google/glog/blob/93772540629aba2139b50ebdb7a460eff20f99e9/src/glog/logging.h#L1451-L1493) for details.
