### ISSUE TITLE
Build glog on QNX/AArch64

### ISSUE THREAD

**Issue by zeb209** [google/glog#444]
Did anyone cross-compile glog, targeting QNX/aarch64? I tried hard to find instructions and could not find any. Here is one of the many things I tried that failed:
`./autogen.sh`
`./configure --prefix=/path/to/install/glog-qnx --target=aarch64-qnx-qnx --host=x86-linux-gnu CXX=/path/to/qnx700/host/linux/x86_64/usr/bin/q++ CXXFLAGS="-D__QNX__"`

Any comment would be appreciated.

**Comment by zeb209** [comment]
It reported this error message:
`/path/to/qnx700/host/linux/x86_64/usr/bin/i586-pc-nto-qnx7.0.0-ld: .libs/logging_unittest: hidden symbol `__umoddi3' in /path/to/qnx700/host/linux/x86_64/usr/lib/gcc/i586-pc-nto-qnx7.0.0/5.4.0/pic/libgcc.a(_umoddi3.o) is referenced by DSO
/path/to/qnx700/host/linux/x86_64/usr/bin/i586-pc-nto-qnx7.0.0-ld: final link failed: Bad value
cc: /path/to/qnx700/host/linux/x86_64/usr/bin/i586-pc-nto-qnx7.0.0-ld error 1
Makefile:1114: recipe for target 'logging_unittest' failed
`

**Comment by stefanseefeld** [comment]
I have no idea whether this is related to your link failure, but I believe you are using the configure options `--host` and `--target` incorrectly:
What you call `--target` should actually be `--host` (the machine on which the compiled code will run), and what you call `--host` should be `--build` (the machine on which you are performing the build). FWIW...

**Comment by pi1ot** [comment]
./autogen.sh
./configure CXX=aarch64-unknown-nto-qnx7.0.0 CXXFLAGS='-U__QNX__'
make

**Comment by sergiud** [comment]
autoconf is not supported anymore.
