### ISSUE TITLE
Corrupted log messages when built with TLS enabled on Windows

### ISSUE THREAD

**Issue by zenden2k** [google/glog#451]
When thread-local storage is enabled, I get corrupted log messaged in my class derived from LogSink.

I have generated Visual Studio solution (Win32) using CMake. I am using Microsoft Visual Studio 2017 on Windows 8.1 64 bit.
I have built static glog library with "WITH_TLS" option enabled (it is enabled by default) and gflags disabled (if it matters). All tests passed.

Here is a sample code to reproduce this:

```cpp
#include <glog/logging.h>
#include <cassert>

class MyLogSink: public google::LogSink {
public:
    void send(google::LogSeverity severity, const char* full_filename,
        const char* base_filename, int line,
        const struct ::tm* tm_time,
        const char* message, size_t message_len) override {
        
        if (strstr(message, "Line1") && strstr(message, "Line2")) {
            assert(0);
        }
    }
};

int main(int argc, char** argv)
{
    google::InitGoogleLogging(argv[0]);
    MyLogSink sink;
    google::AddLogSink(&sink);
 
    while (true){ 
        LOG(ERROR) << "<Line1> is a very loooooooooooooooooooooooooooooong</Line1>" << std::endl;
        LOG(ERROR) << "<Line2> is so short</Line2>" << std::endl;
    }
}
```

Expected behavior:
`assert()` is not being called. 

Actual behavior:
`assert()` is being called and `message` parameter looks like two mixed messages:

```
<Line2> is so short</Line2>
ooooooooooooooooooooong</Line1>
```

I have tested with latest release(0.4.0) and master and got the same issue.
With TLS disabled everything works fine. 

Is it a bug or I am missing something?

**Comment by sergiud** [comment]
Looks like incorrect usage:
1.  `message` is valid only up to `message_len`.  You, however, assume `message` is null-terminated.
2. What do you need`std::endl` for?

**Comment by zenden2k** [comment]
Thank you. My mistake. I would never have found this bug in my code if you didn’t add this TLS functionality. `std::endl` is redundant here, I know.
