### ISSUE TITLE
App security test reports Insecure API for React Native iOS App - Binary Analysis (IPA)

### ISSUE THREAD

**Issue by kamalyzl** [google/glog#453]
Currently the project contains variables not recommended by apple, which generates vulnerabilities when compiling an ipa.
for example:

https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1

Don’t use these functions | Use these instead
-- | --
strcat | strlcat
strcpy | strlcpy
strncat | strlcat
strncpy | strlcpy
sprintf | snprintf (see note) or asprintf
vsprintf | vsnprintf (see note) or vasprintf
gets | fgets (see note) or use Core Foundation or Foundation API

I would like to know if it is possible to correct them since it is giving problems in the projects created with native react

**Comment by sergiud** [comment]
Since you closed the corresponding PR #456, I guess you have found a different solution.
