### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/glog#461]
‘a’ initialized to 0
https://github.com/google/glog/blob/ba8a9f6952d04d1403b97df24e6836227751454e/src/signalhandler_unittest.cc#L61

Division by zero
https://github.com/google/glog/blob/ba8a9f6952d04d1403b97df24e6836227751454e/src/signalhandler_unittest.cc#L62

**Comment by sergiud** [comment]
This is intended since it's a unit test.
