### ISSUE TITLE
Never used variable 'new_hook'

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/glog#462]
https://github.com/google/glog/blob/ba8a9f6952d04d1403b97df24e6836227751454e/src/logging_unittest.cc#L306

the same issue  in line 319

https://github.com/google/glog/blob/ba8a9f6952d04d1403b97df24e6836227751454e/src/logging_unittest.cc#L319

advice: delete the variable which is never used

**Comment by sergiud** [comment]
It is being used for scoped assignment.
