### ISSUE TITLE
GOOGLE_GLOG_DLL_DECL needs to be put into header file

### ISSUE THREAD

**Issue by bruceOctree** [google/glog#469]
Having CMake set this by compiler command line means anyone using an already compiled library must know what the value was at glog compile time.  This should be put directly into the header (include) files or better into a global config header file.

**Comment by serhatgiydiren** [comment]
Hi.
There is ifndef statement in logging.h, what type of error or problem you are getting?

```
// Annoying stuff for windows -- makes sure clients can import these functions
#ifndef GOOGLE_GLOG_DLL_DECL
# if defined(_WIN32) && !defined(__CYGWIN__)
#   define GOOGLE_GLOG_DLL_DECL  __declspec(dllimport)
# else
#   define GOOGLE_GLOG_DLL_DECL
# endif
#endif
```
