### ISSUE TITLE
Output log callback function?

### ISSUE THREAD

**Issue by X-Crack** [google/glog#470]
Can this callback be added in the next version?

It enables us to customize functions to output at any location we want.

**Comment by sergiud** [comment]
I believe this one can be easily solved by writing an own sink. No need for additional features.

**Comment by MIXISAMA** [comment]
> I believe this one can be easily solved by writing an own sink. No need for additional features.

Please forgive me as a c++ novice. If the sink function contains the glog function, the number of source lines displayed by the log is fixed in the sink function. I don't know if I am thinking right.

**Comment by x10000year** [comment]
@sergiud But there is no way to prevent logs from writting to default files/stdout/stderr other than custom sinks. Can we redirect all logs to custom sinks and don't write them to anywhere else?

**Comment by liupeiqiHN** [comment]
really really really need callback function.

**Comment by ArnavBalyan** [comment]
++ This is really needed, it's very inflexible otherwise.

**Comment by ArnavBalyan** [comment]
cc @sergiud

**Comment by sergiud** [comment]
Have you checked the docs? https://google.github.io/glog/stable/sinks/#custom-sinks

**Comment by x10000year** [comment]
@sergiud However, even if custom log sink is registered, LOG() still log to the default log file and there is no way to disable that.

**Comment by sergiud** [comment]
This is not true. Use `google::SetLogDestination(0, "")` to disable file output.
