### ISSUE TITLE
Not able to use severity level properly.

### ISSUE THREAD

**Issue by rahulsharma11** [google/glog#490]
Hi,
I just want to write the LOG(ERROR) to my generated file. For that i have passes "GLOG_minlogleve=2" to exlude INFO and WARNING. 
But whenever i write LOG(ERROR)<<"string", it writes all 3 files (INFO,WARNING,ERROR) files in my folder.  
This parameter setting is working correctly with consol log output but not with log file.
Is this a bug in glog?

**Comment by aesophor** [comment]
According to glog's documentation:

> Note that messages of a given severity are logged not only in the logfile for that severity, but also in all logfiles of lower severity.

So guess this is an expected behavior.

**Comment by rahulsharma11** [comment]
Ok. Thanks
