### ISSUE TITLE
‘FLAGS_v’ is already declared in this scope

### ISSUE THREAD

**Issue by zhangxiangchn** [google/glog#511]
i have install glog (0.4.0) in centos7. In clion, when the title included in my project like # include <glog/logging.h>  

the error happened like this: 
/usr/local/include/glog/logging.h:374:1: error: ‘FLAGS_v’ is already declared in this scope
 DECLARE_int32(v);  // in vlog_is_on.cc

how can i fix the problem? thanks.

**Comment by sergiud** [comment]
Is this still an issue?

**Comment by lukeskywalkers** [comment]
how do you fix it
