### ISSUE TITLE
Glog file separation by year

### ISSUE THREAD

**Issue by vctang** [google/glog#516]
Hello! There seems to be an edge case that occurs when the year switches while we are in the midst of writing glogs.

For instance, if we are writing glogs at 11:59 pm on 12/31/2019, and the year switches to 2020, the mmdd timestamp written on each line of the glog will not capture this year difference. Therefore, it looks like the glogs jump from 12/31/2019 to 01/01/2019 if we are only extrapolating the year from the file name, or the file creation date written at the top of each glog file.

I think some possible solutions include:

- Appending the year to each glog line in the format of [IWEF]**yyyy**mmdd hh:mm:ss.uuuuuu threadid file:line] msg
- Splitting the glog file when the year changes.

Was there a reason for not including the year in the line-by-line output format?

**Comment by aesophor** [comment]
@vctang I've opened a PR (#530) for this.

**Comment by sergiud** [comment]
Fixed in #530.

**Comment by gpshead** [comment]
FWIW I think doing this was a mistake.  It changes the log line format and is no longer compatible with Google's internal log line format.

Processes are never intended to be running for more than a year anywhere (regular software and infrastructure updates being a thing).

Anything parsing log lines should not blindly assume "current year" when parsing a line.

**Comment by cnsgsz** [comment]
Agree with @gpshead . Adding year seems to have broken google cloud logging's built-in regex-based parsing for glogs.

**Comment by sergiud** [comment]
@cnsgsz Could you please create a new issue? The year prefix could be made optional.
