### ISSUE TITLE
./configure && make && make install fails with error: expected initializer before 'Demangle'

### ISSUE THREAD

**Issue by rgiordan** [google/glog#52]
The error is below.  I see the same problem referenced in https://github.com/google/glog/pull/7, though it's not clear to me from the discussion whether this issue is fixed, and the instructions still direct users to use `./configure && make && make install`.

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-demangle.lo -MD -MP -MF src/.deps/libglog_la-demangle.Tpo -c src/demangle.cc  -fPIC -DPIC -o src/.libs/libglog_la-demangle.o
In file included from src/demangle.cc:38:0:
src/demangle.h:80:27: error: expected initializer before 'Demangle'
 bool GOOGLE_GLOG_DLL_DECL Demangle(const char *mangled, char *out, int out_size);
                           ^
```

**Comment by binary42** [comment]
I'd like to second this error.

**Comment by binary42** [comment]
Adding:
// Annoying stuff for windows -- makes sure clients can import these functions
#ifndef GOOGLE_GLOG_DLL_DECL
# if defined(_WIN32) && !defined(__CYGWIN__)
#   define GOOGLE_GLOG_DLL_DECL  __declspec(dllimport)
# else
#   define GOOGLE_GLOG_DLL_DECL
# endif
#endif

to config.h helps, but more issues have arisen....

**Comment by binary42** [comment]
test.cc' || echo './'`src/logging_unittest.cc
src/logging_unittest.cc:64:17: error: ‘GFLAGS_NAMESPACE’ is not a namespace-name
 using namespace GFLAGS_NAMESPACE;
                 ^
src/logging_unittest.cc:64:33: error: expected namespace-name before ‘;’ token
 using namespace GFLAGS_NAMESPACE;
                                 ^
make: *** [src/logging_unittest-logging_unittest.o] Error 1

**Comment by binary42** [comment]
FYI - Pull down version 0.3.3 - builds and installs fine

**Comment by evinism** [comment]
seconding this error. 

src/demangle.h:80:27: error: expected initializer before 'Demangle'
 bool GOOGLE_GLOG_DLL_DECL Demangle(const char *mangled, char *out, int out_size);
                           ^
Makefile:1198: recipe for target 'src/libglog_la-demangle.lo' failed
make: *** [src/libglog_la-demangle.lo] Error 1

v0.3.4 seems to work, but I'm getting this (almost definitely unrelated) error:

/usr/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libgflags.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:1041: recipe for target 'libglog.la' failed

Time to sleep.

**Comment by DrustZ** [comment]
seconding this error.

**Comment by Spiralwise** [comment]
Pull down to version 0.3.3 didn't work for me (CentOS 7).

**Comment by metallo25** [comment]
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I./src  -I./src     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -DNDEBUG -g -O2 -MT src/libglog_la-demangle.lo -MD -MP -MF src/.deps/libglog_la-demangle.Tpo -c -o src/libglog_la-demangle.lo `test -f 'src/demangle.cc' || echo './'`src/demangle.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-demangle.lo -MD -MP -MF src/.deps/libglog_la-demangle.Tpo -c src/demangle.cc  -fPIC -DPIC -o src/.libs/libglog_la-demangle.o
In file included from src/demangle.cc:38:0:
src/demangle.h:80:27: error: expected initializer before 'Demangle'
 bool GOOGLE_GLOG_DLL_DECL Demangle(const char *mangled, char *out, int out_size);
                           ^
make: *** [src/libglog_la-demangle.lo] Error 1


How to fix it?

**Comment by hyuce** [comment]
I have been same error and I tried following command on Ubuntu 14.04. It did work.
---
cd glog
mkdir build && cd build
export CXXFLAGS="-fPIC" && cmake .. && make VERBOSE=1
make 
sudo make install
---

**Comment by Spiralwise** [comment]
I just used the trick described by binary42 and add the flags `CMAKE_CXX_FLAGS:STRING=-fPIC` via ccmake (or edit CMakeCache.txt manualy).

**Comment by 450255457** [comment]
OS：Ubuntu 14.04.2 LTS
How do we solve those problems?

**Comment by MagnusBai** [comment]
@hyuce It works well. thank you so much

**Comment by jsnel** [comment]
The workaround of @hyuce works well, but it cannot be *the* solution or the standard documentation (which mentions ./configure && make && make install) should be updated. Can't a patch be made to CMakeLists.txt in order to fix this issue?

**Comment by iraadit** [comment]
The workaround of @hyuce worked for me too

**Comment by devyhia** [comment]
@hyuce 's workaround worked for me too on Ubuntu 14.04 :+1:

**Comment by yuansanwan** [comment]
@hyuce 'workaround worked for me too on ubuntu 15.10

**Comment by andreaskoepf** [comment]
@hyuce :+1:

**Comment by 06wagon** [comment]
@hyuce :+1: the workaround worked for me too

**Comment by WishBlade** [comment]
@hyuce It also works for me on centos 6.5

**Comment by eugenekolo** [comment]
It's pretty embarrassing that pulling the latest on an Ubuntu 14.04 server doesn't even build and is affected by a year old bug.

**Comment by arhuaco** [comment]
Affected. /sub.

**Comment by shi-yan** [comment]
have this issue too

**Comment by cmuellnerTheobromaSystems** [comment]
I ran into this as well on CentOS 7 (x86_64 and aarch64).
Using v0.3.4 worked.

**Comment by sergiud** [comment]
There are a couple of outstanding pull requests. Refer to #116 and #129. No need to beg for help. Once @ukai merges the PRs, the issues should be fixed in master. In the meantime, everyone is invited to test the changes and report any problems.

**Comment by sergiud** [comment]
The PRs are in the master now.

**Comment by sergiud** [comment]
I guess this issue is obsolete now.
