### ISSUE TITLE
It seems LOG_FIRST_N doesn't work correctly in class member if the class has multiple instances

### ISSUE THREAD

**Issue by iambingoNJU** [google/glog#520]
I simply check the LOG_FIRST_N implementation ,it defines a `static` var as a counter.

Say if I use LOG_FIRST_N(INFO, 3) in a class member, and there are many instances of this class in my program, It only log 3 times in all. But I expect to log 3 times in each instance.

So how to achieve this?

**Comment by sergiud** [comment]
Glog is not aware of any class instances thus logging n times per instance is not possible.
