### ISSUE TITLE
Ownership with SetLogger

### ISSUE THREAD

**Issue by geoffviola** [google/glog#524]
It seems like the comments on the `base::SetLogger` function is incorrect. It says

> [The logger ... should not be deleted by the caller](https://github.com/google/glog/blob/a6f7be14c654b49f2907ffd1bce2aaad9571e579/src/windows/glog/logging.h#L1600-L1603) 

Meanwhile, the [unit tests use a logger that is put on the stack](https://github.com/google/glog/blob/58d7f873dcde8cf0fe6f37817643a7ff4e49e6d4/src/logging_unittest.cc#L834-L836). As far as I can tell from [logging.cc](https://github.com/google/glog/blob/58d7f873dcde8cf0fe6f37817643a7ff4e49e6d4/src/logging.cc), `base::SetLogger` sets `LogDestination`'s `logger_` member variable and it is not deleted there.

It seems like the caller still owns the logger after the `base::SetLogger` call. So if the caller `new`'d the logger, it's expected that the caller also calls `delete` on the logger.

**Comment by sergiud** [comment]
Should be fixed by #503. Reopen if still an issue.
