### ISSUE TITLE
catkin_make error with glog

### ISSUE THREAD

**Issue by JJavierga** [google/glog#525]
When` I catkin_make -j 4 ,I get the following output with a lot of errors:

^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/utilities_unittest.cc:31:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/utilities_unittest.cc:32:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/utilities_unittest.cc:49:1: note: in expansion of macro ‘TEST’
 TEST(utilities, InitGoogleLoggingDeathTest) {
 ^
make[3]: *** [src/signalhandler_unittest-signalhandler_unittest.o] Error 1
make[3]: *** Se espera a que terminen otras tareas....
src/symbolize_unittest.cc:46:17: error: ‘GFLAGS_NAMESPACE’ is not a namespace-name
 using namespace GFLAGS_NAMESPACE;
                 ^
src/symbolize_unittest.cc:46:33: error: expected namespace-name before ‘;’ token
 using namespace GFLAGS_NAMESPACE;
                                 ^
In file included from src/symbolize_unittest.cc:41:0:
src/symbolize_unittest.cc: In static member function ‘static void Test_Symbolize_Symbolize::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/symbolize_unittest.cc:96:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, Symbolize) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/symbolize_unittest.cc:96:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, Symbolize) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/symbolize_unittest.cc:34:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/symbolize_unittest.cc:41:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/symbolize_unittest.cc:96:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, Symbolize) {
 ^
src/symbolize_unittest.cc: In static member function ‘static void Test_Symbolize_SymbolizeWithDemangling::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/symbolize_unittest.cc:119:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, SymbolizeWithDemangling) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/symbolize_unittest.cc:119:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, SymbolizeWithDemangling) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/symbolize_unittest.cc:34:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/symbolize_unittest.cc:41:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/symbolize_unittest.cc:119:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, SymbolizeWithDemangling) {
 ^
make[3]: *** [src/utilities_unittest-utilities_unittest.o] Error 1
src/demangle_unittest.cc:46:17: error: ‘GFLAGS_NAMESPACE’ is not a namespace-name
 using namespace GFLAGS_NAMESPACE;
                 ^
src/demangle_unittest.cc:46:33: error: expected namespace-name before ‘;’ token
 using namespace GFLAGS_NAMESPACE;
                                 ^
src/symbolize_unittest.cc: In static member function ‘static void Test_Symbolize_SymbolizeStackConsumption::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/symbolize_unittest.cc:260:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, SymbolizeStackConsumption) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/symbolize_unittest.cc:260:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, SymbolizeStackConsumption) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/symbolize_unittest.cc:34:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/symbolize_unittest.cc:41:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/symbolize_unittest.cc:260:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, SymbolizeStackConsumption) {
 ^
In file included from src/demangle_unittest.cc:41:0:
src/demangle_unittest.cc: In static member function ‘static void Test_Demangle_CornerCases::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/demangle_unittest.cc:66:1: note: in expansion of macro ‘TEST’
 TEST(Demangle, CornerCases) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/demangle_unittest.cc:66:1: note: in expansion of macro ‘TEST’
 TEST(Demangle, CornerCases) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/demangle_unittest.cc:34:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/demangle_unittest.cc:41:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/demangle_unittest.cc:66:1: note: in expansion of macro ‘TEST’
 TEST(Demangle, CornerCases) {
 ^
src/symbolize_unittest.cc: In static member function ‘static void Test_Symbolize_SymbolizeWithDemanglingStackConsumption::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/symbolize_unittest.cc:278:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, SymbolizeWithDemanglingStackConsumption) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/symbolize_unittest.cc:278:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, SymbolizeWithDemanglingStackConsumption) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/symbolize_unittest.cc:34:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/symbolize_unittest.cc:41:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/symbolize_unittest.cc:278:1: note: in expansion of macro ‘TEST’
 TEST(Symbolize, SymbolizeWithDemanglingStackConsumption) {
 ^
src/demangle_unittest.cc: In static member function ‘static void Test_Demangle_Clones::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/demangle_unittest.cc:83:1: note: in expansion of macro ‘TEST’
 TEST(Demangle, Clones) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/demangle_unittest.cc:83:1: note: in expansion of macro ‘TEST’
 TEST(Demangle, Clones) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/demangle_unittest.cc:34:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/demangle_unittest.cc:41:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/demangle_unittest.cc:83:1: note: in expansion of macro ‘TEST’
 TEST(Demangle, Clones) {
 ^
src/demangle_unittest.cc: In static member function ‘static void Test_Demangle_FromFile::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/demangle_unittest.cc:105:1: note: in expansion of macro ‘TEST’
 TEST(Demangle, FromFile) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/demangle_unittest.cc:105:1: note: in expansion of macro ‘TEST’
 TEST(Demangle, FromFile) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/demangle_unittest.cc:34:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/demangle_unittest.cc:41:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/demangle_unittest.cc:105:1: note: in expansion of macro ‘TEST’
 TEST(Demangle, FromFile) {
 ^
src/demangle_unittest.cc: In function ‘int main(int, char**)’:
src/demangle_unittest.cc:128:43: error: ‘ParseCommandLineFlags’ was not declared in this scope
   ParseCommandLineFlags(&argc, &argv, true);
                                           ^
src/demangle_unittest.cc:128:43: note: suggested alternative:
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/demangle_unittest.cc:34:
/usr/local/include/gflags/gflags.h:346:31: note:   ‘gflags::ParseCommandLineFlags’
 extern GFLAGS_DLL_DECL uint32 ParseCommandLineFlags(int *argc, char*** argv, bool remove_flags);
                               ^
src/logging_unittest.cc:64:17: error: ‘GFLAGS_NAMESPACE’ is not a namespace-name
 using namespace GFLAGS_NAMESPACE;
                 ^
src/logging_unittest.cc:64:33: error: expected namespace-name before ‘;’ token
 using namespace GFLAGS_NAMESPACE;
                                 ^
src/logging_unittest.cc: In function ‘int main(int, char**)’:
src/logging_unittest.cc:180:43: error: ‘ParseCommandLineFlags’ was not declared in this scope
   ParseCommandLineFlags(&argc, &argv, true);
                                           ^
src/logging_unittest.cc:180:43: note: suggested alternative:
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:346:31: note:   ‘gflags::ParseCommandLineFlags’
 extern GFLAGS_DLL_DECL uint32 ParseCommandLineFlags(int *argc, char*** argv, bool remove_flags);
                               ^
In file included from src/logging_unittest.cc:58:0:
src/logging_unittest.cc: In static member function ‘static void Test_DeathNoAllocNewHook_logging::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:297:1: note: in expansion of macro ‘TEST’
 TEST(DeathNoAllocNewHook, logging) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:297:1: note: in expansion of macro ‘TEST’
 TEST(DeathNoAllocNewHook, logging) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/logging_unittest.cc:58:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/logging_unittest.cc:297:1: note: in expansion of macro ‘TEST’
 TEST(DeathNoAllocNewHook, logging) {
 ^
src/logging_unittest.cc: In function ‘void TestRawLogging()’:
src/logging_unittest.cc:309:3: error: ‘FlagSaver’ was not declared in this scope
   FlagSaver saver;
   ^
src/logging_unittest.cc:309:3: note: suggested alternative:
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
src/logging_unittest.cc:309:13: error: expected ‘;’ before ‘saver’
   FlagSaver saver;
             ^
src/logging_unittest.cc: In function ‘void LogWithLevels(int, int, bool, bool)’:
src/logging_unittest.cc:364:3: error: ‘FlagSaver’ was not declared in this scope
   FlagSaver saver;
   ^
src/logging_unittest.cc:364:3: note: suggested alternative:
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
src/logging_unittest.cc:364:13: error: expected ‘;’ before ‘saver’
   FlagSaver saver;
             ^
make[3]: *** [src/symbolize_unittest-symbolize_unittest.o] Error 1
In file included from src/logging_unittest.cc:58:0:
src/logging_unittest.cc: In static member function ‘static void Test_DeathRawCHECK_logging::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:437:1: note: in expansion of macro ‘TEST’
 TEST(DeathRawCHECK, logging) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:437:1: note: in expansion of macro ‘TEST’
 TEST(DeathRawCHECK, logging) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/logging_unittest.cc:58:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/logging_unittest.cc:437:1: note: in expansion of macro ‘TEST’
 TEST(DeathRawCHECK, logging) {
 ^
make[3]: *** [src/demangle_unittest-demangle_unittest.o] Error 1
src/logging_unittest.cc: In static member function ‘static void Test_DeathSTREQ_logging::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:587:1: note: in expansion of macro ‘TEST’
 TEST(DeathSTREQ, logging) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:587:1: note: in expansion of macro ‘TEST’
 TEST(DeathSTREQ, logging) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/logging_unittest.cc:58:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/logging_unittest.cc:587:1: note: in expansion of macro ‘TEST’
 TEST(DeathSTREQ, logging) {
 ^
src/logging_unittest.cc: In static member function ‘static void Test_CheckNOTNULL_Simple::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:597:1: note: in expansion of macro ‘TEST’
 TEST(CheckNOTNULL, Simple) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:597:1: note: in expansion of macro ‘TEST’
 TEST(CheckNOTNULL, Simple) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/logging_unittest.cc:58:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/logging_unittest.cc:597:1: note: in expansion of macro ‘TEST’
 TEST(CheckNOTNULL, Simple) {
 ^
src/logging_unittest.cc: In static member function ‘static void Test_DeathCheckNN_Simple::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:608:1: note: in expansion of macro ‘TEST’
 TEST(DeathCheckNN, Simple) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:608:1: note: in expansion of macro ‘TEST’
 TEST(DeathCheckNN, Simple) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/logging_unittest.cc:58:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/logging_unittest.cc:608:1: note: in expansion of macro ‘TEST’
 TEST(DeathCheckNN, Simple) {
 ^
src/logging_unittest.cc: In static member function ‘static void Test_SafeFNMatch_logging::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:868:1: note: in expansion of macro ‘TEST’
 TEST(SafeFNMatch, logging) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:868:1: note: in expansion of macro ‘TEST’
 TEST(SafeFNMatch, logging) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/logging_unittest.cc:58:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/logging_unittest.cc:868:1: note: in expansion of macro ‘TEST’
 TEST(SafeFNMatch, logging) {
 ^
src/logging_unittest.cc: In static member function ‘static void Test_Strerror_logging::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:1043:1: note: in expansion of macro ‘TEST’
 TEST(Strerror, logging) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:1043:1: note: in expansion of macro ‘TEST’
 TEST(Strerror, logging) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/logging_unittest.cc:58:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/logging_unittest.cc:1043:1: note: in expansion of macro ‘TEST’
 TEST(Strerror, logging) {
 ^
src/logging_unittest.cc: In static member function ‘static void Test_UserDefinedClass_logging::Run()’:
src/googletest.h:177:25: error: ‘FlagSaver’ was not declared in this scope
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:1209:1: note: in expansion of macro ‘TEST’
 TEST(UserDefinedClass, logging) {
 ^
src/googletest.h:177:25: note: suggested alternative:
     static void Run() { FlagSaver fs; RunTest(); }      \
                         ^
src/logging_unittest.cc:1209:1: note: in expansion of macro ‘TEST’
 TEST(UserDefinedClass, logging) {
 ^
In file included from src/glog/logging.h:86:0,
                 from src/utilities.h:82,
                 from src/logging_unittest.cc:33:
/usr/local/include/gflags/gflags.h:277:23: note:   ‘gflags::FlagSaver’
 class GFLAGS_DLL_DECL FlagSaver {
                       ^
In file included from src/logging_unittest.cc:58:0:
src/googletest.h:177:35: error: expected ‘;’ before ‘fs’
     static void Run() { FlagSaver fs; RunTest(); }      \
                                   ^
src/logging_unittest.cc:1209:1: note: in expansion of macro ‘TEST’
 TEST(UserDefinedClass, logging) {
 ^
make[3]: *** [src/logging_unittest-logging_unittest.o] Error 1
make[2]: *** [glog_catkin/glog_src-prefix/src/glog_src-stamp/glog_src-build] Error 2
make[1]: *** [glog_catkin/CMakeFiles/glog_src.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
make: *** [all] Error 2
Invoking "make -j 4"  failed 

Any idea why this happens? I'm currently running ubuntu 14.04

**Comment by sergiud** [comment]
Ubuntu 14.04 is very old. Please update.
