### ISSUE TITLE
stacktrace is not produced on aarch64

### ISSUE THREAD

**Issue by huangtianhua** [google/glog#531]
I built and test apache/kudu on aarch64, and there are some tests failed because the stacktrace is not produced, I debug it and find 'HAVE_LIB_UNWIND'=1, and seems it uses libunwind lib to get the stack trace(maybe in stacktrace_libunwind-inl.h), but it failed. I saw the comment in utilities.h, it says the first way to get stacktrace of libunwind is still in development? so the function of libunwind to get stacktrace dosen't work? or it doesn't work on aarch64? Please help me to fix this, thanks.

**Comment by sergiud** [comment]
There's an open PR #529 for this feature.

**Comment by sergiud** [comment]
libunwind fixed the issue.
