### ISSUE TITLE
"sprintf" function being used in googletest.h which is not secure

### ISSUE THREAD

**Issue by chaira19** [google/glog#536]
The sprintf function, when used with certain format specifiers, poses two types of security risk: (1) writing memory it shouldn't; (2) reading memory it shouldn't. If snprintf is used with a size parameter that matches the buffer, it won't write anything it shouldn't.

**Comment by sergiud** [comment]
What issue is this causing?

**Comment by chaira19** [comment]
@sergiud I have updated the description. sprintf function reads and write memory beyond that it shouldn't and therefore has security problems. It is banned in many organizations including mine.

**Comment by sergiud** [comment]
Fixed in #551.
