### ISSUE TITLE
Support to modify verbose log level for mudules

### ISSUE THREAD

**Issue by acelyc111** [google/glog#538]
Now we have supportted to modify global log level by `google::SetCommandLineOption("minloglevel", new_level)`, but in some cases, we want to modify log level for some mudules, but it's not supprtted now.
```
#if defined(__GNUC__)
// We emit an anonymous static int* variable at every VLOG_IS_ON(n) site.
// (Normally) the first time every VLOG_IS_ON(n) site is hit,
// we determine what variable will dynamically control logging at this site:
// it's either FLAGS_v or an appropriate internal variable
// matching the current source file that represents results of
// parsing of --vmodule flag and/or SetVLOGLevel calls.
#define VLOG_IS_ON(verboselevel)                                \
  __extension__  \
  ({ static google::int32* vlocal__ = &google::kLogSiteUninitialized;           \
     google::int32 verbose_level__ = (verboselevel);                    \
     (*vlocal__ >= verbose_level__) &&                          \
     ((vlocal__ != &google::kLogSiteUninitialized) ||                   \
      (google::InitVLOG3__(&vlocal__, &FLAGS_v,                         \
                   __FILE__, verbose_level__))); })
#else
// GNU extensions not available, so we do not support --vmodule.
// Dynamic value of FLAGS_v always controls the logging level.
#define VLOG_IS_ON(verboselevel) (FLAGS_v >= (verboselevel))
#endif
```
Accordding to these code, when `VLOG_IS_ON` is called at the first time, `vlocal__` will be initialized as a non-`google::kLogSiteUninitialized` pointer, then we will use it forever, that means mudule verbose log level is immutable forever.
On production environment, sometimes we need some more verbose logging, but reset `-vmodule` and restart process is unacceptable, can we support to modify verbose log level for mudules?

**Comment by sergiud** [comment]
Is this still an issue? `kLogSiteUninitialized` was removed in 4a82a856d281e78c2af8c0ea35f0b6b8b4688598.
