### ISSUE TITLE
Is it possible to cancat two log messages in the sample line?

### ISSUE THREAD

**Issue by valaxkong** [google/glog#539]
consider this code:
LOG(INFO) << "AAA";
/* Some other codes */
LOG(INFO) << "BBB";

I want to log "AAABBB" in a same line. But I have to call LOG seperately.
Is it possible now?

**Comment by sergiud** [comment]
Could please provide a full example of what exactly are trying to achieve?

**Comment by sergiud** [comment]
Feel free to reopen once you can provide more info.
