### ISSUE TITLE
Link error with ThreadSanitizer

### ISSUE THREAD

**Issue by neilconway** [google/glog#54]
glog 0.3.4 doesn't compile using clang's thread-sanitizer:

```
$ uname -a
Linux vagrant-ubuntu-vivid-64 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ ./configure CC=clang CXX=clang++ CFLAGS="-fsanitize=thread" CXXFLAGS="-fsanitize=thread" LDFLAGS=-fsanitize=thread
[...]
$ make
[...]
/bin/bash ./libtool  --tag=CXX   --mode=link clang++      -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -fsanitize=thread  -fsanitize=thread -o logging_unittest  src/logging_unittest-logging_unittest.o  libglog.la       -lpthread
libtool: link: clang++ -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -fsanitize=thread -fsanitize=thread -o .libs/logging_unittest src/logging_unittest-logging_unittest.o  ./.libs/libglog.so -lpthread
src/logging_unittest-logging_unittest.o: In function `operator delete[](void*)':
src/logging_unittest.cc:(.text+0x370): multiple definition of `operator delete[](void*)'
/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/lib/linux/libclang_rt.tsan-x86_64.a(tsan_interceptors.o):(.text+0x2870): first defined here
src/logging_unittest-logging_unittest.o: In function `operator delete(void*)':
src/logging_unittest.cc:(.text+0x320): multiple definition of `operator delete(void*)'
/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/lib/linux/libclang_rt.tsan-x86_64.a(tsan_interceptors.o):(.text+0x26f0): first defined here
src/logging_unittest-logging_unittest.o: In function `operator new[](unsigned long)':
src/logging_unittest.cc:(.text+0x240): multiple definition of `operator new[](unsigned long)'
/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/lib/linux/libclang_rt.tsan-x86_64.a(tsan_interceptors.o):(.text+0x22a0): first defined here
src/logging_unittest-logging_unittest.o: In function `operator new(unsigned long)':
src/logging_unittest.cc:(.text+0x120): multiple definition of `operator new(unsigned long)'
/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/lib/linux/libclang_rt.tsan-x86_64.a(tsan_interceptors.o):(.text+0x2130): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:1079: recipe for target 'logging_unittest' failed
make: *** [logging_unittest] Error 1
```

i.e., tsan and glog both want to define their own replacements for operator new. Admittedly, this is unfortunate behavior on tsan's part (see https://llvm.org/bugs/show_bug.cgi?id=19660 for griping about asan, which does the same thing).

Since glog only seems to replace operator new for testing purposes, I wonder whether it would be possible to either:
- Make it so that the unit test code is not compiled as part of a normal build (make building the unit tests a dependency of the "check" target, for example)
- Provide a configure option or #ifdef to avoid replacing operator new.

**Comment by toddlipcon** [comment]
Hey Neil. We're hitting this one too. Have you done any workaround patch already on your end?

**Comment by neilconway** [comment]
@toddlipcon Hey Todd! Unfortunately not, I haven't spent any more time on this.

**Comment by cherusker** [comment]
Running into the same issues with the AddressSanitizer. I will apply a similar patch like @adembo but it would be nice if you could make building the tests optional.

**Comment by sergiud** [comment]
This is already possible. Use the version from master to check whether the problem persists. Closing for now.

**Comment by cherusker** [comment]
@sergiud I am pretty sure I miss something obvious here but how exactly would I exclude the tests from the build?

**Comment by sergiud** [comment]
When configuring glog using CMake, set `BUILD_TESTING`  to `OFF`.

**Comment by cherusker** [comment]
Whoops, I didn't look into CMake but only into autogen etc. Thanks, that works as expected :)
