### ISSUE TITLE
error while installing pod

### ISSUE THREAD

**Issue by mayur2345** [google/glog#541]
Try `/Users/malhar/Library/Caches/CocoaPods/Pods/External/glog/f09d6cdb8398b4922e87d51f5245de7e-2f640/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: WARNING: using cross tools not prefixed with host triplet
configure: WARNING: Could not find the PC.  Will not output failed addresses...
sed: 1: "s/.*%!_!# !%!_!#  _%!_! ...": unterminated substitute pattern
configure: error: could not make ./config.status

**Comment by sergiud** [comment]
Generally, there is no support for third party tools unless someone is willing to look into the issue. Besides that, autoconf support is deprecated and will be removed soon.
