### ISSUE TITLE
How to properly use glog with static/global objects?

### ISSUE THREAD

**Issue by daravi** [google/glog#547]
Hi. I am using glog in a muti-threaded application with some static classes (singletons) for managing ports and database. My program is crashing on termination:
```
*** Aborted at 1588035923 (unix time) try "date -d @1588035923" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x2e06dbce000027c2) received by PID 10213 (TID 0x7ffff7fcce80) from PID 10178; stack trace: ***
    @     0x7ffff243bdc0 (unknown)
    @     0x7ffff1c7c8df __GI_raise
    @     0x7ffff1c66cf5 __GI_abort
    @          0x11e6f3b glog_internal_namespace_::Mutex::Lock()
    @          0x11e58c3 glog_internal_namespace_::MutexLock::MutexLock()
    @          0x11e0068 google::LogMessage::Flush()
    @          0x11dfeac google::LogMessage::~LogMessage()
    @           0xbb7dee mmi::core::ipc::ZMQServer::~ZMQServer()
    @           0xbb0cc5 std::__1::__shared_ptr_emplace<>::__on_zero_shared()
    @           0x519178 std::__1::__shared_count::__release_shared()
    @           0x51910e std::__1::__shared_weak_count::__release_shared()
    @           0xbadad5 std::__1::shared_ptr<>::~shared_ptr()
    @           0xbada5a std::__1::shared_ptr<>::operator=()
    @           <my program stack ends here, attempting LOG() from the singleton destructor>
```
My guess is that glog is doing its global clean-ups before the destructor of my global object hits the LOG() line. My understanding is that the C++ runtime guarantees reverse order of creation for static object destruction, so it seems to me that the glog backend should have been destroyed after my program's objects since I call `google::InitGoogleLogging(argv[0]);` in the begining of my program. So here are my questions:
- Are glog's global variables instantiated lazily on first LOG() use, or are they supposed to be created when I call `InitGoogleLogging`?
- Are there any recommended techniques for dealing with destruction order when it comes to using glog in static objects?

**Comment by Flamefire** [comment]
This is happening in PyTorch too. See https://github.com/pytorch/pytorch/issues/41561 and https://github.com/pytorch/pytorch/issues/41474. The crash is traced to this mutex: https://github.com/google/glog/blob/28321d8959574a8268de3ebe41d40cf65415fc9b/src/logging.cc#L380

So basically there exists a global static which leads to a race in the destruction of other global statics. A solution would be to purposely "leak" the mutex on program termination. See https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use

Note: Same issue as #504 and #363

**Comment by wypx** [comment]
Not resolved yet?

**Comment by daravi** [comment]
I was hoping for a response from a maintainer and there is no response yet. So not resolved for me.

**Comment by asekretenko** [comment]
A similar issue is observed in Apache Mesos: https://issues.apache.org/jira/browse/MESOS-10201

It should be noted that avoiding execution of non-trivial `~Mutex()` also would apparently be fully in line with Google's C++ Style Guide: https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

**Comment by sergiud** [comment]
> My understanding is that the C++ runtime guarantees reverse order of creation for static object destruction, so it seems to me that the glog backend should have been destroyed after my program's objects since I call `google::InitGoogleLogging(argv[0]);` in the begining of my program.

The C++ standard guarantees a reverse destruction order only within same class/scope/compilation unit. However, the linking order of compilation units also determines the order of object destruction within a module. This becomes even more complicated if multiple modules (e.g., shared libraries, executables etc.) are involved.

My guess is that you are trying to access an already destructed glog object instance from your singleton which invokes undefined behavior. This error on your part can be easily avoided if you do the cleanup just before returning form your process entry point (e.g., `main`).

Without a minimal working example that demonstrates the problem I must assume the error is in the user code and thus is a won't fix for glog.

**Comment by daravi** [comment]
@sergiud Fair enough. I will close until when / if I have a reproducible example.

**Comment by z-hasher** [comment]
> > My understanding is that the C++ runtime guarantees reverse order of creation for static object destruction, so it seems to me that the glog backend should have been destroyed after my program's objects since I call `google::InitGoogleLogging(argv[0]);` in the begining of my program.
> 
> The C++ standard guarantees a reverse destruction order only within same class/scope/compilation unit. However, the linking order of compilation units also determines the order of object destruction within a module. This becomes even more complicated if multiple modules (e.g., shared libraries, executable etc.) are involved.
> 
> My guess is that you are trying to access an already destructed glog object instance from your singleton which invokes undefined behavior. This error on your part can be easily avoided if you do the cleanup just before returning from your process entry point (e.g., `main`).
> 
> Without a minimal working example demonstrating that the problem is caused by glog, I must assume the error is in the user code. At least the initial backtrace indicates that this is in fact the case. Managing destructed objects is hardly possible and thus a won't fix for glog.

we patched it in our own code with intentionally "leaking" the global mutex object, which avoids the SIGABRT for us. Basically something like
```
static std::mutex& log_mutex = *new std::mutex;
```
