### ISSUE TITLE
"#error Do not know how to define a 32-bit integer quantity on your system" with cygwin

### ISSUE THREAD

**Issue by foroughmajidi** [google/glog#549]
I try to build glog with cmake in cygwin64 as following:
1-cmake . -DBUILD_SHARED_LIBS=on
2-make -j
the result of above instruction:
![Capture42](https://user-images.githubusercontent.com/51900859/80909764-a316d680-8cdf-11ea-9974-640585f2057b.PNG)
Whould you please tell me how to solve it?

**Comment by foroughmajidi** [comment]
After I installed libunwind and build glog as following:
cmake  -DBUILD_SHARED_LIBS=ON  -DUnwind_PLATFORM_LIBRARY=X86-64  

I got this error:

![Capture43](https://user-images.githubusercontent.com/51900859/80913337-be421000-8cf8-11ea-8953-4948892500b2.PNG)

**Comment by sergiud** [comment]
I am unable to reproduce these errors with current master.
