### ISSUE TITLE
Using glog with bazel

### ISSUE THREAD

**Issue by ourarash** [google/glog#557]
I was able to install `glog` with:

`brew install glog`

Then I can successfully compile and use it using g++:

`g++ src/main/main_logger.cc -std=c++17  -lglog`

I can easily do this without copying the original glog include files into my repo.

How can I do this with `bazel`?

I get this error:

    fatal error: 'glog/logging.h' file not found
    #include <glog/logging.h>
         ^~~~~~~~~~~~~~~~
    1 error generated.

The example provided [here](https://github.com/google/glog/tree/master/bazel) seems to be dependent on the files under source in glog repo. Is there any way to create an independent repo after installing glog with brew so that I don't have to copy all the files in Google's glog repo into mine?

**Comment by sergiud** [comment]
Do this [docs](https://github.com/google/glog#bazel) help?
