### ISSUE TITLE
Cannot pass `stderrthreshold` as environment variable

### ISSUE THREAD

**Issue by daravi** [google/glog#558]
I am able set FLAGS_stderrthreshold in code (while `logtostderr` and `alsologtostderr` are left as default) and see desired behavior. i.e. all available logs go to file and anything at or above the threshold also goes to stderr.

However when setting `GLOG_stderrthreshold=<lvl>` environment variable it's as if I am not setting this variable at all. It seems like for some reason this environment variable is not being correctly picked up by GLOG.

**Comment by yumais2** [comment]
I have the same issue here. Both DLOG and LOG does not work. It seems to be stuck at level 2.

**Comment by jstiefel** [comment]
Same issue here.

**Comment by gouchaoer** [comment]
same issue here
