### ISSUE TITLE
compile error: use of overloaded operator '<<' is ambiguous

### ISSUE THREAD

**Issue by xingx1** [google/glog#562]
I'm using Ubuntu 18.04.4 LTS (Bionic Beaver), clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final), cmake version 3.10.2.
I cloned, compiled, installed the project, and trying to use it in my own project.
But once I included the header "glog/logging.h", I got an compile error like:
```
_/usr/local/include/glog/logging.h:649:9: error: use of overloaded operator '<<' is ambiguous 
(with operand types 'std::ostream' (aka 'basic_ostream<char>') and 'const nullptr_t')
  (*os) << v;_
```
Did this because the use of the operator is really ambiguous or there's implicit incompatible with some cmake settings I made?

____________________________________________________________________________________________

I found it is because that **CHECK_NE() is not suitable to estimate a pointer to nullptr.**
Try following code:
```c++
#include "glog/logging.h"
#include <iostream>

int main() {
    int i = 0;
    CHECK_NE(&i, nullptr);
    return 0;
}
```

**Comment by Mizux** [comment]
Got this bug on Google OR-Tools too. It may come from the version of the compiler

Result I got:
* alpine, archlinux, fedora OK (gcc 10.2)
* ubuntu OK (gcc 9.3)
* centos FAIL (gcc 8.3.1)
* debian FAIL (gcc 8.3.0)
ref: https://github.com/google/or-tools/actions/runs/315808746

* runner ubuntu github FAIL (gcc 7.5.0)

**Comment by Mizux** [comment]
FYI, a simple workaround, is to replace:
* `CHECK_NE(..., nullptr)` by `CHECK(... != nullptr)` and
* `CHECK_EQ(..., nullptr)` by `CHECK(... == nullptr)`

Otherwise you may also cherry pick the PR #342
