### ISSUE TITLE
Disabling 'Symbolize functionality' is not working

### ISSUE THREAD

**Issue by m-kurbanov** [google/glog#563]
From #523 
`cmake -DWITH_SYMBOLIZE=OFF` is not working, because `HAVE_SYMBOLIZE` is defined in:
https://github.com/google/glog/blob/0a2e5931bd5ff22fd3bf8999eb8ce776f159cda6/src/utilities.h#L130-L141

**Comment by edbaunton** [comment]
On what platform is this?

**Comment by m-kurbanov** [comment]
platform: windows
But judging from the code it's true with all platforms
