### ISSUE TITLE
Any plan to rely on abseil?

### ISSUE THREAD

**Issue by hcoona** [google/glog#564]
I'm seeing that googletest & googlebenchmark projects are relying on abseil project to eliminate some common utilities. Is there any plan that glog would do so? I think there are 3 components could benefit from the migration:

1. stacktrace
2. mutex
3. flags

**Comment by hcoona** [comment]
Maybe a better solution is to integrate the logging into abseil?

**Comment by shinh** [comment]
Yeah, I think abseil folks were thinking of adding logging feature, I don't know its status and priority, though.

**Comment by Mizux** [comment]
related to https://github.com/abseil/abseil-cpp/issues/658 which seems currently stall...

**Comment by sergiud** [comment]
I'm closing the issue as @shinh answered the question.
