### ISSUE TITLE
C++ question on DLOG macro

### ISSUE THREAD

**Issue by oryandunn** [google/glog#567]
I was looking at the header and couldn't figure out why a couple of the things were done in the DLOG macro:
```
#define DLOG(severity)  \
  static_cast<void>(0), \
  true ? (void) 0 : @ac_google_namespace@::LogMessageVoidify() & LOG(severity)
```
What is the purpose of the initial "static_cast<void>(0),"?
Why is the LogMessageVoidify() needed?  I read the comments on that class and still couldn't figure out why it was needed.

**Comment by daohu527** [comment]
## static_cast<void>(0)

This is a way to tell that it is ok for a variable to be unused suppressing corresponding compiler warning. This approach has been deprecated with introduction of [[maybe_unused]] attribute in C++17.

ref stackoverflow [link](https://stackoverflow.com/questions/49273384/what-is-purpose-of-using-static-castvoid)  

## LogMessageVoidify
LogMessageVoidify override operator &, there are comments in the code `This has to be an operator with a precedence lower than << but higher than ?:`, so the @ac_google_namespace@::LogMessageVoidify() & LOG(severity) first run <<, then
DLOG(INFO) << "Found cookies" will do nothing. If don't have LogMessageVoidify then there will be an error with <<.
```
class GOOGLE_GLOG_DLL_DECL LogMessageVoidify {
 public:
  LogMessageVoidify() { }
  // This has to be an operator with a precedence lower than << but
  // higher than ?:
  void operator&(std::ostream&) { }
};
```

**Comment by neal-zhu** [comment]
What's wrong with
`#define DLOG(severity)  LOG(severity)`
This has been buged me for a week

And what's the problem define LOG_IF as:
`#define LOG_IF(severity, condition) \
   if (condition) \
   LOG(severity)`

**Comment by asplingzhang** [comment]
> I was looking at the header and couldn't figure out why a couple of the things were done in the DLOG macro:
> 
> ```
> #define DLOG(severity)  \
>   static_cast<void>(0), \
>   true ? (void) 0 : @ac_google_namespace@::LogMessageVoidify() & LOG(severity)
> ```
> 
> What is the purpose of the initial "static_cast(0),"? Why is the LogMessageVoidify() needed? I read the comments on that class and still couldn't figure out why it was needed.

There is an explaination I think that would be your answer. https://asplingzhang.github.io/webrtc/logging/why-static_cast-void-and-LogMessageVoidify-needed-in-logging-macros/

**Comment by MHebes** [comment]
> > I was looking at the header and couldn't figure out why a couple of the things were done in the DLOG macro:
> > ```
> > #define DLOG(severity)  \
> >   static_cast<void>(0), \
> >   true ? (void) 0 : @ac_google_namespace@::LogMessageVoidify() & LOG(severity)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What is the purpose of the initial "static_cast(0),"? Why is the LogMessageVoidify() needed? I read the comments on that class and still couldn't figure out why it was needed.
> 
> There is an explaination I think that would be your answer. https://asplingzhang.github.io/webrtc/logging/why-static_cast-void-and-LogMessageVoidify-needed-in-logging-macros/

For future finders: https://github.com/asplingzhang/asplingzhang.github.io/blob/main/docs/_posts/webrtc/logging/2022-06-14-why-static_cast-void-and-LogMessageVoidify-needed-in-logging-macros.md
