### ISSUE TITLE
The identifier could not be found

### ISSUE THREAD

**Issue by gaqiang** [google/glog#577]
G:\vc\colmap-3.6\Release\glog\src\logging.cc(1868): error C3861: “truncate”: The identifier could not be found [G:\vc\colmap-3.6\Release\glog\__bu
ild__\glog.vcxproj]
G:\vc\colmap-3.6\Release\glog\src\logging.cc(1886): error C3861: “S_ISREG”: The identifier could not be found [G:\vc\colmap-3.6\Release\glog\__bui
ld__\glog.vcxproj]
G:\vc\colmap-3.6\Release\glog\src\logging.cc(1913): error C3861: “ftruncate”: The identifier could not be found [G:\vc\colmap-3.6\Release\glog\__b
uild__\glog.vcxproj]

vs2017 professional win10 x64

**Comment by gaqiang** [comment]
It happens when build the resolution using vs 2017

**Comment by gozo1234** [comment]
I meet the same problem. Are there any solutions?

**Comment by sergiud** [comment]
That looks like IntelliSense errors which are unimportant. What matters is the compiler output.
