### ISSUE TITLE
LOG(INFO) consume a lot of cpu resource

### ISSUE THREAD

**Issue by GOGOYAO** [google/glog#581]
In my code, I use `LOG(INFO) << {some logs} << .....` to print log but when I run my code, I set `minloglevel=1` to prevent `INFO` log to output.
But when I use `pprof` to check the cpu usage, I find `google::LogMessage::init` consume a lot of cpu.
![image](https://user-images.githubusercontent.com/18675094/93310603-967ebf00-f837-11ea-9c22-bb6a7b3cb334.png)

**Comment by daohu527** [comment]
That cause by "localtime_r". Can start to optimize from this aspect

**Comment by GOGOYAO** [comment]
> That cause by "localtime_r". Can start to optimize from this aspect

Sorry. I can not get your opinion. Can you give me more words?

**Comment by daohu527** [comment]
`localtime_r ` will apply and release locks, which will consume a lot of resources. As there is a `FLAGS_log_utc_time`, so set `FLAGS_log_utc_time` and try again.
https://github.com/google/glog/blob/c8f8135a5720aee7de8328b42e4c43f8aa2e60aa/src/logging.cc#L1549-L1552

**Comment by GOGOYAO** [comment]
Thank you very much
