### ISSUE TITLE
Could not find a package configuration file provided by "glog" with any of   the following names:

### ISSUE THREAD

**Issue by 353264241** [google/glog#582]
![image](https://user-images.githubusercontent.com/13993615/93869942-1bb61800-fcff-11ea-8026-1d1e086042eb.png)
As I use 
`find_package(glog REQUIRED)`
the glogConfig.cmake couldn't be found anywhere and I also didn't find it in source code.

**Comment by daohu527** [comment]
There is a doc about it. [docs](https://github.com/google/glog#consuming-glog-in-a-cmake-project)
```
cmake_minimum_required (VERSION 3.0.2)
project (myproj VERSION 1.0)

find_package (glog 0.4.0 REQUIRED)

add_executable (myapp main.cpp)
target_link_libraries (myapp glog::glog)
```
