### ISSUE TITLE
EnableLogCleaner not recognized

### ISSUE THREAD

**Issue by heavyweight87** [google/glog#586]
Hi,

I find that EnableLogCleaner does not work for me as its not found. 
Its missing from logger.h (its only in logger.h.in)

It seems like its been an included feature for a while so maybe im missing something?
I compiled and installed the lib according to the cmake instructions

**Comment by aesophor** [comment]
If you followed the instruction in README.rst to build the library with CMake, the header should be installed into `/usr/local/include/glog/`.
```
$ sudo cmake --build build --target install
-- trimmed --
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libglog.a
-- Up-to-date: /usr/local/include/glog/logging.h
-- Up-to-date: /usr/local/include/glog/raw_logging.h
-- Up-to-date: /usr/local/include/glog/stl_logging.h
-- Up-to-date: /usr/local/include/glog/vlog_is_on.h
-- Up-to-date: /usr/local/include/glog/log_severity.h
-- Up-to-date: /usr/local/lib/pkgconfig/libglog.pc
-- Up-to-date: /usr/local/lib/cmake/glog/glog-modules.cmake
-- Up-to-date: /usr/local/lib/cmake/glog/glog-config.cmake
-- Up-to-date: /usr/local/lib/cmake/glog/glog-config-version.cmake
-- Up-to-date: /usr/local/share/glog/cmake
-- Up-to-date: /usr/local/share/glog/cmake/FindUnwind.cmake
-- Up-to-date: /usr/local/lib/cmake/glog/glog-targets.cmake
-- Up-to-date: /usr/local/lib/cmake/glog/glog-targets-noconfig.cmake
```

I just built it and the function prototypes are there:
```
$ grep 'LogCleaner' /usr/local/include/glog/logging.h 
GOOGLE_GLOG_DLL_DECL void EnableLogCleaner(int overdue_days);
GOOGLE_GLOG_DLL_DECL void DisableLogCleaner();
```

Can you run the command above and see if they're there?

If they're not there, please post the output of `sudo cmake --build build --target install`

**Comment by heavyweight87** [comment]
Appologies, I was given an older version of the library (3.5) which didn't have this prototype. It works great with the latest version. Thanks

**Comment by aesophor** [comment]
No problem! I'm glad it works great for you :smile:
