### ISSUE TITLE
Exception  when set FLAGS_log_dir with "/" under windows.

### ISSUE THREAD

**Issue by chjq68** [google/glog#588]
Exception  when set FLAGS_log_dir with "/" under windows.
windows library function such as fopen() support both slash and backslash. 
also QT's QDir.absolutpath return path with slash("/"). when set FLAGS_log_dir with it, exception occured.

**Comment by sergiud** [comment]
`/` is not a valid directory on Windows. Do you possibly mean that the log directory contains forward slashes? Could you please provide an example?

**Comment by sergiud** [comment]
Feel free to reopen once you can provide more info.
