### ISSUE TITLE
Can SetLogger set severity to -1?

### ISSUE THREAD

**Issue by daohu527** [google/glog#590]
I found that SetLogger's `severity` is int.
```c++
void base::SetLogger(LogSeverity severity, base::Logger* logger) {
  MutexLock l(&log_mutex);
  LogDestination::log_destination(severity)->logger_ = logger;
}
```
but in log_destination `severity` must in [0, NUM_SEVERITIES]
```c++
inline LogDestination* LogDestination::log_destination(LogSeverity severity) {
  assert(severity >=0 && severity < NUM_SEVERITIES);
  if (!log_destinations_[severity]) {
    log_destinations_[severity] = new LogDestination(severity, NULL);
  }
  return log_destinations_[severity];
}
```

If you use an wrapped logger and set SetLogger's `severity` to -1, wrapped logger will not work, it seems use the default logger in glog then?

And I found that there are other restrictions in the code that cause `severity` should be greater or equal to 0. Why not set `severity` to unsigned type？

**Comment by sergiud** [comment]
Why would you want to set the severity to -1?

**Comment by daohu527** [comment]
This maybe a bug, because you can't stop others from setting it up. I actually encountered!

**Comment by sergiud** [comment]
With #1025 `LogSeverity` will become an enum which will prevent implicit conversions.
