### ISSUE TITLE
Does the wrapped logger write need to be synchronize?

### ISSUE THREAD

**Issue by daohu527** [google/glog#591]
I found the `SendToLog` have mutex inside, does logger's write function need synchronize then?
https://github.com/google/glog/blob/c8f8135a5720aee7de8328b42e4c43f8aa2e60aa/src/logging.cc#L1715-L1720

the `LogToAllLogfiles` will callback wrapped logger's write function, does the write need to synchronize if there is a mutex before?

**Comment by sergiud** [comment]
The comment above the function implies that there's no need for an additional lock:
https://github.com/google/glog/blob/c8f8135a5720aee7de8328b42e4c43f8aa2e60aa/src/logging.cc#L1714
Does this help?
