### ISSUE TITLE
Large integers get truncated

### ISSUE THREAD

**Issue by r-barnes** [google/glog#594]
In our application we have some loggers that trigger every millisecond.

This is problematic since `LogMessage` uses a signed 32-bit integer as the counter type (see [here](https://github.com/google/glog/blob/master/src/windows/glog/logging.h#L1205)) which can lead to a wrap every 24.85. This is bad for long-running processes.

It would probably be better if `LogMessage` used `uint64_t` or `size_t` as the counter type.

If there's a size concern, then using `uint32` as the data type would at least double the time before wrap around.

**Comment by daohu527** [comment]
`int` will wrap after 24.85 days. Seems there is no logical problem, but counting number will wrong.

**Comment by ot** [comment]
@daohu527 Signed overflow is undefined behavior in C++, and the type here is an `int`.

**Comment by daohu527** [comment]
#### LOG_EVERY_N
They use two parameters to implement this logic. **LOG_OCCURRENCES_MOD_N** will not great than N+1 to filter the log. And **LOG_OCCURRENCES** will use to count the log num.
https://github.com/google/glog/blob/c8f8135a5720aee7de8328b42e4c43f8aa2e60aa/src/glog/logging.h.in#L908-L915

So I said there is no problem with logic, int will overflow is true.
There maybe a little problem too, n should be set in [1, INT_MAX-1]
