### ISSUE TITLE
publicly visible Bazel target no longer provides any headers

### ISSUE THREAD

**Issue by shahms** [google/glog#596]
The only target accessible via Bazel (`@com_github_google_glog//:glog`) no longer provides any headers, due to PR ##488.  This breaks when using `features = ["layering_check"]`.  Given the low-level nature of logging libraries and pervasive dependencies in a code base which uses them, it's infeasible to disable that feature for just the targets which depend on glog.  The benefits afford by the check (particularly for code bases which are imported internally) means that disabling it for our entire code base isn't reasonable.

**Comment by drigz** [comment]
Do you have a repro for this? https://github.com/google/glog/pull/615 seems not to break the build, but I wasn't able to find docs on how to enable layering_check.

**Comment by shahms** [comment]
You can enabled layering_check by adding:

package(features = ["layering_check"]) or `features = ["laying_check"]` to the specific cc_ rules in question.

**Comment by drigz** [comment]
I tried that but it didn't reproduce the failure with glog at HEAD.

**Comment by shahms** [comment]
I forgot that we use Clang to do the build.  Bazel uses GCC by default, which doesn't support layering_check.  Building with clang, via:
```
build build --client_env=CC=clang  ...
```
will reproduce

**Comment by drigz** [comment]
Thank you! I was able to reproduce it, and #615 seems to fix it.
