### ISSUE TITLE
CMake build instructions do not work for paths with ampersand

### ISSUE THREAD

**Issue by FHof** [google/glog#597]
When I clone glog into a folder which has an ampersand in its absolute path, the compilation fails:
```
~/Downloads/before&after_ampersand/glog$ LC_ALL=C cmake --build build
[  4%] Copying find modules...
/bin/sh: 1: after_ampersand/glog/build/share/glog/cmake: not found
make[2]: *** [CMakeFiles/glog.dir/build.make:62: share/glog/cmake/FindUnwind.cmake] Error 127
make[1]: *** [CMakeFiles/Makefile2:1084: CMakeFiles/glog.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

### How to reproduce

* Create a folder `before&after_ampersand` and change the directory to it
* Execute the build steps shown in the Readme: https://github.com/google/glog/tree/c8f8135a5720aee7de8328b42e4c43f8aa2e60aa#building-glog-with-cmake

**Comment by daohu527** [comment]
I think it may be a cmake problem rather than glog. 

## cmake
> It works fine with fancy things like dots, eszett (ß), etc. But there are other characters that lead to fail, namely tabulation, newline and any of `"#$:;\|` (ASCII 9, 10, 34, 35, 36, 58, 59 ,92, 124). Noticeable it works fine with other non-printable characters, single quotes, etc. in directory name.

ref [link](https://gitlab.kitware.com/cmake/cmake/-/issues/16207)

It’s better not to not contain the characters in path.

**Comment by FHof** [comment]
ok, thank you for the information.
