### ISSUE TITLE
Any plan to set c++11 as default standard version?

### ISSUE THREAD

**Issue by theidexisted** [google/glog#602]
The gtest repo has changed c++ version from 03 to 11, is there any plan for glog?

**Comment by sergiud** [comment]
Yes, I would even go as far as requiring C++14 or even C++17.

@drigz @shinh @ukai Any thoughts ?

**Comment by drigz** [comment]
I don't have an opinion, although I'll note that the style guide suggests C++17: https://google.github.io/styleguide/cppguide.html#C++_Version

**Comment by sergiud** [comment]
I submitted #902 which sets C++14 as the minimum standard. C++17 seems unnecessary at this point.
