### ISSUE TITLE
BUILD file will create a conflict with build/ folder

### ISSUE THREAD

**Issue by Aymkdn** [google/glog#606]
Hi,

In the repo there is a [BUILD file](https://github.com/google/glog/blob/master/BUILD) that creates a conflict when following the [CMake instructions](https://github.com/google/glog/blob/master/README.rst#cmake) because it will try to create a `build/` folder.

I renamed the BUILD file and then I've been able to make the project.

**Comment by weiyengs** [comment]
Thanks for the helpful tip! It happened to me too!

**Comment by edbaunton** [comment]
Renaming it to `BUILD.bazel` in the tree would solve this problem for good. That approach is [recommended](https://docs.bazel.build/versions/master/build-ref.html#packages) by bazel.
