### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by how0723** [google/glog#617]
When will the new version be released?

with timestamp_in_logfile_name features

**Comment by sergiud** [comment]
I've tagged 0.5-rc1. Please give it a try.

**Comment by Arfrever** [comment]
It seems that it is now time for `0.5.0` release...

**Comment by sergiud** [comment]
Please be patient. A new version will be released soon.

**Comment by Arfrever** [comment]
(https://github.com/google/glog/milestone/2 currently mentions date 2021-04-30.)

**Comment by sergiud** [comment]
Yes. I'm very well aware.
