### ISSUE TITLE
How can I link glog with static library in my project?

### ISSUE THREAD

**Issue by zhaoxuyan** [google/glog#643]
I want to use static library(`libglog.a`) not shared to link my `heartbeat` app.

Here is my CMakeLists.txt
```bash
include_directories(
    ${CMAKE_CURRENT_LIST_DIR}
)

link_directories(

)

add_executable( heartbeat
    main.cpp
    heartbeat.cpp
    ${COMPONENTS_SRC}
    ${MODULES_SRC}
)
    
target_link_libraries( heartbeat 
    libpthread.a
    libcrypt.a
    libm.a

    libgflags.a
    libglog.a
    libhiredis.a
    libredis++.a
)

# 输出到build文件夹上层目录
set(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/..)
```
Then I get this ERROR
```bash
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libglog.a(libglog_la-utilities.o)：在函数‘google::GetStackTrace(void**, int, int) [clone .part.7]’中：
(.text+0xad)：对‘_Ux86_64_getcontext’未定义的引用
(.text+0xb8)：对‘_ULx86_64_init_local’未定义的引用
(.text+0xe7)：对‘_ULx86_64_step’未定义的引用
(.text+0x100)：对‘_ULx86_64_get_reg’未定义的引用
(.text+0x120)：对‘_ULx86_64_step’未定义的引用
collect2: error: ld returned 1 exit status
```

**Comment by sergiud** [comment]
Please see the documentation on how to consume glog in CMake projects.

**Comment by Entongsu** [comment]
Hi, I have encountered similar problems. Could you provide some hints on how to fix it? Thank you.

**Comment by sergiud** [comment]
Please refer to the [documentation](https://github.com/google/glog?tab=readme-ov-file#usage-in-projects).

**Comment by rickyyx** [comment]
Running into this as well - anyone has luck getting it work? 

For my case, we don't use a cmake system to link glog into our project, but I did use cmake to build glog into libglog.a. And run into exactly this issue when I linked glog staticly into mine. 

I am also not sure if this documentation explicitly answers this, any more specific pointer would be appreciated.

**Comment by unknown-no** [comment]
> Running into this as well - anyone has luck getting it work?
> 
> For my case, we don't use a cmake system to link glog into our project, but I did use cmake to build glog into libglog.a. And run into exactly this issue when I linked glog staticly into mine.
> 
> I am also not sure if this documentation explicitly answers this, any more specific pointer would be appreciated.

build with `-DWITH_UNWIND=none` if you don't need unwind/libunwind
