### ISSUE TITLE
Does glog support one log per day?

### ISSUE THREAD

**Issue by tengliu0929** [google/glog#644]
I have searched , but not find any method support one log per day, for example,  App_year_month_day.log  format,  is there   any methods support to set log name format? Thank you !

**Comment by darbitman** [comment]
I just added a feature that might help you here. The macro is called `LOG_EVERY_T` and it uses seconds as the time period, so if you supply the number of seconds in a day to it, you should be able to generate a log once per day.

**Comment by sergiud** [comment]
Feel free to reopen if #669 does not solve your problem.
