### ISSUE TITLE
Glog doesn't work with folly and Android ndk

### ISSUE THREAD

**Issue by karol-bisztyga** [google/glog#652]
# Description

Hey! I have a react-native project and have some problems with using `folly` that actually uses `glog`. I'm posting this here because I think this is a problem with attaching `glog` to a project rather than with `folly` itself.

I use `CMake`.

# Reproducing steps

I have [a branch](https://github.com/karol-bisztyga/rnfbjni/tree/folly) where all my work is tracked. I'm going to present following steps I took to try to make it work:
1. [commit](https://github.com/karol-bisztyga/rnfbjni/commit/371ebdc4ca1139dd7b7af17baeaf8bdde2e2a03a) I added Gradle tasks that download tools needed by `folly`(folly, double conversion, boost, glog). Most of the code is taken from [react-native's repo](https://github.com/facebook/react-native/blob/263478b91cf958f81f3010e7b9d017bb70693ba4/ReactAndroid/build.gradle)
2. As you might've noticed, I included `folly/MPMCQueue.h` but didn't use it really. Once I try to use it like this:
```
folly::MPMCQueue<int> q;
q.write(5);
```
`folly` starts to throw errors, so I took another step:
3. [commit](https://github.com/karol-bisztyga/rnfbjni/commit/571602493041fcdbea9a6496294315b95c74ffd6) I added `folly` and `double-conversion` source files, and now I get:
```
../../../.././build/third-party-ndk/glog/glog/logging.h:695: error: undefined reference to 'google::base::CheckOpMessageBuilder::NewString()'
```
From that, I understand that `glog`'s missing implementation for functions in `logging.h`, seems fair, quite like `folly` before. And now comes the issue that I failed to add sources for `glog` :(
4. I added `${GLOG_SOURCES}` to `add_library` in `CMakeLists.txt`(it's already there in the first commit I posted here, just not added yet), but then I got a lot of errors from `glog` mostly referring to preprocessor values that aren't set(like `GOOGLE_NAMESPACE`, `_START_GOOGLE_NAMESPACE_`, etc.). Example error:
```
In file included from {xxx}/rnfbjni/android/app/build/third-party-ndk/glog/glog-0.3.5/src/logging_striptest10.cc:35:
{xxx}/rnfbjni/android/app/build/third-party-ndk/glog/glog-0.3.5/src/logging_striptest_main.cc:45:17: error: expected namespace name
```
where `{xxx}` is just a path on my computer where the project is.

# Reproducing repository

So, the final repro is [here](https://github.com/karol-bisztyga/rnfbjni/tree/folly)(branch `folly`)

# Things I've tried

I tried to set those preprocessor values by myself using `build.gradle`, `CMAkeLists.txt`, also, I tried to include `glog`'s `CMake` files, but with all those attempts a lot of other errors were coming in and I felt it's going too deep and the direction's probably not the best.

I've seen [this](https://github.com/jefby/build-glog-for-android) but the scripts failed when I tried to run them. Also, I'm not sure how exactly this should work in an existing android project.

I also have seen it can be done by adding `glog` with `find_package` and linking to `target_link_libraries`(from [here](https://github.com/google/glog#consuming-glog-in-a-cmake-project)) but it covers installing `glog` in the local environment, right? I would rather avoid it.

# Questions

Now, my first question is: is this approach valid?
How can I properly add `glog` to my project using `CMake`?

Thanks in advance!

**Comment by sergiud** [comment]
First of all: what problem exactly are you trying to solve?

> I also have seen it can be done by adding `glog` with `find_package` and linking to `target_link_libraries`(from [here](https://github.com/google/glog#consuming-glog-in-a-cmake-project)) but it covers installing `glog` in the local environment, right? I would rather avoid it.

This is incorrect. You can use glog directly from your build directory.

> How can I properly add `glog` to my project using `CMake`?

The proper way of linking glog is described in the documentation.

**Comment by karol-bisztyga** [comment]
Thanks for the quick reply! 🙌 

> First of all: what problem exactly are you trying to solve?

Well, I'm trying to build the project I posted (in a repro section) on android. Lower level it comes to using `glog` with android ndk. I'm not really sure what's unclear here. Can you specify what exactly is confusing/misleading for you? I tried to make myself clear about what the problem is...

> This is incorrect. You can use glog directly from your build directory.

Ok, my bad. Anyways, I've also tried to link it following the docs, so I added to `CMakeLists.txt`:
```
set(glog_DIR ${CMAKE_CURRENT_SOURCE_DIR}/build/third-party-ndk/third-party-ndk/glog/glog/)

find_package (glog 0.3.5 REQUIRED)
...
target_link_libraries(
...
glog::glog
)
```
but it cannot find the cmake:
```
Could not find a package configuration file provided by "glog" (requested
  version 0.3.5) with any of the following names:

    glogConfig.cmake
    glog-config.cmake

  Add the installation prefix of "glog" to CMAKE_PREFIX_PATH or set
  "glog_DIR" to a directory containing one of the above files.  If "glog"
  provides a separate development package or SDK, be sure it has been
  installed.
```
`glog_DIR` is set above, right...
Also, I noticed the contents of `glog-config.cmake` are
```
@PACKAGE_INIT@

include (CMakeFindDependencyMacro)

@gflags_DEPENDENCY@

include ("${CMAKE_CURRENT_LIST_DIR}/glog-targets.cmake")
```
`gflags_DEPENDENCY` should be `find_dependency (gflags ${gflags_VERSION})`, right?
but what of `PACKAGE_INIT`? I cannot find a value for it.

**Comment by sergiud** [comment]
> Can you specify what exactly is confusing/misleading for you

Pretty much everything. I'm trying to parse how are failures in building folly related to glog in the first place.

Also: please read the documentation on how to build glog. It looks like you are still ignoring it.

> Also, I noticed the contents of `glog-config.cmake` are

This is also incorrect; what you posted are the contents of `glog-config.cmake.in`.

You also use a very old version of glog. Make sure to update to the latest one before submitting an issue.

**Comment by karol-bisztyga** [comment]
Ok I got this working.

> I'm trying to parse how are failures in building folly related to glog in the first place.

Folly uses glog([example](https://github.com/facebook/folly/blob/df9437f96dd66a23e1f5f0efdca48b2266afc3bd/folly/File.cpp#L29)).

Thank you for all the tips! Sorry if I missed anything on the way!
