### ISSUE TITLE
MacOS compilation error

### ISSUE THREAD

**Issue by BigBaiNB** [google/glog#657]
![image](https://user-images.githubusercontent.com/40379787/119434577-0e986f80-bd4b-11eb-9109-7efa3a8a5b87.png)

**Comment by BigBaiNB** [comment]
I'm running on MacOs and the above error occurred

**Comment by sergiud** [comment]
Does this happen with the release version as well?

**Comment by BigBaiNB** [comment]
> Does this happen with the release version as well?

yes , it's the latest code base

**Comment by DarrenIm** [comment]
Same here.

**Comment by uuuuu-diwu** [comment]
Add set(CMAKE_CXX_STANDARD 17) to solve this problem
