### ISSUE TITLE
InitGoogleLogging() is not initialized?

### ISSUE THREAD

**Issue by markany-swma** [google/glog#673]
1. I compiled the glog library by static with POD
2. Link to liba.a
3. Link lib.a to multiple shared libraries libfoo.so, libbar.so
4. Link libfoo.so, libbar.so to executable binary baz (call InitGoogleLogging() at baz's main())
5. Execute baz, "WARNING: Logging before InitGoogleLogging() is written to STDERR"

Every codes in libfoo.so, libbar.so are executed after InitGoogleLogging(). But I compiled the glog to shared, solved this problem.

Why glog is not initialize correctly when it compiled by static library?

**Comment by sergiud** [comment]
This is how static libraries work; they do not share the global state opposed to *shared* libraries.
