### ISSUE TITLE
Glog error in Xcode: Implicit instantiation of undefined template 'std::string'

### ISSUE THREAD

**Issue by sleaper** [google/glog#690]
Hi,
I'm trying to build React native app on iOS simulator with Xcode 13. When I try to build app (from Xcode) I got a lot of errors:

<img width="523" alt="Screenshot 2021-07-22 at 18 59 54" src="https://user-images.githubusercontent.com/19505081/126678868-4c574f67-4e65-4036-ad39-9fc452092214.png">

When I try to start app with `npx react-native run-ios`, it throws same errors in console.

I know that I gave you minimal info, but I have no idea what it is and what it means.
Feel free to ask any questions.

Thank you very much

**Comment by sergiud** [comment]
Please provide a minimal working example that demonstrates the problem.

**Comment by sleaper** [comment]
> Please provide a minimal working example that demonstrates the problem.

Iam not sure what do you mean by working example. I just press the build button in Xcode. Maybe you want to see Pod files? Or should I post this problem on stackOverflow?

**Comment by sergiud** [comment]
I'm neither familiar with Xcode nor do I know what Pod files are.

Unless you are willing to provide a complete example that shows a problem with the library, there's not much we can do.
