### ISSUE TITLE
Use glog loop record in the for loop, the final record is incomplete

### ISSUE THREAD

**Issue by MisterYan** [google/glog#691]
When i use glog loop record in the for loop,i found the final record is incomplete. Like this sample:
```cpp
#include <glog/logging.h>
#include <iostream>
int main(int argc, char* argv[ ]){
    google::InitGoogleLogging(argv[0]);
    FLAGS_log_dir = "./log";
    for(int count = 0;count < 150;count++)
    {
        LOG(INFO) << "count = " << count;
        std::cout << "count = " << count << std::endl;
    }
    return 0;
}
```
When the program is finished, you just can see "count = 146 " in the log file，But you can see the output  "count = 149" in the terminal. The log file missing three records.

**Comment by sergiud** [comment]
I cannot reproduce. Neither using the 0.5.0 release nor current master (370cb741bb060614ff41920b8bb1983349d2619d).

Since open files are flushed when they are closed, this indicates that your program does not exit properly.

Please provide the full output of the test application. Also: what platform are you on?

**Comment by MisterYan** [comment]
> I cannot reproduce. Neither using the 0.5.0 release nor current master ([370cb74](https://github.com/google/glog/commit/370cb741bb060614ff41920b8bb1983349d2619d)).
> 
> Since open files are flushed when they are closed, this indicates that your program does not exit properly.
> 
> Please provide the full output of the test application. Also: what platform are you on?

Thank you for attention. Just now, i found the reason for this problem, it's has a special relationship with the screen ratio of my computer when full screen display. I  noticed that when i used gedit text editor open the log file and full screen display in my computer, the last few lines always cannot be displayed. But when i reduce the display window and scroll to the bottom, i could see complete log content. By the way,my computer system is Ubuntu 20.04.2 LTS and the screen ratio is 16:9.

**Comment by MisterYan** [comment]
> I cannot reproduce. Neither using the 0.5.0 release nor current master ([370cb74](https://github.com/google/glog/commit/370cb741bb060614ff41920b8bb1983349d2619d)).
> 
> Since open files are flushed when they are closed, this indicates that your program does not exit properly.
> 
> Please provide the full output of the test application. Also: what platform are you on?
