### ISSUE TITLE
React Native and Mediapipe ios framework problem

### ISSUE THREAD

**Issue by robert-go** [google/glog#692]
I created a MediaPipe ios framework
And I'm trying to integrate it into a React Native project
But the app crash in Mutex::Lock() without any information
I believe the reason is my framework and RN both use `glog`
How can I disable `glog` for one of them ? or any idea to fix it
Thanks for reading
![Screen Shot 2021-07-25 at 09 46 42](https://user-images.githubusercontent.com/64536259/126886085-d9d46993-9d4e-4322-8af2-093f9205094f.png)

**Comment by sergiud** [comment]
You can't disable glog selectively. Your use case also would not warrant such a feature. You're better advised finding the root cause for failing POSIX threads functionality.
