### ISSUE TITLE
Custom log destinations

### ISSUE THREAD

**Issue by manushawijekoon** [google/glog#693]
Is it possible to add custom log destinations? For example, say there is a need to route all logs to Apache Kafka or a memory mapped file? This type of functionality is supported in log4j2 (java) for example.

**Comment by sergiud** [comment]
You could define a custom sink:
https://github.com/google/glog/blob/f8c8e99fdfb998c2ba96cfb470decccf418f0b30/src/glog/logging.h.in#L624-L641

**Comment by manushawijekoon** [comment]
Thanks. Does this mean the log is also written to the usual destination (say file) in addition to the custom log sink?

**Comment by sergiud** [comment]
I would assume so unless you use `LOG_TO_SINK_BUT_NOT_TO_LOGFILE`.

**Comment by manushawijekoon** [comment]
Cheers! This will work for me.
