### ISSUE TITLE
Is there any benchmark on glog?

### ISSUE THREAD

**Issue by willkk** [google/glog#698]
Is there any benchmark data on glog？I log my program using glog, but it seems that many lines of logs are lost. So I want to know if I hit the glog's perfermance limit or I use it the wrong way.

**Comment by sergiud** [comment]
Please provide an example demonstrating the problem. A benchmark is not helpful here.

**Comment by willkk** [comment]
Forget it. I tcpdumped my program, and the face it that my client tool did't send as many requests as expected.
