### ISSUE TITLE
Console logging: separation of stdout and stderr

### ISSUE THREAD

**Issue by kishorenc** [google/glog#701]
For console logging, it seems like there is no way to configure Glog to send non-error logs to `stdout` and error logs to `stderr`. 

By default, Glog sends only error logs to stderr, and there is a `FLAGS_logtostderr` which sends ALL logs to `stderr` which is not ideal.  It will be good to have a flag to log to _both_ stdout and stderr appropriately.

**Comment by git-hulk** [comment]
@sergiud I would like to have a try. For the design, I don't think we should send non-error logs to stdout when FLAGS_logtostderr was enabled, which would have the breaking change. Do you think we should add another flag to like `logtostdout` to achieve this feature.

**Comment by git-hulk** [comment]
https://github.com/KvrocksLabs/kvrocks/issues/478 Kvrocks also wants to log to the stdout which is using glog.

**Comment by sergiud** [comment]
Having `logtostdout` sounds reasonable. Go ahead!

**Comment by git-hulk** [comment]
cool, thanks.

**Comment by jstiefel** [comment]
As explained in `logging.cc`, setting the flag `logtostdout` to `True` should direct the log messages to stdout instead of logfiles. However, this is definitely not the case for me. I still get the `INFO` in the logfiles. `logtostderr` behaves in the same way. This is quite confusing, since there is a `alsologtostderr` flag which describes this behaviour. To be consistent, wouldn't it make sense to have a `alsologtostdout` flag, provided that the previous flag doesn't write to the log?

And how does `logtostdout` interact with `stderrthreshold`. If I understand correctly, `stderrthreshold` directs INFO and WARNING to stderr, if I set it to 0. What happens if I set `logtostdout` at the same time?

**Comment by git-hulk** [comment]
>  To be consistent, wouldn't it make sense to have a alsologtostdout flag, provided that the previous flag doesn't write to the log?

@sergiud I will be happy to do this if you think it makes sense. 

> And how does logtostdout interact with stderrthreshold. If I understand correctly, stderrthreshold directs INFO and WARNING to stderr, if I set it to 0.

You're right that it will send all logs to stderr if set to 0 and `logtostdout` is enabled.

**Comment by jstiefel** [comment]
> @sergiud I will be happy to do this if you think it makes sense.

However, I'm not sure how intended behavior should be. During my testing today, both `logtostderr` and `alsologtostderr` did the same, i.e. output to log files and stderr. And so did `logtostdout`. (glog v0.6.0) And this doesn't seem to correspond to the documentation.

**Comment by git-hulk** [comment]
@jstiefel What's your expected behavior and what you got?

**Comment by jstiefel** [comment]
> @jstiefel What's your expected behavior and what you got?

`logtostderr`, `alsologtostderr`, as well as `logtostdout` forwarded messages to my terminal as desired. However, they still created entries in the logfile. This is not consistent with the documentation: 

https://github.com/google/glog/blob/05fbc65278db1aa545ca5cb743c31bc717a48d0f/src/logging.cc#L120

(I didn't set any other flags while trying.)

**Comment by git-hulk** [comment]
Ummm... I tried on my side but it won't send logs to the logfile if one of FLAGS_logtostdout and FLAGS_logtostderr is enabled.

**Comment by jstiefel** [comment]
My mistake, I just realized that these flags keep persisting if I don't overwrite them. So no logfiles created now. I think it would be useful to have the `alsologtostdout` option as well.

**Comment by git-hulk** [comment]
@sergiud Does this sound good? if yes, i will go ahead to handle this.

**Comment by kishorenc** [comment]
Found an issue related to this flag: https://github.com/google/glog/issues/943
