### ISSUE TITLE
Unprotected VLOG(4) statement in SendEmailInternal

### ISSUE THREAD

**Issue by jmcclellen** [google/glog#704]
There is a VLOG(4) << "Mailing command: " in SendEmailnternal that is not protected by the 'use_logging' condition.

This leads to application being blocked when an email message is attempting to be sent, and the application is running with --v=4 or higher.

**Comment by sergiud** [comment]
Do you mean here?
https://github.com/google/glog/blob/b79e18b78b7ffad059a58e5e1448373cfa94d206/src/logging.cc#L2170
