### ISSUE TITLE
LOG_FIRST_N and similar macros may fail to compile after case label

### ISSUE THREAD

**Issue by eelstork** [google/glog#72]
Since a `case`  label does not imply a new scope, compilers may emit an error ([example](https://github.com/BVLC/caffe/pull/3365)) when LOG_FIRST_N and similar macros are used after ` case` inside a `switch`  statement.
I am suggesting a fix, see #71.

**Comment by ukai** [comment]
write LOG_FIRST_N in block like

```c
  case:
    {
       LOG_FIRST_N(INFO, 20) << "...";
    }
```
