### ISSUE TITLE
Two tests are failing upon turning ON "WITH_CUSTOM_PREFIX"

### ISSUE THREAD

**Issue by vijaythreadtemp** [google/glog#725]
I was trying to test [Custom prefix](https://github.com/google/glog#custom-log-prefix-format ) . Upon setting "WITH_CUSTOM_PREFIX" ON in "CMakeLists.txt:44", I'm seeing following failures.
          1 - logging_custom_prefix (Child aborted)
          3 - logging (Child aborted). 

I'm new to this repo. Can anyone explain what's going on?

**Comment by vijaythreadtemp** [comment]
Hi, 

I'm using the current master. 

Please find the following  output.

**> cmake -S . -B build -G "Unix Makefiles"** 
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find GTest (missing: GTest_DIR)
CMake Warning at CMakeLists.txt:86 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" (requested
  version 2.2.0) with any of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find Unwind (missing: Unwind_INCLUDE_DIR Unwind_LIBRARY Unwind_PLATFORM_LIBRARY)
-- Looking for C++ include unwind.h
-- Looking for C++ include unwind.h - found
-- Looking for C++ include dlfcn.h
-- Looking for C++ include dlfcn.h - found
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
-- Looking for C++ include glob.h
-- Looking for C++ include glob.h - found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - found
-- Looking for C++ include memory.h
-- Looking for C++ include memory.h - found
-- Looking for C++ include pwd.h
-- Looking for C++ include pwd.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include strings.h
-- Looking for C++ include strings.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include sys/syscall.h
-- Looking for C++ include sys/syscall.h - found
-- Looking for C++ include sys/time.h
-- Looking for C++ include sys/time.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include sys/utsname.h
-- Looking for C++ include sys/utsname.h - found
-- Looking for C++ include sys/wait.h
-- Looking for C++ include sys/wait.h - found
-- Looking for C++ include syscall.h
-- Looking for C++ include syscall.h - found
-- Looking for C++ include syslog.h
-- Looking for C++ include syslog.h - found
-- Looking for C++ include ucontext.h
-- Looking for C++ include ucontext.h - found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include ext/hash_map
-- Looking for C++ include ext/hash_map - found
-- Looking for C++ include ext/hash_set
-- Looking for C++ include ext/hash_set - found
-- Looking for C++ include ext/slist
-- Looking for C++ include ext/slist - found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Looking for C++ include tr1/unordered_set
-- Looking for C++ include tr1/unordered_set - found
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - found
-- Looking for C++ include unordered_set
-- Looking for C++ include unordered_set - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of unsigned __int16
-- Check size of unsigned __int16 - failed
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Looking for dladdr
-- Looking for dladdr - not found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for pread
-- Looking for pread - found
-- Looking for pwrite
-- Looking for pwrite - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Performing Test HAVE_NO_DEPRECATED
-- Performing Test HAVE_NO_DEPRECATED - Success
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Looking for pthread_threadid_np
-- Looking for pthread_threadid_np - not found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for UnDecorateSymbolName in dbghelp
-- Looking for UnDecorateSymbolName in dbghelp - not found
-- Performing Test HAVE___ATTRIBUTE__
-- Performing Test HAVE___ATTRIBUTE__ - Success
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_DEFAULT
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_DEFAULT - Success
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_HIDDEN
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_HIDDEN - Success
-- Performing Test HAVE___BUILTIN_EXPECT
-- Performing Test HAVE___BUILTIN_EXPECT - Success
-- Performing Test HAVE___SYNC_VAL_COMPARE_AND_SWAP
-- Performing Test HAVE___SYNC_VAL_COMPARE_AND_SWAP - Success
-- Performing Test HAVE_RWLOCK
-- Performing Test HAVE_RWLOCK - Success
-- Performing Test HAVE___DECLSPEC
-- Performing Test HAVE___DECLSPEC - Failed
-- Performing Test STL_NO_NAMESPACE
-- Performing Test STL_NO_NAMESPACE - Failed
-- Performing Test STL_STD_NAMESPACE
-- Performing Test STL_STD_NAMESPACE - Success
-- Performing Test HAVE_USING_OPERATOR
-- Performing Test HAVE_USING_OPERATOR - Success
-- Performing Test HAVE_NAMESPACES
-- Performing Test HAVE_NAMESPACES - Success
-- Performing Test HAVE_GCC_TLS
-- Performing Test HAVE_GCC_TLS - Success
-- Performing Test HAVE_MSVC_TLS
-- Performing Test HAVE_MSVC_TLS - Failed
-- Performing Test HAVE_CXX11_TLS
-- Performing Test HAVE_CXX11_TLS - Success
-- Performing Test HAVE_ALIGNED_STORAGE
-- Performing Test HAVE_ALIGNED_STORAGE - Success
-- Performing Test HAVE_CXX11_ATOMIC
-- Performing Test HAVE_CXX11_ATOMIC - Success
-- Performing Test HAVE_CXX11_CONSTEXPR
-- Performing Test HAVE_CXX11_CONSTEXPR - Success
-- Performing Test HAVE_CXX11_CHRONO
-- Performing Test HAVE_CXX11_CHRONO - Success
-- Performing Test HAVE_CXX11_NULLPTR_T
-- Performing Test HAVE_CXX11_NULLPTR_T - Success
-- Performing Test HAVE_LOCALTIME_R
-- Performing Test HAVE_LOCALTIME_R - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/d/Learning/git/Google/glog/build

**> cmake --build build**
Scanning dependencies of target glogbase
[  4%] Building CXX object CMakeFiles/glogbase.dir/src/demangle.cc.o
[  8%] Building CXX object CMakeFiles/glogbase.dir/src/logging.cc.o
[ 12%] Building CXX object CMakeFiles/glogbase.dir/src/raw_logging.cc.o
[ 16%] Building CXX object CMakeFiles/glogbase.dir/src/symbolize.cc.o
[ 20%] Building CXX object CMakeFiles/glogbase.dir/src/utilities.cc.o
[ 24%] Building CXX object CMakeFiles/glogbase.dir/src/vlog_is_on.cc.o
[ 28%] Building CXX object CMakeFiles/glogbase.dir/src/signalhandler.cc.o
[ 28%] Built target glogbase
Scanning dependencies of target glogtest
[ 32%] Linking CXX static library libglogtest.a
[ 32%] Built target glogtest
Scanning dependencies of target signalhandler_unittest
[ 36%] Building CXX object CMakeFiles/signalhandler_unittest.dir/src/signalhandler_unittest.cc.o
[ 40%] Linking CXX executable signalhandler_unittest
[ 40%] Built target signalhandler_unittest
Scanning dependencies of target utilities_unittest
[ 44%] Building CXX object CMakeFiles/utilities_unittest.dir/src/utilities_unittest.cc.o
[ 48%] Linking CXX executable utilities_unittest
[ 48%] Built target utilities_unittest
Scanning dependencies of target demangle_unittest
[ 52%] Building CXX object CMakeFiles/demangle_unittest.dir/src/demangle_unittest.cc.o
[ 56%] Linking CXX executable demangle_unittest
[ 56%] Built target demangle_unittest
Scanning dependencies of target symbolize_unittest
[ 60%] Building CXX object CMakeFiles/symbolize_unittest.dir/src/symbolize_unittest.cc.o
[ 64%] Linking CXX executable symbolize_unittest
[ 64%] Built target symbolize_unittest
Scanning dependencies of target logging_custom_prefix_unittest
[ 68%] Building CXX object CMakeFiles/logging_custom_prefix_unittest.dir/src/logging_custom_prefix_unittest.cc.o
[ 72%] Linking CXX executable logging_custom_prefix_unittest
[ 72%] Built target logging_custom_prefix_unittest
Scanning dependencies of target logging_unittest
[ 76%] Building CXX object CMakeFiles/logging_unittest.dir/src/logging_unittest.cc.o
[ 80%] Linking CXX executable logging_unittest
[ 80%] Built target logging_unittest
Scanning dependencies of target stacktrace_unittest
[ 84%] Building CXX object CMakeFiles/stacktrace_unittest.dir/src/stacktrace_unittest.cc.o
[ 88%] Linking CXX executable stacktrace_unittest
[ 88%] Built target stacktrace_unittest
Scanning dependencies of target stl_logging_unittest
[ 92%] Building CXX object CMakeFiles/stl_logging_unittest.dir/src/stl_logging_unittest.cc.o
[ 96%] Linking CXX executable stl_logging_unittest
[ 96%] Built target stl_logging_unittest
Scanning dependencies of target glog
[100%] Linking CXX shared library libglog.so
[100%] Built target glog

**> cmake --build build --target test**
Running tests...
Test project /mnt/d/Learning/git/Google/glog/build
      Start  1: logging_custom_prefix
 1/11 Test  #1: logging_custom_prefix ............Child aborted***Exception:   0.45 sec
      Start  2: demangle
 2/11 Test  #2: demangle .........................   Passed    0.03 sec
      Start  3: logging
 3/11 Test  #3: logging ..........................Child aborted***Exception:   0.40 sec
      Start  4: signalhandler
 4/11 Test  #4: signalhandler ....................   Passed    0.03 sec
      Start  5: stacktrace
 5/11 Test  #5: stacktrace .......................   Passed    0.02 sec
      Start  6: stl_logging
 6/11 Test  #6: stl_logging ......................   Passed    0.03 sec
      Start  7: symbolize
 7/11 Test  #7: symbolize ........................   Passed    0.10 sec
      Start  8: cmake_package_config_init
 8/11 Test  #8: cmake_package_config_init ........   Passed    0.06 sec
      Start  9: cmake_package_config_generate
 9/11 Test  #9: cmake_package_config_generate ....   Passed    2.90 sec
      Start 10: cmake_package_config_build
10/11 Test #10: cmake_package_config_build .......   Passed    2.78 sec
      Start 11: cmake_package_config_cleanup
11/11 Test #11: cmake_package_config_cleanup .....   Passed    0.43 sec

82% tests passed, 2 tests failed out of 11

Total Test time (real) =   7.40 sec

The following tests FAILED:
          1 - logging_custom_prefix (Child aborted)
          3 - logging (Child aborted)
Errors while running CTest
make: *** [Makefile:106: test] Error 8

**Comment by sergiud** [comment]
Thanks for the info.
