### ISSUE TITLE
Support for WASM export

### ISSUE THREAD

**Issue by WenheLI** [google/glog#729]
Hi,
Is there any plan for supporting WASM compile for glog?
I am working on some projects and want to export them to wasm.
One problem I encountered is the glog can not export to WASM.

**Comment by josephrocca** [comment]
@sergiud You can read about web assembly (wasm) [here](https://en.wikipedia.org/wiki/WebAssembly). It's used in web browsers, JS runtimes (e.g. node.js, Deno), and has a few popular purpose-built/standalone runtimes (e.g. Wasmer, wasmtime) that can be used to embed wasm modules in basically all popular languages, and is becoming widely used across the industry. Several popular languages have strong wasm export support, including C and C++ (via [emscripten](https://emscripten.org/)) and [Rust](https://www.rust-lang.org/what/wasm). Some other popular (but garbage-collected) languages are just waiting for wasm-gc proposal to land.

@WenheLI is working on a wasm build of Lyra: https://github.com/google/lyra and one key issue that complicates this is that glog can't export to wasm.

**Comment by sergiud** [comment]
It looks like the Bazel version of glog already builds for WebAssembly. @drigz can probably chime in here.

The question is now what exactly does not work?

**Comment by drigz** [comment]
I think this is a "PR welcome" situation, for Bazel at least. https://github.com/google/glog/pull/546 supposedly fixed the build but didn't add any CI checks, so something could have broken since then. I'm not familiar with the WASM toolchain, but perhaps @WenheLI could dig into it?

**Comment by WenheLI** [comment]
Humm, I see. I will try to build glog into WASM first to see if there is anything broken here.
Thanks for your response.

**Comment by sergiud** [comment]
Let us know once you have more details on what does no work. Closing the issue for now.
