### ISSUE TITLE
Can I disable CHECK in release build?

### ISSUE THREAD

**Issue by kunlinyu** [google/glog#740]
> CHECK aborts the application if a condition is not true. Unlike assert, it is *not* controlled by NDEBUG, so the check will be executed regardless of compilation mode.

Can I disable CHECK in release build, just like assert?

If CHECK is not a replacement of assert, then how should I use it?

My example is :
```cpp
// debug mode:
void check_data(std::shared_ptr<Data> data) {
  CHECK_NOTNULL(data);
  // do something about data
}

// release mode:
void check_data(std::shared_ptr<Data> data) {
  if (data == nullptr) return;
  // do something about data
}
```

I thought CHECK_NOTNULL will just return whatever it get in release build, so i wrote this:
```cpp
void check_data(std::shared_ptr<Data> data) {
  if (CHECK_NOTNULL(data) == nullptr) return;
  // do something about data
}
```

**Comment by kunlinyu** [comment]
Can anybody help me?

**Comment by sergiud** [comment]
Can't you define a custom macro that does the job?

**Comment by sergiud** [comment]
Something along those lines, yes.

**Comment by kunlinyu** [comment]
@sergiud Thank you for your reply!

OK, I understand. Basically, it means: "Glog doesn't handle this. please customize it as your requirements.". Am I correct?

I'm just curious that, in my opinion, ignoring all asserts in release build is a classic practice. Why did Glog choose not to follow it? Does Glog have some concerns?

I use CHECK as a replacement for assert. Is this is the recommended way to use CHECK?

**Comment by sergiud** [comment]
Because glog cannot possibly cover all use cases and customization to your specific needs is straightfoward.

**Comment by kunlinyu** [comment]
@sergiud  Thank you!
