### ISSUE TITLE
How use glog in sdk and new project meanwhile

### ISSUE THREAD

**Issue by oronge** [google/glog#744]
I developed a sdk which log message with glog, meanwhile, I developed a new project which use the previous sdk, also, I want log message with glog too in my new project, and separate log from sdk and new project. How can I achieve this ? 

I tried call InitGoogleLogging() in sdk and new project, but the process core dump with following error message

"You called InitGoogleLogging() twice"

**Comment by sergiud** [comment]
You should call `InitGoogleLogging` in application's entry point (e.g., `main`).

**Comment by oronge** [comment]
> You should call `InitGoogleLogging` in application's entry point (e.g., `main`).

thanks for your reply! 
Buf if the new project doesn't use glog, the main function will not call InitGoogleLogging, then the sdk whill not log messages ?

**Comment by sergiud** [comment]
This is something you must ensure regardless.

**Comment by oronge** [comment]
ok thanks
