### ISSUE TITLE
0.3.5 release date estimate

### ISSUE THREAD

**Issue by theopolis** [google/glog#75]
Any idea when a 0.3.5 can be tagged?

**Comment by jnguyen75** [comment]
+1. It would be nice to have a release that can be built via CMake

**Comment by jakirkham** [comment]
Absolutely, a patch release would be great. 😄

**Comment by mleotta** [comment]
I agree, it would be extremely helpful to have a release that can be built with CMake.  It's been quite a while since the last release.  Can you provide an estimate of when the next release might happen?

👍

**Comment by jakirkham** [comment]
Really any release would be good at this point. Any ideas when that might happen?
