### ISSUE TITLE
[Docs] Possible outdated documentation

### ISSUE THREAD

**Issue by wesleytanws** [google/glog#750]
We have identified **`2`** possible instances of outdated documentation:

- [x] [`DGFLAGS_NAMESPACE`](https://github.com/google/glog/blob/921651e97c3892e656287f1cfa923319f0799729/cmake/DetermineGflagsNamespace.cmake#L36) was renamed to [`DGLOG_GFLAGS_NAMESPACE`](https://github.com/google/glog/blob/eec1435d52a922abffa4a193a9d3e5f5781b223e/cmake/DetermineGflagsNamespace.cmake#L36) but the change has not been reflected in the current version of the [Installing Glog on Ubuntu 14.04](https://github.com/google/glog/wiki/Installing-Glog-on-Ubuntu-14.04/aa4fc07826bca7edf4aae57acd53119e515f9963) wiki page

- [x] [`fPIC`](https://github.com/google/glog/blob/921651e97c3892e656287f1cfa923319f0799729/m4/libtool.m4#L3905) was deleted but the change has not been reflected in the current version of the [Installing Glog on Ubuntu 14.04](https://github.com/google/glog/wiki/Installing-Glog-on-Ubuntu-14.04/aa4fc07826bca7edf4aae57acd53119e515f9963) wiki page

#### About
This is part of a research project that aims to automatically detect outdated documentation in GitHub repositories. We are evaluating the validity of our approach by identifying instances of outdated documentation in real-world projects.

We hope that this research will be a step towards keeping documentation up-to-date. If this has been helpful, consider updating the documentation to keep it in sync with the source code. If this has not been helpful, consider updating this issue with an explanation, so that we can improve our approach. Thanks!

**Comment by sergiud** [comment]
Thanks! Those wiki pages are indeed outdated. I've deleted them.
