### ISSUE TITLE
How to build libglog.so.1?

### ISSUE THREAD

**Issue by trzy** [google/glog#755]
Hopefully this is the right venue for this question: I'm building a project (project) that has somehow picked up a dependency on libglog.so.1 in addition to libglog.so.0. I spent some time Googling for libglog.so.1 but couldn't find any information. I installed libglog using "sudo apt-get install libgoogle-glog-dev" but this does not include the library in question. 

I'm on Ubuntu 20.04.3 LTS.

**Comment by aesophor** [comment]
If you clone this repo and build it manually, you should be able to find it.

On my machine, it can be located at: `/usr/local/lib/libglog.so.1` which is a symbolic link to `/usr/local/lib/libglog.so.0.6.0`

```
> pwd; ls -la
/usr/local/lib
total 288K
drwxr-xr-x  3 root root 4.0K Oct 26 12:19 cmake
drwxr-xr-x  2 root root 4.0K Dec  5 19:20 pkgconfig
drwxr-xr-x  4 root root  12K Dec  8 13:47 .
drwxr-xr-x 11 root root 4.0K Jul 24 20:13 ..
-rwxr-xr-x  1 root root 261K Dec  8 13:47 libglog.so.0.6.0
lrwxrwxrwx  1 root root   16 Oct 26 12:19 libglog.so.1 -> libglog.so.0.6.0
lrwxrwxrwx  1 root root   12 Oct 26 12:19 libglog.so -> libglog.so.1
```

**Comment by trzy** [comment]
I found the problem. I had another project in a directory parallel to ceres-solver that also built glog (bring it in as a git submodule) and somehow ceres-solver's cmake scripts found *that* version and built against it. So the fix was adding: -DGLOG_PREFER_EXPORTED_GLOG_CMAKE_CONFIGURATION=FALSE
