### ISSUE TITLE
LogCleaner: Performance benchmark and parallelization

### ISSUE THREAD

**Issue by aesophor** [google/glog#761]
## Overview

Users have reported that enabling log cleaner causes performance degradation (e.g., #702, #753), but no one has really measured its performance penalty (i.e. absolute execution time) until now.

Here's a simple benchmark I've made recently. In addition, I implemented a parallelized version of `LogCleaner::Run()` using pthread.

## Environment

* Platform:
  - Arch Linux
  - CPU: Intel i7-10700 CPU @ 2.90GH (16-core)
  - Memory: 16 GB

## Evaluation

<img width="965" alt="Screen Shot 2021-12-14 at 12 48 45 AM" src="https://user-images.githubusercontent.com/32998585/145853831-e66714ea-99e0-4292-bac5-51a59e493e42.png">

There are two graphs above, please refer to the one on the LHS. The x-axis denotes the amount of threads used, and when x = 1 pthread is not involved, i.e. the current implementation of log cleaner is used. Here's the explanation:
* When there are **100 files** in log directories, the execution time of `LogCleaner::Run()` is **0.157 ms** in avg.
* When there are **1,000 files** in log directories, the execution time of `LogCleaner::Run()` is **1.249 ms** in avg.
* When there are **10,000 files** in log directories, the execution time of `LogCleaner::Run()` is **13.742 ms** in avg.
* When there are **100,000 files** in log directories, the execution time of `LogCleaner::Run()` is **127.586 ms** in avg.

Note:
* The execution time of `LogCleaner::Run()` is measured using glog's CycleClock.
* In the experiment, no `unlink()` is actually performed.
* All filenames in log directories are valid (`IsLogFromCurrentProject()` will return true for all of them).

### Serial Implementation
For every file in log directories, `LogCleaner::Run()` does the following tasks in serial:
* check if the filename matches the format used by glog
* and if yes, check if the last modified timestamp is >= `overdue_days_`

### Parallel Implementation
To parallelize this method, we can first save all filenames into a vector of strings, and then create multiple threads to do the checking in parallel. Suppose we have 16 files and 3 threads, then the workload will be distributed evenly to each thread like this:

| Thread ID | Responsible for i-th file |
| -- | -- |
| 0 (main) | 0, 3, 6, 9, 12, 15 |
| 1 | 1, 4, 7, 10, 13 |
| 2 | 2, 5, 8, 11, 14 |

On the graph above, the one on the RHS shows how much speedup the parallel implementation can achieve when compared to the current serial implementation:
* When there are **< 100 files** in log directories, multithreading can incur unnecessary overhead.
* When there are **>= 1,000 files** in log directories, multithreading can save some time.

## A Fully Working Example

* The parallel implementation is here: aesophor/glog@7d8c591376e8afed56acfffea13e367bdd5d3f57 (`parallel_logcleaner` branch)
  - the original `LogCleaner::Run()` is called `LogCleaner::RunSerial()`
  - the parallel `LogCleaner::Run()` is called `LogCleaner::RunParallel()`
  - [`CycleClock_Now()` is called before and after these functions to measure execution time.](https://github.com/aesophor/glog/blob/7d8c591376e8afed56acfffea13e367bdd5d3f57/src/logging.cc#L1314-L1335)

* https://github.com/aesophor/NYCU-ParallelProgramming-2021Fall/blob/master/final_project/main.cc
  - `generate_files.sh` - generates n logs in a subdirectory called "testdir". example: `./generate_files.sh 1000`
  - `main.cc`, `Makefile` - a program which runs the LogCleaner using n threads. example: `./glog_logcleaner_benchmark 8` 

## Final Remarks

This is a final project of the parallel programming course I've taken, and if the speedup brought by pthread is acceptable, then I'll submit a corresponding PR.

Thanks for reading all of these!

**Comment by sergiud** [comment]
Wow! Thanks for creating this benchmark. This looks great!

Without having looked at your implementation, however, I want to note that an actual parallel cleanup is probably impractical because the most likely bottleneck will be the speed of the storage device (e.g., HDD vs. SSD) and parallel random accesses will only slow down the task. At the same time, the cleanup can be performed in a single thread in a serial manner independently from the logging thread, e.g., by triggering a task in regular intervals or while the process idling. It is clear, that the cleanup will not finish if the process is stopped. However, a cleanup guarantee can be made only while the process is running anyway.

**Comment by aesophor** [comment]
I see. Thank you @sergiud! 😸
