### ISSUE TITLE
Make error Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by jackoftrades** [google/glog#77]
Error on default ./configure && make && make install

g++ -DHAVE_CONFIG_H -I. -I./src  -I./src  -pthread     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -g -O2 -MT src/logging_unittest-logging_unittest.o -MD -MP -MF src/.deps/logging_unittest-logging_unittest.Tpo -c -o src/logging_unittest-logging_unittest.o `test -f 'src/logging_unittest.cc' || echo './'`src/logging_unittest.cc
src/logging_unittest.cc:64:17: error: ‘GFLAGS_NAMESPACE’ is not a namespace-name
 using namespace GFLAGS_NAMESPACE;
                 ^
src/logging_unittest.cc:64:33: error: expected namespace-name before ‘;’ token
 using namespace GFLAGS_NAMESPACE;

**Comment by NoelCarlton** [comment]
how to deal with this trouble? I got the same matter.  `src/logging_unittest.cc:64:17: error: ‘GFLAGS_NAMESPACE’ is not a namespace-name` and `src/logging_unittest.cc:64:33: error: expected namespace-name before ‘;’ token`
