### ISSUE TITLE
how to build libglog.a 

### ISSUE THREAD

**Issue by Cute-Yang** [google/glog#772]
### build static lib on linux
+ I just modify the CMakeLIsts.txt: add a STATIC FLAG on add_library(glog STATIC ),and write a test cc file to run.but got " stack smashing detected" error finally!
+ I just want to know what's the difference between libglog.so and libglogbase.a? And the reason caused  **stack smashing detected**.
+ hope your answer,handsome boy!!!

**Comment by sergiud** [comment]
https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html
