### ISSUE TITLE
Test suite does not fully respect ${TMPDIR}

### ISSUE THREAD

**Issue by Arfrever** [google/glog#793]
Portage, package manager in Gentoo, sets `TMPDIR` environmental variable to per-package-version temporary directory.
E.g. `TMPDIR="/var/tmp/portage/dev-cpp/glog-0.5.0/temp"`

When test suite of Glog is run, it creates e.g. the following files in `${TMPDIR}`:
```
logging_custom_prefix_unittest.ERROR -> logging_custom_prefix_unittest.localhost.portage.log.ERROR.20220218-105043.71
logging_custom_prefix_unittest.INFO -> logging_custom_prefix_unittest.localhost.portage.log.INFO.20220218-105043.71
logging_custom_prefix_unittest.WARNING -> logging_custom_prefix_unittest.localhost.portage.log.WARNING.20220218-105043.71
logging_custom_prefix_unittest.localhost.portage.log.ERROR.20220218-105043.71
logging_custom_prefix_unittest.localhost.portage.log.INFO.20220218-105043.71
logging_custom_prefix_unittest.localhost.portage.log.WARNING.20220218-105043.71
logging_unittest.ERROR -> logging_unittest.localhost.portage.log.ERROR.20220218-105044.76
logging_unittest.INFO -> logging_unittest.localhost.portage.log.INFO.20220218-105044.76
logging_unittest.WARNING -> logging_unittest.localhost.portage.log.WARNING.20220218-105044.76
logging_unittest.localhost.portage.log.ERROR.20220218-105044.76
logging_unittest.localhost.portage.log.INFO.20220218-105044.76
logging_unittest.localhost.portage.log.WARNING.20220218-105044.76
mock-log_unittest.ERROR -> mock-log_unittest.localhost.portage.log.ERROR.20220218-105046.84
mock-log_unittest.INFO -> mock-log_unittest.localhost.portage.log.INFO.20220218-105046.84
mock-log_unittest.WARNING -> mock-log_unittest.localhost.portage.log.WARNING.20220218-105046.84
mock-log_unittest.localhost.portage.log.ERROR.20220218-105046.84
mock-log_unittest.localhost.portage.log.INFO.20220218-105046.84
mock-log_unittest.localhost.portage.log.WARNING.20220218-105046.84
```

However test suite also leaves some files in `/tmp` without respecting `${TMPDIR}`, e.g.:
```
captured.err
logging_custom_prefix_unittest.INFO -> logging_test_basename_two_processes_writing
logging_unittest.INFO -> logging_test_basename_two_processes_writing
symlinkbase.INFO -> logging_test_extension20220218-105045.76specialextension
truncatefile
truncatefile.link -> /tmp/truncatefile
truncatefilecustom
truncatefilecustom.link -> /tmp/truncatefilecustom
```

Current usage of `${TMPDIR}` is e.g. here:
https://github.com/google/glog/blob/b38ed9d08a901d4003b28ce454e74476ba88f67a/src/logging.cc#L2271-L2282

Hardcoded usage of `/tmp` is here:
https://github.com/google/glog/blob/b38ed9d08a901d4003b28ce454e74476ba88f67a/src/googletest.h#L78-L80

**Comment by Izzy1405** [comment]
> Portage, package manager in Gentoo, sets `TMPDIR` environmental variable to per-package-version temporary directory.
> E.g. `TMPDIR="/var/tmp/portage/dev-cpp/glog-0.5.0/temp"`
> 
> When test suite of Glog is run, it creates e.g. the following files in `${TMPDIR}`:
> ```
> logging_custom_prefix_unittest.ERROR -> logging_custom_prefix_unittest.localhost.portage.log.ERROR.20220218-105043.71
> logging_custom_prefix_unittest.INFO -> logging_custom_prefix_unittest.localhost.portage.log.INFO.20220218-105043.71
> logging_custom_prefix_unittest.WARNING -> logging_custom_prefix_unittest.localhost.portage.log.WARNING.20220218-105043.71
> logging_custom_prefix_unittest.localhost.portage.log.ERROR.20220218-105043.71
> logging_custom_prefix_unittest.localhost.portage.log.INFO.20220218-105043.71
> logging_custom_prefix_unittest.localhost.portage.log.WARNING.20220218-105043.71
> logging_unittest.ERROR -> logging_unittest.localhost.portage.log.ERROR.20220218-105044.76
> logging_unittest.INFO -> logging_unittest.localhost.portage.log.INFO.20220218-105044.76
> logging_unittest.WARNING -> logging_unittest.localhost.portage.log.WARNING.20220218-105044.76
> logging_unittest.localhost.portage.log.ERROR.20220218-105044.76
> logging_unittest.localhost.portage.log.INFO.20220218-105044.76
> logging_unittest.localhost.portage.log.WARNING.20220218-105044.76
> mock-log_unittest.ERROR -> mock-log_unittest.localhost.portage.log.ERROR.20220218-105046.84
> mock-log_unittest.INFO -> mock-log_unittest.localhost.portage.log.INFO.20220218-105046.84
> mock-log_unittest.WARNING -> mock-log_unittest.localhost.portage.log.WARNING.20220218-105046.84
> mock-log_unittest.localhost.portage.log.ERROR.20220218-105046.84
> mock-log_unittest.localhost.portage.log.INFO.20220218-105046.84
> mock-log_unittest.localhost.portage.log.WARNING.20220218-105046.84
> ```
> 
> However test suite also leaves some files in `/tmp` without respecting `${TMPDIR}`, e.g.:
> ```
> captured.err
> logging_custom_prefix_unittest.INFO -> logging_test_basename_two_processes_writing
> logging_unittest.INFO -> logging_test_basename_two_processes_writing
> symlinkbase.INFO -> logging_test_extension20220218-105045.76specialextension
> truncatefile
> truncatefile.link -> /tmp/truncatefile
> truncatefilecustom
> truncatefilecustom.link -> /tmp/truncatefilecustom
> ```
> 
> Current usage of `${TMPDIR}` is e.g. here:
> https://github.com/google/glog/blob/b38ed9d08a901d4003b28ce454e74476ba88f67a/src/logging.cc#L2271-L2282
> 
> Hardcoded usage of `/tmp` is here:
> https://github.com/google/glog/blob/b38ed9d08a901d4003b28ce454e74476ba88f67a/src/googletest.h#L78-L80

Portage, package manager in Gentoo, sets TMPDIR environmental variable to per-package-version temporary directory.
E.g. TMPDIR="/var/tmp/portage/dev-cpp/glog-0.5.0/temp"

When test suite of Glog is run, it creates e.g. the following files in ${TMPDIR}:

logging_custom_prefix_unittest.ERROR -> logging_custom_prefix_unittest.localhost.portage.log.ERROR.20220218-105043.71 logging_custom_prefix_unittest.INFO -> logging_custom_prefix_unittest.localhost.portage.log.INFO.20220218-105043.71 logging_custom_prefix_unittest.WARNING -> logging_custom_prefix_unittest.localhost.portage.log.WARNING.20220218-105043.71 logging_custom_prefix_unittest.localhost.portage.log.ERROR.20220218-105043.71 logging_custom_prefix_unittest.localhost.portage.log.INFO.20220218-105043.71 logging_custom_prefix_unittest.localhost.portage.log.WARNING.20220218-105043.71 logging_unittest.ERROR -> logging_unittest.localhost.portage.log.ERROR.20220218-105044.76 logging_unittest.INFO -> logging_unittest.localhost.portage.log.INFO.20220218-105044.76 logging_unittest.WARNING -> logging_unittest.localhost.portage.log.WARNING.20220218-105044.76 logging_unittest.localhost.portage.log.ERROR.20220218-105044.76 logging_unittest.localhost.portage.log.INFO.20220218-105044.76 logging_unittest.localhost.portage.log.WARNING.20220218-105044.76 mock-log_unittest.ERROR -> mock-log_unittest.localhost.portage.log.ERROR.20220218-105046.84 mock-log_unittest.INFO -> mock-log_unittest.localhost.portage.log.INFO.20220218-105046.84 mock-log_unittest.WARNING -> mock-log_unittest.localhost.portage.log.WARNING.20220218-105046.84 mock-log_unittest.localhost.portage.log.ERROR.20220218-105046.84 mock-log_unittest.localhost.portage.log.INFO.20220218-105046.84 mock-log_unittest.localhost.portage.log.WARNING.20220218-105046.84 

However test suite also leaves some files in /tmp without respecting ${TMPDIR}, e.g.:

captured.err logging_custom_prefix_unittest.INFO -> logging_test_basename_two_processes_writing logging_unittest.INFO -> logging_test_basename_two_processes_writing symlinkbase.INFO -> logging_test_extension20220218-105045.76specialextension truncatefile truncatefile.link -> /tmp/truncatefile truncatefilecustom truncatefilecustom.link -> /tmp/truncatefilecustom 

Current usage of ${TMPDIR} is e.g. here:
https://github.com/google/glog/blob/b38ed9d08a901d4003b28ce454e74476ba88f67a/src/logging.cc#L2271-L2282

Hardcoded usage of /tmp is here:
https://github.com/google/glog/blob/b38ed9d08a901d4003b28ce454e74476ba88f67a/src/googletest.h#L78-L80
