### ISSUE TITLE
`COPYING` file refers to a project via invalid URL

### ISSUE THREAD

**Issue by mbrukman** [google/glog#795]
The `COPYING` file contains the following lines:

https://github.com/google/glog/blob/a8e0007e96ff96145022c488e367da10f835c75d/COPYING#L31-L33

However, this URL is a link to Code Search which is no longer functional, so it returns a 404:

 http://www.google.com/codesearch/p?hl=en#dR3YEbitojA/COPYING&q=GetSystemTimeAsFileTime%20license:bsd 

Would it be possible to replace it with a direct URL to the original project?

**Comment by sergiud** [comment]
Thanks. Could you submit a PR with the updated URL?

**Comment by mbrukman** [comment]
@sergiud -- sorry, I don't know what URL that is supposed to point to, otherwise I would have provided an updated URL. The search query is opaque, and as I was not involved in this project early on, I don't know which project this is referring to.

Looks like there's similar text is in the `utilities.cc` file:

https://github.com/google/glog/blob/a8e0007e96ff96145022c488e367da10f835c75d/src/utilities.cc#L203-L204

which says this comes from a file named `os_win32.c`; if we search for that, we find:

* https://android.googlesource.com/platform/external/wpa_supplicant_8/+/refs/heads/lollipop-dev/src/utils/os_win32.c

so maybe the `os_get_time()` function is the source of `gettimeofday` in this repo? Though that's obviously not the original location of that code.

Maybe this is it: https://w1.fi/cgit/hostap/tree/src/utils/os_win32.c#n26 ?

Again, someone more familiar with the history of this project would have to confirm and make the determination; I don't have any insight into this; I just found the above from a little searching and browsing of the code, so it may also be incorrect, as these are just my guesses.
