### ISSUE TITLE
glog should use ThreadSanitizer (TSAN) dynamic annotations

### ISSUE THREAD

**Issue by toddlipcon** [google/glog#80]
Trying to build glog with TSAN ends up causing a bunch of false positives due to probably-benign races. For example, RawLog_SetLastTime operates unprotected on global variables. This is questionable (since 'struct tm' is relatively large) and generates a TSAN warning. Fixing this to use a seqlock, or at least annotating it as benign, would be helpful for those trying to run glog in TSAN builds.

Another example is the thread-unsafe counters for LOG_EVERY_N and similar macros. These need to be annotated as benign.

**Comment by toddlipcon** [comment]
Another example in stacktrace_libunwind-inl.h -- the 'g_now_entering' variable should be stored using a 'Release_Store' at the end of GetStackTrace(...).

Probably many more, so I won't bother listing them all.

I know that Google uses TSAN internally heavily. Does Google have any intention to open source newer versions of glog, or should we assume that any improvements here will have to be done by the external community?

**Comment by toddlipcon** [comment]
One more: there should be an ANNOTATE_BENIGN_RACE on fatal_msg_data_shared to prevent a TSAN warning when multiple threads FATAL at the same time. (or it should be made thread-safe)

**Comment by kennyyu** [comment]
@toddlipcon This PR will mark the LOG_EVERY_N macros as benign races: https://github.com/google/glog/pull/263
