### ISSUE TITLE
Can glog (c++) print line number in its stacktrace?

### ISSUE THREAD

**Issue by yiguolei** [google/glog#806]
Glog could print stacktrace during segment fault. But line number is missed, Could it print line number?

Glog version 0.4.0

*** Aborted at 1647396557 (unix time) try "date -d @1647396557" if you are using GNU date ***
PC: @     0x7fb744c413bd doris::TaskWorkerPool::_create_tablet_worker_thread_callback()
*** SIGSEGV (@0x8) received by PID 9239 (TID 0x7fb6fa572700) from PID 8; stack trace: ***
    @     0x7fb746225bd2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fb741efe270 (unknown)
    @     0x7fb744c413bd doris::TaskWorkerPool::_create_tablet_worker_thread_callback()
    @     0x7fb744778b89 doris::ThreadPool::dispatch_thread()
    @     0x7fb74477217f doris::Thread::supervise_thread()
    @     0x7fb741cb4e25 start_thread
    @     0x7fb741fc135d __clone
    @                0x0 (unknown)

**Comment by sergiud** [comment]
Please see the following issues:
#534
#555
