### ISSUE TITLE
logtostderr is not working

### ISSUE THREAD

**Issue by annelau99** [google/glog#810]
I am using logtostderr=true but it is not working. When I have the readOnlyRootFilesystem: true, I get the error that it is trying to create a logfile. 

This should not be happening right given that I have set logtostderr as true right? 

Thanks!

**Comment by sergiud** [comment]
Please provide a minimal reproducible example including glog version, command line for configuring and compiling glog, and the corresponding outputs.

What is readOnlyRootFilesystem?

**Comment by annelau99** [comment]
I am running the glog version: glog v0.0.0-20160126235308-23def4e6c14b
This is b
Command line: <app name> --logtostderr=true --v=4
The output: log: exiting because of error: log: cannot create log: open /tmp/.... :read-only file system 
readOnlyRootFilesystem is a Kubernetes security setting that Requires that containers must run with a read-only root filesystem (i.e. no writable layer). So it fails when I try to run the app because it is creating a log file. 

Any idea on why the logtostderr is not being picked up?

**Comment by sergiud** [comment]
We need to figure out what version you are actually running. Please provide a release version or a commit hash used in this repository.

**Comment by annelau99** [comment]
Nvm thanks for your help. I think I have inquired about this on the wrong repo.
