### ISSUE TITLE
glog-0.6.0 incorrectly creates symlink libglog.so.1 instead of libglog.so.0

### ISSUE THREAD

**Issue by ayinresh** [google/glog#814]
Im running into the following error:
`Error: package or namespace load failed for 'arrow' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/conda/lib/R/library/arrow/libs/arrow.so':
  libglog.so.0: cannot open shared object file: No such file or directory`

I checked and I'm running with glog-0.6.0-h6f12383_0 from [conda-forge](https://anaconda.org/conda-forge/glog/files).

I inspected the package and it looks like the generated symlink to the shared object is libglog.so.1 which is incorrect considering major version of 0.6.0 is 0. Is there a way to rebuild 0.6.0 to fix this?

**Comment by sergiud** [comment]
We do not maintain conda packages.

**Comment by ayinresh** [comment]
sorry! opened the issue in [conda-forge/glog-feedstock](https://github.com/conda-forge/glog-feedstock/issues/23)

**Comment by sergiud** [comment]
No problem. FYI, the .0 in the .so name **does not** point to the major version of the library but to the .so version. It is likely that you have packages installed that rely a previous version of glog which has been removed by the update.

**Comment by ayinresh** [comment]
I don't know what the official spec for shared object naming is, but this google search gave me [this](https://unix.stackexchange.com/questions/475/how-do-so-shared-object-numbers-work):

> Shared libraries should be versioned according to the following scheme:
> 
> blah.so.X.Y.Z
> where
> 
> X = backwards incompatible ABI release
> Y = backwards compatible ABI release
> Z = Internal changes only - no change to the ABI

**Comment by sergiud** [comment]
Please read the information on the site you linked to very carefully. You are confusing two versioning schemes: build version (major.minor.patch) and API version (single version number). The latter is what you initially complained about.

**Comment by ayinresh** [comment]
I am not entirely clear as to the difference you are referring to, but I don't think it changes anything.

If I have a package that correctly follows semver, then 0.6.0 must not break consumers of 0.5.0. Regardless of how the X in libglog.so.X is determined, X must remain the same between 0.5.0 and 0.6.0. In this case X has changed (from 0 to 1)

Looking at the index.json of arrow-cpp-0.15.1-py36h982ac2c_6, the depends clause correctly defines 
`"glog >=0.4.0,<1.0a0"`.  We would only expect a change from 0 to 1 when a major version bump occurred for glog (allowing breaking backwards compat).

**Comment by jakirkham** [comment]
Actually semver doesn't make that guarantee when the major version is 0. Please see [this point]( https://semver.org/#spec-item-4 ) (quoted below):

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

A separate question is whether glog intends to use semver. This often gets assumed of libraries, but is not always the case.

**Comment by sergiud** [comment]
> I am not entirely clear as to the difference you are referring to, but I don't think it changes anything.

Your understanding is clearly lacking. Any further discussion is pointless as you ignoring basic information that was provided to you. Please continue the discussion with conda package maintainers. Thank you.

**Comment by ayinresh** [comment]
I see - if 0.6.0 is intended to be incompatible with 0.5.0, then that makes sense. However, I do think conda implicitly requires backwards compat between minor versions even if major version is 0, considering that conda included `"glog >=0.4.0,<1.0a0"` and not `"glog >=0.4.0,<0.5.0a0"` in the index.json of the arrow-cpp package.

I picked up this (runtime) break because I re-solve my conda environments often and pulled in this latest version of glog immediately after its release. It's worth noting that any conda package out there built with glog<0.6.0 will break at runtime with glog>=0.6.0

My apologies about my lack of understanding and missing basic information. Not my intention. I appreciate your time and will leave it at this.

**Comment by sergiud** [comment]
glog does not (yet) guarantee ABI compatibility between minor releases. Incompatibilities are indicated by incrementing the .so version which has been done for the 0.6 release. While I'm not familiar with conda, the version range `glog >=0.4.0,<1.0a0` looks far too general which is likely the reason for the breakage you observe.

**Comment by jakirkham** [comment]
Conda can constrain the version as tight as needed. Currently we pin to minor version, which is similar to the example above of `glog >=0.4.0,<0.5.0a0`.

In any event, I don't think there is a `glog` issue here, but instead something not being pinned correctly in another package using `glog`. So it seems best to keep the discussion in the conda-forge issue for now

**Comment by sergiud** [comment]
Thanks for clearing this up @jakirkham.
