### ISSUE TITLE
Can multi modules write log to different files

### ISSUE THREAD

**Issue by nonths** [google/glog#817]
Suppose in my process, it will load two modules: A And B.
In my own process, I want to write logs to file0; 
module A wants to write logs to file1; 
module B wants to write logs to file2.
Can glog support it? Thanks

**Comment by sergiud** [comment]
I don't believe this is possible. What would be the purpose of such per module logging anyway?

**Comment by nonths** [comment]
> That's not meaningful because the modules live in the same process and do not act independently. You generally want to see the exact sequence of events that caused a failure, as an example.

Got it, thanks for your reply
