### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by uuuuu-diwu** [google/glog#823]
glog-0.6.0/src/base/commandlineflags.h:127:16: error: expected constructor, destructor, or type conversion before '(' token
127 |   DEFINE_uint32(name, EnvToUInt("GLOG_" #name, value), meaning)

glog-0.6.0/src/logging.cc:194:1: note: in expansion of macro 'GLOG_DEFINE_uint32'
[ 23%] Building CXX object CMakeFiles/glogbase.dir/src/signalhandler.cc.o
CMakeFiles/glogbase.dir/build.make:94: recipe for target 'CMakeFiles/glogbase.dir/src/logging.cc.o' failed

**Comment by sergiud** [comment]
Please provide a minimal example allowing to reproduce the problem. Additionally OS, compiler version, used libraries and their versions, CMake arguments, full CMake and compiler output.

**Comment by sergiud** [comment]
Closing due to lack of response.

**Comment by zengkui** [comment]
> Please provide a minimal example allowing to reproduce the problem. Additionally OS, compiler version, used libraries and their versions, CMake arguments, full CMake and compiler output.

I met the same compile error. 
OS: centos 
gcc :  4.8.5
cmake : cmake-3.23.1-linux-x86_64
gflags:  2.1.1
full error message with cmd : cmake --build build
[  3%] Building CXX object CMakeFiles/glogbase.dir/src/demangle.cc.o
[  6%] Building CXX object CMakeFiles/glogbase.dir/src/logging.cc.o
In file included from /home/work/glog-0.6.0/src/logging.cc:67:0:
/home/work/glog-0.6.0/src/base/commandlineflags.h:127:16: error: expected constructor, destructor, or type conversion before ‘(’ token
   DEFINE_uint32(name, EnvToUInt("GLOG_" #name, value), meaning)
                ^
/home/work/glog-0.6.0/src/logging.cc:194:1: note: in expansion of macro ‘GLOG_DEFINE_uint32’
 GLOG_DEFINE_uint32(max_log_size, 1800,
 ^
gmake[2]: *** [CMakeFiles/glogbase.dir/src/logging.cc.o] Error 1
gmake[1]: *** [CMakeFiles/glogbase.dir/all] Error 2
gmake: *** [all] Error 2

plus configure info:
cmake -S . -B build -G "Unix Makefiles"
-- The CXX compiler identification is GNU 4.8.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find GTest (missing: GTest_DIR)
-- Looking for gflags namespace
-- Looking for gflags namespace - gflags
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find Unwind (missing: Unwind_INCLUDE_DIR Unwind_LIBRARY)
-- Looking for C++ include unwind.h
-- Looking for C++ include unwind.h - found
-- Looking for _Unwind_Backtrace
-- Looking for _Unwind_Backtrace - found
-- Looking for C++ include dlfcn.h
-- Looking for C++ include dlfcn.h - found
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
-- Looking for C++ include glob.h
-- Looking for C++ include glob.h - found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - found
-- Looking for C++ include memory.h
-- Looking for C++ include memory.h - found
-- Looking for C++ include pwd.h
-- Looking for C++ include pwd.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include strings.h
-- Looking for C++ include strings.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include sys/syscall.h
-- Looking for C++ include sys/syscall.h - found
-- Looking for C++ include sys/time.h
-- Looking for C++ include sys/time.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include sys/utsname.h
-- Looking for C++ include sys/utsname.h - found
-- Looking for C++ include sys/wait.h
-- Looking for C++ include sys/wait.h - found
-- Looking for C++ include syscall.h
-- Looking for C++ include syscall.h - found
-- Looking for C++ include syslog.h
-- Looking for C++ include syslog.h - found
-- Looking for C++ include ucontext.h
-- Looking for C++ include ucontext.h - found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include ext/hash_map
-- Looking for C++ include ext/hash_map - found
-- Looking for C++ include ext/hash_set
-- Looking for C++ include ext/hash_set - found
-- Looking for C++ include ext/slist
-- Looking for C++ include ext/slist - found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Looking for C++ include tr1/unordered_set
-- Looking for C++ include tr1/unordered_set - found
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include unordered_set
-- Looking for C++ include unordered_set - not found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of unsigned __int16
-- Check size of unsigned __int16 - failed
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Looking for dladdr
-- Looking for dladdr - not found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for pread
-- Looking for pread - found
-- Looking for pwrite
-- Looking for pwrite - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Performing Test HAVE_NO_DEPRECATED
-- Performing Test HAVE_NO_DEPRECATED - Success
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Looking for pthread_threadid_np
-- Looking for pthread_threadid_np - not found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for UnDecorateSymbolName in dbghelp
-- Looking for UnDecorateSymbolName in dbghelp - not found
-- Performing Test HAVE___ATTRIBUTE__
-- Performing Test HAVE___ATTRIBUTE__ - Success
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_DEFAULT
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_DEFAULT - Success
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_HIDDEN
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_HIDDEN - Success
-- Performing Test HAVE___BUILTIN_EXPECT
-- Performing Test HAVE___BUILTIN_EXPECT - Success
-- Performing Test HAVE___SYNC_VAL_COMPARE_AND_SWAP
-- Performing Test HAVE___SYNC_VAL_COMPARE_AND_SWAP - Success
-- Performing Test HAVE_RWLOCK
-- Performing Test HAVE_RWLOCK - Success
-- Performing Test HAVE___DECLSPEC
-- Performing Test HAVE___DECLSPEC - Failed
-- Performing Test STL_NO_NAMESPACE
-- Performing Test STL_NO_NAMESPACE - Failed
-- Performing Test STL_STD_NAMESPACE
-- Performing Test STL_STD_NAMESPACE - Success
-- Performing Test HAVE_USING_OPERATOR
-- Performing Test HAVE_USING_OPERATOR - Success
-- Performing Test HAVE_NAMESPACES
-- Performing Test HAVE_NAMESPACES - Success
-- Performing Test HAVE_GCC_TLS
-- Performing Test HAVE_GCC_TLS - Success
-- Performing Test HAVE_MSVC_TLS
-- Performing Test HAVE_MSVC_TLS - Failed
-- Performing Test HAVE_CXX11_TLS
-- Performing Test HAVE_CXX11_TLS - Failed
-- Performing Test HAVE_ALIGNED_STORAGE
-- Performing Test HAVE_ALIGNED_STORAGE - Failed
-- Performing Test HAVE_CXX11_ATOMIC
-- Performing Test HAVE_CXX11_ATOMIC - Failed
-- Performing Test HAVE_CXX11_CONSTEXPR
-- Performing Test HAVE_CXX11_CONSTEXPR - Failed
-- Performing Test HAVE_CXX11_CHRONO
-- Performing Test HAVE_CXX11_CHRONO - Failed
-- Performing Test HAVE_CXX11_NULLPTR_T
-- Performing Test HAVE_CXX11_NULLPTR_T - Failed
-- Performing Test HAVE_LOCALTIME_R
-- Performing Test HAVE_LOCALTIME_R - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/work/glog-0.6.0/build

**Comment by KrisThielemans** [comment]
I have the same problem.
```
[ 21%] Performing update step for 'glog'
[ 22%] Performing configure step for 'glog'
loading initial cache file /slms/inm/research/tools/build_Thinlinc/SIRF-SuperBuild/Release-python3.7/builds/glog/tmp/glog-cache-Release.cmake
-- Could NOT find Unwind (missing: Unwind_INCLUDE_DIR Unwind_LIBRARY)
-- Configuring done
-- Generating done
-- Build files have been written to: /slms/inm/research/tools/build_Thinlinc/SIRF-SuperBuild/Release-python3.7/builds/glog/build
[ 22%] Performing build step for 'glog'
[  3%] Building CXX object CMakeFiles/glogbase.dir/src/logging.cc.o
In file included from /slms/inm/research/tools/build_Thinlinc/SIRF-SuperBuild/Release-python3.7/sources/glog/src/logging.cc:67:
/slms/inm/research/tools/build_Thinlinc/SIRF-SuperBuild/Release-python3.7/sources/glog/src/base/commandlineflags.h:127:16: error: expected constructor, destructor, or type conversion before \u2018(\u2019 token
  127 |   DEFINE_uint32(name, EnvToUInt("GLOG_" #name, value), meaning)
      |                ^
/slms/inm/research/tools/build_Thinlinc/SIRF-SuperBuild/Release-python3.7/sources/glog/src/logging.cc:194:1: note: in expansion of macro \u2018GLOG_DEFINE_uint32\u2019
  194 | GLOG_DEFINE_uint32(max_log_size, 1800,
      | ^~~~~~~~~~~~~~~~~~
make[5]: *** [CMakeFiles/glogbase.dir/build.make:96: CMakeFiles/glogbase.dir/src/logging.cc.o] Error 1
```
CMake found a system installed gflags 2.1.1. This is surprising as glog requires 2.2.2 https://github.com/google/glog/blob/b33e3bad4c46c8a6345525fd822af355e5ef9446/CMakeLists.txt#L82
A similar problem is mentioned  in #951, which was resolved by updating gflags.

Checking `gflags-config-version.cmake` seems to uncover a bug in `gflags` that it actually doesn't check the version at all., so I've created https://github.com/gflags/gflags/issues/358. It seems therefore that `glog` needs to do the `gflag` version checking itself.

Configuring with CMake with `WITH_GFLAGS=OFF` makes the problem disappear

Just in case you want to know, this is a CentOS system with g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), CMake 3.17.3. `make VERBOSE=ON` gives me the full build cmdline
```
/opt/rh/devtoolset-9/root/usr/bin/g++  -DGLOG_CUSTOM_PREFIX_SUPPORT -DGLOG_NO_SYMBOLIZE_DETECTION -DGOOGLE_GLOG_IS_A_DLL -I/slms/inm/research/tools/build_Thinlinc/SIRF-SuperBuild/Release-python3.7/sources/glog/src -I/slms/inm/research/tools/build_Thinlinc/SIRF-SuperBuild/Release-python3.7/builds/glog/build  -O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -o CMakeFiles/glogbase.dir/src/logging.cc.o -c /slms/inm/research/tools/build_Thinlinc/SIRF-SuperBuild/Release-python3.7/sources/glog/src/logging.cc
```

**Comment by sergiud** [comment]
Thanks for looking into this @KrisThielemans! Indeed, I can reproduce the problem.

However, I'm inclined not to perform an additional CMake version check in glog because this gflags issue affects all downstream clients and thus should be fixed in gflags directly.
