### ISSUE TITLE
Please set scope for NOGDI

### ISSUE THREAD

**Issue by Adela0814** [google/glog#825]
When I compile `colmap`, I get this issue:

```
	Line 136: E:\vcpkg\installed\x64-windows\include\FreeImage.h(921): error C2061: syntax error: identifier 'RGBQUAD'
	Line 136: E:\vcpkg\installed\x64-windows\include\FreeImage.h(921): error C2061: syntax error: identifier 'RGBQUAD'
	Line 137: E:\vcpkg\installed\x64-windows\include\FreeImage.h(923): error C2061: syntax error: identifier 'RGBQUAD'
	Line 137: E:\vcpkg\installed\x64-windows\include\FreeImage.h(923): error C2061: syntax error: identifier 'RGBQUAD'
	Line 138: E:\vcpkg\installed\x64-windows\include\FreeImage.h(935): error C2143: syntax error: missing ';' before '*'
        ...
```

I investigated the issue and found that `glog `defines `NOGDI`, which caused the condition not to be met in `wingdi.h` so skipped defining `RGBQUAD`. 

logging.h
```
# ifndef NOGDI
#  define NOGDI
# endif
// To avoid macro definition of min/max.
# ifndef NOMINMAX
#  define NOMINMAX
# endif

```

I would like to be able to scope these macros to avoid affecting sibling dependencies.

**Comment by sergiud** [comment]
The definitions are private to glog and we are free to define these. There are no guarantees that we can give here.

**Comment by Adela0814** [comment]
Thank you for your reply.
But this question still confuses me. `colmap` strongly depends on `glog`, I found that during my debugging `#  define NOGDI` was run. My request is that this macro should be undefined outside of glog, could you please unset this macro to avoid it working outside of `glog `without affecting `glog`.

**Comment by Adela0814** [comment]
Sorry, I made a mistake. This is not in the source file(`logging.h`), but a patch in vcpkg. 
close this issue because it's not a bug.
