### ISSUE TITLE
windows:: glog complie error

### ISSUE THREAD

**Issue by DAVID-Hown** [google/glog#827]
#include <iostream>
#include <vector>
#include <functional>
#include <cmath>
#include <numeric>
#include <opencv2/opencv.hpp>

#include "common/image.h"

using namespace std;
using namespace cv;
using namespace bilibili::bcv;

int main(int argc, char** argv) {
    cv::Mat img;
    const std::string img_path(R"(E:\bilibili\face_analysis\facial_for_c++\test.jpeg)");
    img = cv::imread(img_path);
    if (img.data) {
       std:: cout << "loading image successfully..." << std::endl;
    }
    return EXIT_SUCCESS;
}
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/55193099/170199084-a6d3c72d-2ae6-4385-a467-b3015e6d76e7.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/55193099/170198986-1b2e7d6b-d362-44ab-81ca-785adf56a119.png">

**Comment by sergiud** [comment]
Please refer to the documentation on consuming glog.

**Comment by DAVID-Hown** [comment]
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/55193099/170215272-4ebd7ef7-0d2e-4907-8b20-ec016f049acb.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/55193099/170215352-f0417f04-fbdb-4985-8bc6-271d8e6df1b2.png">
Hello, I have readjusted the code, but the error is still reported

**Comment by sergiud** [comment]
I'm not sure what are you asking. glog seems to be properly configured now.

**Comment by DAVID-Hown** [comment]
Thank you for your reply, now the problem is Gflag, I follow the Setting Flags in the document, but I am in Windows environment, so this command GLOG_logtostderr= 1.\ facial_for_c++.exe is not applicable?
<img width="626" alt="image" src="https://user-images.githubusercontent.com/55193099/170229869-e69366d2-4cbf-48c2-960c-03fd7d0af882.png">

**Comment by sergiud** [comment]
Looks like like it. You need to configure gflags as well.

**Comment by DAVID-Hown** [comment]
int main(int argc, char** argv) {
    google::InitGoogleLogging(argv[0]);
    // FLAGS_alsologtostderr = true;
    return 0;
}
i try it , but failed
