### ISSUE TITLE
Platform not supported by glog for webassembly

### ISSUE THREAD

**Issue by ZhengChai-DM** [google/glog#828]
When I compile the WASM file with Bazel + Emscripten on Linux (ubuntu20.04), I got the error: 
"bazel-out/wasm-opt-ST-95dcf5f511a2/bin/external/com_github_glog/_virtual_includes/glog/glog/platform.h:55:2: error: Platform not supported by glog. Please consider to contribute platform information by submitting a pull request on Github."

Maybe add more support in the platform.h ?

**Comment by sergiud** [comment]
What support is exactly needed?

**Comment by jay80253504** [comment]
I meet the same problem when I compile the WASM file with CMake + Emscripten on Linux (ubuntu18.04). The error is: 

/glog-0.6.0/glog-0.6.0/src/glog/platform.h2:552:: ::55error:  2 ::2 error: :Platform not supported by glog. Please consider to contribute platform information by submitting a pull request on Github

Is there any solution? Thank you.

**Comment by Vertexwahn** [comment]
Same problem for me ;) - need also Emscripten support! Using Emscripten with Bazel.
