### ISSUE TITLE
Link error for static glog library

### ISSUE THREAD

**Issue by wuleistarrocks** [google/glog#833]
I build static glog library with commands below:
`cmake3 -S . -B build -G "Unix Makefiles" -DBUILD_SHARED_LIBS=0 -DBUILD_TESTING=OFF`

the libglog.a generated successfully. But when i link the lib, the ld report error like:

> /bin/ld: starlet_fslib_test: hidden symbol `_ZN6google10LogMessageC1EPKcii' in ../third_party/glog_install/lib64/libglog.a(logging.cc.o) is referenced by DSO

**Comment by sergiud** [comment]
This looks like an error in your setup. You need to properly link against glog.

**Comment by sergiud** [comment]
We need a full reproducer since our CI successfully builds the static version of glog. Also: are you able to build the tests?

**Comment by sergiud** [comment]
Closing due to lack of response.
