### ISSUE TITLE
Pod install error: Compiling react-native Pods/React-jsi  JSIDynamic.cpp    (/ios/Pods/Headers/Public/glog/glog/logging.h:512:1)    510 |    511 | // They need the definitions of integer types. > 512 | #include "glog/log_severity.h"       | ^ import of module 'glog.glog.log_severity' appears within namespace 'google'

### ISSUE THREAD

**Issue by mtaylor769** [google/glog#838]
Getting this issue even though you locked the conversation on the other thread (https://github.com/google/glog/issues/393) and it hasn't been fixed.

**Comment by sergiud** [comment]
Please submit the issue to the project responsible for maintaining PODs. This is the wrong issue tracker. Thank you.
