### ISSUE TITLE
GLOG_drop_log_memory results in excess CPU consumption

### ISSUE THREAD

**Issue by neilconway** [google/glog#84]
Under high log volumes, glog can call `posix_fadvise` hundreds of thousands of times per second due to the `GLOG_drop_log_memory` feature. Either the feature should be disabled by default, or else the implementation should be improved to reduce the number of system calls per second when there is a heavy log write volume.

For more information, see https://issues.apache.org/jira/browse/MESOS-920

**Comment by pixelb** [comment]
Are there any issues with this proposed fix?

**Comment by bmahler** [comment]
Looks like the fix was merged, should this be closed @shinh?
