### ISSUE TITLE
glog fails on Bazel HEAD with Windows+Clang

### ISSUE THREAD

**Issue by Wyverald** [google/glog#840]
See Bazel CI error logs: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2547#0181f780-2a99-4cfc-9f5e-970920b20ca2

The culprit might be this Bazel change: https://github.com/bazelbuild/bazel/pull/15269 (cc @compnerd)

```
C:/b/j4o7rwe7/external/com_github_gflags_gflags/BUILD:18:15: Compiling src/windows_port.cc failed: undeclared inclusion(s) in rule '@com_github_gflags_gflags//:gflags':
--
  | this rule is missing dependency declarations for the following files included by 'src/windows_port.cc':
  | 'C:/Program Files/LLVM/lib/clang/10.0.0/include/vadefs.h'
  | 'C:/Program Files/LLVM/lib/clang/10.0.0/include/stdarg.h'
  | 'C:/Program Files/LLVM/lib/clang/10.0.0/include/stddef.h'
  | 'C:/Program Files/LLVM/lib/clang/10.0.0/include/__stddef_max_align_t.h'
  | 'C:/Program Files/LLVM/lib/clang/10.0.0/include/limits.h'
  | 'C:/Program Files/LLVM/lib/clang/10.0.0/include/inttypes.h'
  | 'C:/Program Files/LLVM/lib/clang/10.0.0/include/stdint.h'
```

**Comment by Wyverald** [comment]
Bazel's LTS policy (https://blog.bazel.build/2020/11/10/long-term-support-release.html) states that new major releases can contain breaking changes. So while this isn't an urgent breakage, it'll eventually be visible to any users of Bazel 6.0+ when it's released later this year.

**Comment by compnerd** [comment]
Interesting; The change itself should allow using a vendored or unvendored clang.  The difference should be just the prefix on the line.  It may be possible that we are mis-parsing the string now, but I don't see how to determine what we processed and what the results were from the buildkite logs.

**Comment by meteorcloudy** [comment]
`DEBUG: C:/src/tmp/3cwdc5ex/external/bazel_tools/tools/cpp/windows_cc_configure.bzl:577:10: "clang version 10.0.0 "`

Turns out there is a space after the version, so `first_line.split(" ")[-1]` doesn't really work 😂
```
    # The first line of stderr should look like "[vendor ]clang version X.X.X"
    if result.return_code != 0 or first_line.find("clang version ") == -1:
        auto_configure_fail("Failed to get clang version by running \"%s -v\"" % clang_cl)
    return first_line.split(" ")[-1]
```

**Comment by meteorcloudy** [comment]
This is a Bazel bug, so feel free to close it.
