### ISSUE TITLE
Does it make sense to log message with JSON format

### ISSUE THREAD

**Issue by git-hulk** [google/glog#842]
### Search before asking

- [X] I had searched in the [issues](https://github.com/google/glog/issues) and found no similar issues.

### Motivation

Currently, more and more applications are running on Kubernetes or docker, and most of them will collect logs with structure format which can make the log processor easier. So Do you think it's
a good idea to support JSON format?

### Solution

Support to specify log format like JSON

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
hello @sergiud, dose this sound good to you?

**Comment by andrea-cassioli-maersk** [comment]
Supporting JSON output would be awesome...

**Comment by sergiud** [comment]
You can implement a custom sink and dump log messages in any format you want. Use case specific sinks are outside of glog's scope.
