### ISSUE TITLE
Possible dangling `else` with DLOG in non-debug mode

### ISSUE THREAD

**Issue by anpol** [google/glog#854]
After #830, the following code starts misbehaving:
```cpp
#define NDEBUG
#include "glog/logging.h"

int main()
{
  if (true)
    DLOG(ERROR) << "Hello";
  else
    LOG(ERROR) << "Bye";
}
```

This code now compiles with a warning, and prints "Bye".

Another possible issue with #830 is that `DLOG` now expands to a statement in non-debug mode, while being an expression in debug mode.

**Comment by sergiud** [comment]
@lstaroth Could please look into the issue?

**Comment by lstaroth** [comment]
@sergiud Sorry for introducing the bug, looks like you need to fall back to the previous version to fix it

**Comment by lstaroth** [comment]
@sergiud Changing to 'while (false) LOG(severity)' will solve this problem but doesn't seem to apply to LOG_IF, so maybe we'll just have to fall back
