### ISSUE TITLE
Cross building glog for Green Hill Integrity on windos

### ISSUE THREAD

**Issue by tianfang-fafafa** [google/glog#856]
hi,
 I installed Green Hill IDE compiler and IntegrityOS using default settings, 
cloned glog repo and cross do_configure via cmake-v3.24 on cmdline of windows, but many include files needed by glog are not found.
Does glog support Green Hill IntegrityOS ? Always glog is used for Linux System.

==========================================================================
C:\ghs\src\glog-master>   cmake -G "Green Hills MULTI" -A arm64 -T c:\ghs\comp_202214 -D GHS_OS_DIR=c:\ghs\int19015 -D GHS_BSP_NAME=platform-zynq-mp  -D BUILD_SHARED_LIBS=ON  -S . -B c:\ghs\build\glogtest  --fresh  --toolchain C:\ghs\toolchain.cmake
==============================================================
my toolchain.cmake:
set(CMAKE_CROSSCOMPILING TRUE)

set ( GHS_BSP_NAME "platform-zynq-mp" )
set ( __ARCH_NAME arm64 )
set ( __BSP_CFG_NAME dbg )
set ( GHS_OS_DIR c:/ghs/int19015 )

set ( CMAKE_FIND_ROOT_PATH c:/ghs/comp_202214/ansi  c:/ghs/comp_202214 )

set( CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
=======================================================================
LOG:
-- The CXX compiler identification is GHS 2022.1.4
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/ghs/comp_202214/cxintarm64.exe - skipped
-- Could NOT find GTest (missing: GTest_DIR)
CMake Warning at CMakeLists.txt:82 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" (requested
  version 2.2.2) with any of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in posix
-- Looking for pthread_create in posix - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Could NOT find Threads (missing: Threads_FOUND)
-- Could NOT find Unwind (missing: Unwind_INCLUDE_DIR Unwind_LIBRARY)
-- Looking for _Unwind_Backtrace
-- Looking for _Unwind_Backtrace - not found
-- Looking for _Unwind_GetIP
-- Looking for _Unwind_GetIP - not found
-- Looking for C++ include dlfcn.h
-- Looking for C++ include dlfcn.h - not found
-- Looking for C++ include glob.h
-- Looking for C++ include glob.h - not found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - not found
-- Looking for C++ include memory.h
-- Looking for C++ include memory.h - not found
-- Looking for C++ include pwd.h
-- Looking for C++ include pwd.h - not found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - not found
-- Looking for C++ include strings.h
-- Looking for C++ include strings.h - not found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - not found
-- Looking for C++ include sys/syscall.h
-- Looking for C++ include sys/syscall.h - not found
-- Looking for C++ include sys/time.h
-- Looking for C++ include sys/time.h - not found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - not found
-- Looking for C++ include sys/utsname.h
-- Looking for C++ include sys/utsname.h - not found
-- Looking for C++ include sys/wait.h
-- Looking for C++ include sys/wait.h - not found
-- Looking for C++ include syscall.h
-- Looking for C++ include syscall.h - not found
-- Looking for C++ include syslog.h
-- Looking for C++ include syslog.h - not found
-- Looking for C++ include ucontext.h
-- Looking for C++ include ucontext.h - not found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - not found
-- Looking for C++ include ext/hash_map
-- Looking for C++ include ext/hash_map - not found
-- Looking for C++ include ext/hash_set
-- Looking for C++ include ext/hash_set - not found
-- Looking for C++ include ext/slist
-- Looking for C++ include ext/slist - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - not found
-- Looking for C++ include tr1/unordered_set
-- Looking for C++ include tr1/unordered_set - not found
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include unordered_set
-- Looking for C++ include unordered_set - not found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - not found
-- Check size of unsigned __int16
-- Check size of unsigned __int16 - failed
-- Check size of mode_t
-- Check size of mode_t - failed
-- Check size of ssize_t
-- Check size of ssize_t - failed
-- Check size of u_int16_t
-- Check size of u_int16_t - failed
-- Check size of uint16_t
-- Check size of uint16_t - failed
-- Looking for dladdr
-- Looking for dladdr - not found
-- Looking for fcntl
-- Looking for fcntl - not found
-- Looking for pread
-- Looking for pread - not found
-- Looking for pwrite
-- Looking for pwrite - not found
-- Looking for sigaction
-- Looking for sigaction - not found
-- Looking for sigaltstack
-- Looking for sigaltstack - not found
-- Looking for backtrace
-- Looking for backtrace - not found
-- Looking for backtrace_symbols
-- Looking for backtrace_symbols - not found
-- Performing Test HAVE_NO_DEPRECATED
-- Performing Test HAVE_NO_DEPRECATED - Failed
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Looking for pthread_threadid_np
-- Looking for pthread_threadid_np - not found

**Comment by sergiud** [comment]
I suggest you ask the CMake folks why this is happening. From a quick glance, I'd say your toolset is broken because it is missing fundamental C headers such as `stddef.h`. Nothing glog can do about it.
