### ISSUE TITLE
please remove generated autotools from the git repo

### ISSUE THREAD

**Issue by vapier** [google/glog#86]
any developer working on live git and not a release tarball should be able to run `autoreconf -fi`.  keeping the files in the tree causes headaches for people.

case in point: i got the tree and ran configure, and then the system wanted to rebuild autotools for me.  after doing so, i'm left with 20 modified files.

also, the `test-driver` script committed to the repo now is incorrectly a symlink.  it should be a real file.

**Comment by ldemailly** [comment]
work around : https://github.com/google/glog/issues/117#issuecomment-228142866

**Comment by ArturKlajnerok** [comment]
`test-driver` script was removed with : https://github.com/google/glog/pull/188
