### ISSUE TITLE
There is a bug in the use of glog by multiple processes

### ISSUE THREAD

**Issue by east-czx** [google/glog#864]
in my project, I used a total of three processes, a, a+1, a+2, and initialized glog in the 'a' process. The a+1 process will call LOG(ERROR) in some specific cases. If no error occurs, there will be no  output. but in the end, in my log dir, LOG.INFO is softly connected to an empty log file, the process number of the log file is a+1, and the name of the log file is wrong, it should be lego_heart, but the name is go_heart.
This happens when I set FLAGS_v = 2
I would be very grateful if you could reply

**Comment by east-czx** [comment]
i find out that if i change the name of process before log anything ,log file will go wrong

**Comment by sergiud** [comment]
Please provide a minimal example that demonstrates the problem.

**Comment by sergiud** [comment]
Closing due to lack of response.
