### ISSUE TITLE
Custom sink example?

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [google/glog#865]
I am considering to use glog instead a lot of custom code, but I cannot se from the docs how to achieve the following:

* user shall select to either log to console or file (not both)
* file should have encoded each line as a JSON, to be then be piped to a logging service.

I see from the code that glog support custom sinks, but I cannot find an example.

**Comment by sergiud** [comment]
The [code and the documentation](https://github.com/google/glog/blob/b70ea80433c2a8f20b832be97b90f1f82b0d29e9/src/glog/logging.h.in#L1750-L1795) is all what we have now.

**Comment by andrea-cassioli-maersk** [comment]
OK, thanks. 

Is there a way to pipe logs only to console or only to file?

**Comment by x10000year** [comment]
I also need this feature. This feature has been requested in #470 .

@sergiud
