### ISSUE TITLE
Stracktrace on Windows

### ISSUE THREAD

**Issue by continue98** [google/glog#867]
Hi. Why does stacktrace work so weird? I'm specifically trying to crash the program, I expect that the stacktrace will have a function: "crashFunction". But she's not there. What could be the problem?

```cxx
void crashFunction()
{
	*(static_cast<unsigned int*>(0)) = 0xDEAD;
}

int main(int argc, char* argv[])
{
	google::InitGoogleLogging("test");
	google::InstallFailureSignalHandler();
	fLS::FLAGS_log_dir = "./logs";
	google::InstallFailureWriter([](auto text, auto size) {
		const std::string str(text, size);
		LOG(ERROR) << str << std::endl;
	});


	crashFunction();
	return 0;
}
```

```log
E20221002 13:16:18.692387 13356 main.cpp:19]     @ 0x7740ce92 _seh_filter_exe
E20221002 13:16:18.696342 13356 main.cpp:19]     @   0x70c140 __scrt_common_main_seh
E20221002 13:16:18.698343 13356 main.cpp:19]     @ 0x75bdfa29 BaseThreadInitThunk
E20221002 13:16:18.700340 13356 main.cpp:19]     @ 0x77aa7b5e RtlGetAppContainerNamedObjectPath
E20221002 13:16:18.700340 13356 main.cpp:19]     @ 0x77aa7b2e RtlGetAppContainerNamedObjectPath
```

P.S: Windows 10, Visual Studio 2022

**Comment by sergiud** [comment]
The function is likely getting inlined. The stack trace is also not generated by glog directly but rather by the `dbghelp` library.

**Comment by continue98** [comment]
@sergiud I tried telling the compiler: don't inline it. But stracktrace is still not what I expect

```cxx
__declspec(noinline) void crashFunction()
{
	*(static_cast<unsigned int*>(0)) = 0xDEAD;
}
```

```log
E20221002 22:51:36.723834  9052 main.cpp:19] *** Aborted at 1664740296 (unix time) try "date -d @1664740296" if you are using GNU date ***
E20221002 22:51:36.728507  9052 main.cpp:19]     @ 0x7740ce92 _seh_filter_exe
E20221002 22:51:36.732504  9052 main.cpp:19]     @   0xc4c140 __scrt_common_main_seh
E20221002 22:51:36.734380  9052 main.cpp:19]     @ 0x75bdfa29 BaseThreadInitThunk
E20221002 22:51:36.736379  9052 main.cpp:19]     @ 0x77aa7b5e RtlGetAppContainerNamedObjectPath
E20221002 22:51:36.736379  9052 main.cpp:19]     @ 0x77aa7b2e RtlGetAppContainerNamedObjectPath
```

**Comment by continue98** [comment]
![изображение](https://user-images.githubusercontent.com/12125634/193473932-be474e7c-43f1-4ac1-a7eb-761d6f582d8a.png)
![изображение](https://user-images.githubusercontent.com/12125634/193473942-2282f43c-aac6-4011-88f9-2cf1db83e2f3.png)
![изображение](https://user-images.githubusercontent.com/12125634/193473944-2c7cc870-7ff2-4721-9dbb-8a1a498bd692.png)

also code listing from ida pro

**Comment by sergiud** [comment]
As previously mentioned, the stack trace comes from `dbghelp`. There isn't much glog can do about the output. My guess is that the debug info does not contain the frames you are expecting.
