### ISSUE TITLE
vcpkg install  not google::LogMessageInfo

### ISSUE THREAD

**Issue by Robin528919** [google/glog#883]
vcpkg install glog  not google::LogMessageInfo
![image](https://user-images.githubusercontent.com/45855146/208110965-dc48d63e-cd53-4caa-b90c-6861938cab16.png)

**Comment by sergiud** [comment]
We do not maintain the vcpkg version of glog.

**Comment by Robin528919** [comment]
![image](https://user-images.githubusercontent.com/45855146/208111268-f80cb4f7-f2bd-482b-be26-e7baea561c5d.png)

**Comment by Robin528919** [comment]
OK, thank you
