### ISSUE TITLE
Insecure API when using in React Native iOS app

### ISSUE THREAD

**Issue by master4-2021** [google/glog#892]
There are some insecure APIs that exists in this repository that Apple considered insecure and recommended not using:
https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1

These are reported when using Mobile Security Framework (https://github.com/MobSF/Mobile-Security-Framework-MobSF) to scan the IPA.

strncpy:

https://github.com/google/glog/blob/6ed0c9e58b11680779c571996a3007bd972e0853/src/symbolize.cc#L658

https://github.com/google/glog/blob/6ed0c9e58b11680779c571996a3007bd972e0853/src/symbolize.cc#L729

https://github.com/google/glog/blob/a34226ca94be8faae363b0599e5c4cdb7767774a/src/demangle.cc#L1344

I understand that the use of these function does not definitely leads to security issues, but I want to bring this to your attention, and check if these are safe to use within our application.

**Comment by sergiud** [comment]
Issue wording almost entirely copy pasted from #889.
