### ISSUE TITLE
LogMessage inheritance

### ISSUE THREAD

**Issue by jcao02** [google/glog#9]
Hi,

I'm implementing a class which inherits from LogMessage, modifies some behavior from it and adds some other. The problem is that a lot of important attributes of LogMessage, such as data_, the Init function and the send functions are private and cannot be accessed from the class I'm trying to implement.

Is it possible to change these attributes from private to protected? 

Thanks

**Comment by ukai** [comment]
I think LogMessage is not expected to be used directly.
LOG or CHECK macro is public interface of glog.
