### ISSUE TITLE
Cmake Integrated the glog dynamic library built by bazel, and the operation crashes

### ISSUE THREAD

**Issue by liuxunfei** [google/glog#908]
When LOG (INFO) is called for printing each time, the log can be output normally, but the interface will crash after running. After LOG (INFO) is annotated, the crash will be eliminated；

storehouse：0x0000000000007080 in ?? ()

**Comment by sergiud** [comment]
It is not clear what the problem is. Please provide an example that demonstrates the issue.

**Comment by sergiud** [comment]
Closing due to lack of response.
