### ISSUE TITLE
Adding a parameter when using glog.lib produces an error

### ISSUE THREAD

**Issue by lichangxin-code** [google/glog#909]
![捕获](https://user-images.githubusercontent.com/73156850/224889920-5b4f9532-ff9e-481a-b972-3b5cd74c6a85.PNG)
If you don't add parameters and just print information, it won't report an error, which is very strange.
glog version 0.5

**Comment by sergiud** [comment]
There's nothing strange about this given you've overridden a glog macro responsible for symbols linkage.

Make sure to take a look at the documentation how to correctly consume glog.
