### ISSUE TITLE
/Zc:__cplusplus: linker input file not found: No such file or directory

### ISSUE THREAD

**Issue by heepengpeng** [google/glog#917]
When I use vcpkg install glog， meet a problem /Zc:__cplusplus: linker input file not found: No such file or directory

**Comment by heepengpeng** [comment]
Problems were encountered while collecting compiler information:
	cc1plus.exe: fatal error: /Zc:__cplusplus: No such file or directory

**Comment by sergiud** [comment]
We do not maintain the vcpkg version of glog. Please submit the issue to the corresponding tracker.
