### ISSUE TITLE
how to succeed logging to the same file from multiple processes

### ISSUE THREAD

**Issue by Huangyong657** [google/glog#918]
I have seen the link https://github.com/google/glog/issues/170
but I do not how to succeed logging to the same file from multiple processes.
 I would like to ask where is the merge and could I change every file's name from every processed  and make files's name to the same one to solve the problem now?
Thanks very much for your help , best wishes!

**Comment by sergiud** [comment]
Logging into the same file from multiple processes does not sound very useful. A possible implementation would inadvertently incur an unconditional runtime overhead due to necessary synchronization. This is something one wants to avoid.
