### ISSUE TITLE
[Linking Error]:  undefined reference to `google::InitGoogleLogging(char const*)'

### ISSUE THREAD

**Issue by chensuo2048** [google/glog#920]
I wrote a demo code:
----------------------------------------------------------------------------------------------------
#include <glog/logging.h>
int main(int argc, char* argv[]){
    google::InitGoogleLogging(argv[0]);
    return 0;
}

The contents of CMakeLists.txt are as follows:
----------------------------------------------------------------------------------------------------
cmake_minimum_required(VERSION 3.16)
project(test)
set(CMAKE_CXX_STANDARD 14)
set(THIRD_PARTY_PATH "${PROJECT_SOURCE_DIR}/third_party")
include_directories(${THIRD_PARTY_PATH}/include)
add_executable(test test.cpp ${THIRD_PARTY_PATH}/lib/libglog.so)

But the following error occurs at compile time:
----------------------------------------------------------------------------------------------------
test.cpp:(.text.startup+0xc): undefined reference to `google::InitGoogleLogging(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test.dir/build.make:97: test] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

outputs of 'nm -CD libglog.so' command:
----------------------------------------------------------------------------------------------------
00000000000157d4 T google::SetStderrLogging(int)
000000000001814a T google::DisableLogCleaner()
000000000001807e T google::InitGoogleLogging(char const*)
000000000001809d T google::InitGoogleLogging(char const*, void (*)(std::ostream&, google::LogMessageInfo const&, void*), void*)
000000000001518b T google::SetLogDestination(int, char const*)
000000000000fe0c T google::GetLogSeverityName(int)

The google::InitGoogleLogging(char const*) exists.

Can someone help me with this？

**Comment by sergiud** [comment]
Please refer to the [documentation](https://github.com/google/glog#consuming-glog-in-a-cmake-project).
