### ISSUE TITLE
Hello, I run `pod install --verbose`. not show error

### ISSUE THREAD

**Issue by megabeehothanhminh** [google/glog#928]
-> Installing glog (0.3.5)  > Git download  > Git download      $ /opt/homebrew/bin/git clone https://github.com/google/glog.git      /var/folders/dl/kh3bh2wn39j3d11ptk4x_z640000gn/T/d20230604-2657-4f8z21 --template= --single-branch --depth 1      --branch v0.3.5      Cloning into '/var/folders/dl/kh3bh2wn39j3d11ptk4x_z640000gn/T/d20230604-2657-4f8z21'...

**Comment by megabeehothanhminh** [comment]
npx react-native info 

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 126.03 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/lib/ruby/gems/3.2.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-22 | Google APIs ARM 64 v8a, android-23 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM 64 v8a, android-26 | Google APIs ARM 64 v8a, android-28 | Google APIs ARM 64 v8a, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by sergiud** [comment]
We do not support pod. Please report the problem to the corresponding issue tracker.
