### ISSUE TITLE
Some question about LogMessageTime

### ISSUE THREAD

**Issue by 4kangjc** [google/glog#936]
Hi! I have a few questions about LogMessage.
https://github.com/google/glog/blob/3a0d4d22c5ae0b9a2216988411cfa6bf860cc372/src/glog/logging.h.in#L103-L120
1. Why don't these member functions return int  directly ?
2. Why does the `LogMessage::min`(Line 111) have one more parenthesis than other member functions ?
Thanks.

**Comment by sergiud** [comment]
What issue are you trying to solve?

**Comment by 4kangjc** [comment]
> What issue are you trying to solve?

nothing, just some questions in the process of reading the code.

**Comment by 4kangjc** [comment]
> > What issue are you trying to solve?
> 
> nothing, just some questions in the process of reading the code.

I just think int and int32_t are basic types, there is no need for reference.

**Comment by sergiud** [comment]
This is an issue tracker not a Q&A site. Unless you want to discuss specific code issues and demonstrate the problem that requires genuine attention, your questions are better suited elsewhere. Thanks.
