### ISSUE TITLE
Optimization of LogMessageTime::CalcGmtOffset 

### ISSUE THREAD

**Issue by pabitra-nayak** [google/glog#941]
Hi,

I was doing code profiling of our application and found that "google::LogMessageTime::CalcGmtOffset" function is taking close to 15% of total application time. This is after minimizing logging wherever possible. I thought I should post here in case this had been already observed and addressed before. Any help on this would be greatly appreciated.

My apologies in case there is a separate forum to report this kind of issue which I am not aware of.

Thanks,
Pabitra

**Comment by sergiud** [comment]
How does 15% translate into absolute times (e.g., average)? Using what operating system and compiler do you observe the behavior? Did you compile glog with optimizations? If so, which ones?

Please provide more information otherwise it is just guesswork at this point.

**Comment by pabitra-nayak** [comment]
@sergiud Appreciate your help on this. 

I did a load testing of our application for 3 minutes, so this 15% is CPU consumption for that period. I am using gcc(g++) 11 with C++20 on Red Hat Enterprise Linux 8. Yes, I turned on optimization while building glog library, the compiler flags while building the same are as below:
"-O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=gnu++20"

**Comment by sergiud** [comment]
You lost me now. First you mentioned

> 15% of total application time

but then

> 15% is CPU consumption

So which one is it? Would you please share your exact profiling findings including absolute times related to the `CalcGmtOffset` performance.

**Comment by sergiud** [comment]
Let us know once you can provide the details.
