### ISSUE TITLE
How to output strack trace to file async signal safely?

### ISSUE THREAD

**Issue by komgcn** [google/glog#950]
I have seen example online such as:
```cpp
google::InstallFailureWriter([](cosnt char* data, int size){
    std::string str = std::string(data,size);
    LOG(ERROR) << str;
});
```
which I think it's not async signal safe. This function seems to be called inside signal handling function. Is it possible to implement it in a asynal signal safe way?

**Comment by sergiud** [comment]
What would be a signal safe approach?

**Comment by sergiud** [comment]
I'm closing the issue due to lack of response. Please let us know once you have more information.

**Comment by komgcn** [comment]
I think both`std::string str = std::string(data,size);` and `LOG(ERROR) << str;` are not signal safe because they will call functions like malloc/mmap, according to the [signal-safety linux manpage](https://man7.org/linux/man-pages/man7/signal-safety.7.html).
Indeed my question is if my program breaks, and I would like to see the strace/stack/coredump content in my log file, how should I write this function properly? What would be a signal safe approach?
