### ISSUE TITLE
v0.5.0 build success, but v0.6.0 failed with weird error

### ISSUE THREAD

**Issue by ChanCody** [google/glog#951]
os: Ubuntu16.04
gcc/g++: 5.4.0
cmake: 3.16.2

v0.5.0 can be build successfully, but v0.6.0 building failed with lots of error lilke:

```console
/home/chan/download/glog/src/mock-log.h:90:3: error: template argument 1 is invalid
   MOCK_METHOD3(Log, void(GOOGLE_NAMESPACE::LogSeverity severity,
   ^
/home/chan/download/glog/src/mock-log.h:90:3: error: expected ‘,’ or ‘...’ before ‘>’ token
   MOCK_METHOD3(Log, void(GOOGLE_NAMESPACE::LogSeverity severity,
   ^
In file included from /home/chan/anaconda3/include/gmock/gmock.h:62:0,
                 from /home/chan/download/glog/src/logging_unittest.cc:71:
/home/chan/anaconda3/include/gmock/gmock-more-actions.h: In constructor ‘testing::SaveArgPointeeActionP<k, pointer_type>::SaveArgPointeeActionP(pointer_type)’:
/home/chan/anaconda3/include/gmock/gmock-more-actions.h:93:1: error: ‘move’ is not a member of ‘std’
 ACTION_TEMPLATE(SaveArgPointee,
 ^
/home/chan/anaconda3/include/gmock/gmock-more-actions.h: In constructor ‘testing::SaveArgPointeeActionP<k, pointer_type>::gmock_Impl<F>::gmock_Impl(pointer_type)’:
/home/chan/anaconda3/include/gmock/gmock-more-actions.h:93:1: error: ‘move’ is not a member of ‘std’
 ACTION_TEMPLATE(SaveArgPointee,
 ^
```

I've tried to deactivate conda env, but the error still occurs.

Appriciate for any help!

**Comment by sergiud** [comment]
It looks like your gmock version is expecting C++11 or later support enabled but the corresponding compiler options were not supplied. The issue itself is in gmock not glog since version 0.6 does not require newer language standard to be enabled.

As a workaround you can disable `WITH_GMOCK` CMake option or pass `-std=c++11` to the compiler.

**Comment by ChanCody** [comment]
Thanks for your reply @sergiud. Sorry for my mistake.
I tried to remove the build folder and rebuild glog without conda activated, and the error changed:

> [ 22%] Building CXX object CMakeFiles/glogbase.dir/src/signalhandler.cc.o
> In file included from /home/chan/download/glog/src/logging.cc:67:0:
> /home/chan/download/glog/src/base/commandlineflags.h:127:16: error: expected constructor, destructor, or type conversion before ‘(’ token
>    DEFINE_uint32(name, EnvToUInt("GLOG_" #name, value), meaning)
>                 ^
> /home/chan/download/glog/src/logging.cc:194:1: note: in expansion of macro ‘GLOG_DEFINE_uint32’
>  GLOG_DEFINE_uint32(max_log_size, 1800,
>  ^
> CMakeFiles/glogbase.dir/build.make:75: recipe for target 'CMakeFiles/glogbase.dir/src/logging.cc.o' failed
> make[2]: *** [CMakeFiles/glogbase.dir/src/logging.cc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:183: recipe for target 'CMakeFiles/glogbase.dir/all' failed
> make[1]: *** [CMakeFiles/glogbase.dir/all] Error 2
> Makefile:162: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by sergiud** [comment]
Looks like your gflags version is outdated.

**Comment by ChanCody** [comment]
> Looks like your gflags version is outdated.

My gflags version is v2.1.2. How do I know if this version is outdated?

**Comment by sergiud** [comment]
glog 0.6 requires at least 2.2.2:

https://github.com/google/glog/blob/b33e3bad4c46c8a6345525fd822af355e5ef9446/CMakeLists.txt#L82

Gflags is not used by glog otherwise. There must be something very wrong with your setup.
