### ISSUE TITLE
configure: Hardcoded `am__api_version='1.14'` breaks build on systems with autoconf 1.15

### ISSUE THREAD

**Issue by marcusmueller** [google/glog#97]
… which should be fairly common these days, considering 1.15 is from 2014.

I suspect 

```
am__api_version=`aclocal --version|head -n1|grep -oE '[0-9]+.[0-9]+$'`
```

would fix the issue, but I'm not sure glog wouldn't want to check the version to be "high" enough.

Reason of problem:

the configure script appends the `am__api_version` to the `aclocal` executable name, and of course, on a system with `aclocal-1.15`, there's no `aclocal-1.14`.

**Comment by ldemailly** [comment]
workaround: https://github.com/google/glog/issues/117#issuecomment-228142866
