### ISSUE TITLE
Can LOG(FATAL) insert `__builtin_unreachable()` after `Fail()` ?

### ISSUE THREAD

**Issue by kvtb** [google/glog#977]
Can LOG(FATAL) insert `__builtin_unreachable()` after `Fail()` ?

`~LogMessageFatal()` having `[[noreturn]]` is not enough to suppress all silly compiler warnings, e.g.

```c++
int f() {
 switch (someenum) {
  case A: return 1;
  case B: return 2;
 }
 LOG(FATAL) << "unexpected someenum: " << (int)someenum;
}
```
compiler blames that the function does not return `int`

**Comment by sergiud** [comment]
I'm not seeing any warnings or errors even when compiling using `-Wall -Wextra -pedantic -Werror`.

Please provide a full reproducer including exact compiler and glog version, options necessary provoke the warnings etc.

**Comment by sergiud** [comment]
Closing due to lack of response. Please let us know once you have more information on how to reproduce the issue.
