### ISSUE TITLE
glog.ini logfile_mode set error

### ISSUE THREAD

**Issue by hoopfly** [google/glog#980]
the parameter logfile_mode in glog.ini is ineffective, the design should be configured according to octal digits, but atoi in TIniFile::ReadInt returns the converted integral number to decimal digits, for example what I set 0660 is actually 660, should TIniFile::ReadInt support read octal digits. 
logging.cc:2190 770 is wrong, it should be modified to 0770, logging.cc:166 0664 is right.

code:
logging.cc:166 GLOG_DEFINE_int32(logfile_mode, 0664, “Log file mode/permissions.”);
logging.cc:2190 FLAGS_logfile_mode = iniFileObj.ReadInt(“glog”, “logfile_mode”, **770**);
logging.cc:912 int fd = open(filename, O_WRONLY | O_CREAT | O_EXCL, FLAGS_logfile_mode);
profile.cpp:167 
int TIniFile::ReadInt(const char *section, const char *entry, int defaultInt)
{
char buf[1024] = { 0 };
char buf2[12] = { 0 };
sprint(buf2, “%d”, defaultInt); // -2100000000
ReadString(section, entry, buf2, buf, sizeof(buf));
**defaultInt = atoi(buf);**
return defaultInt;
}

**Comment by sergiud** [comment]
You seem to be confusing something as there's no such thing as `glog.ini` or `TIniFile` in glog.
