### ISSUE TITLE
cmake: dbghelp is incorrectly detected when building static libraris with Xcode generator

### ISSUE THREAD

**Issue by Kentzo** [google/glog#982]
It's probably an issue with CMake (tested 3.27.9), but [check_library_exists](https://github.com/google/glog/blob/931323df212c46e3a01b743d761c6ab8dc9f0d09/CMakeLists.txt#L159) incorrectly detects `dbghelp` when generating an Xcode project that cross-compiles for tvOS and passing `-DBUILD_SHARED_LIBS=OFF`. The internally generated TryCompile project by CMake simply makes no attempt at actually detecting library's presence.

I reported it to CMake via a private issue [#25479](https://gitlab.kitware.com/cmake/cmake/-/issues/25479).

The workaround is to ["bypass"](https://github.com/Kitware/CMake/blob/master/Modules/CheckLibraryExists.cmake#L44) the `check_library_exists` check by passing `-DHAVE_DBGHELP=0` to cmake.

**Comment by sergiud** [comment]
Thanks for the report.

Can you confirm that switching to `check_cxx_symbol_exists` also solves the issue?
