### ISSUE TITLE
LoongArch undefined reference error

### ISSUE THREAD

**Issue by minguofeng** [google/glog#989]
```console
[  0%] Linking CXX executable ../../../build/release/proto-bin/protoc-gen-insertions
/usr/bin/ld: ../../../thirdparty/glog-0.3.5.M.20181214/.libs/libglog.a(libglog_la-utilities.o): in function `.L70':
utilities.cc:(.text+0xa24): undefined reference to `_Uloongarch_getcontext'
/usr/bin/ld: utilities.cc:(.text+0xa40): undefined reference to `_ULloongarch_init_local'
/usr/bin/ld: ../../../thirdparty/glog-0.3.5.M.20181214/.libs/libglog.a(libglog_la-utilities.o): in function `.L78':
utilities.cc:(.text+0xae0): undefined reference to `_ULloongarch_get_reg'
/usr/bin/ld: ../../../thirdparty/glog-0.3.5.M.20181214/.libs/libglog.a(libglog_la-utilities.o): in function `.L76':
utilities.cc:(.text+0xb70): undefined reference to `_ULloongarch_step'
collect2: error: ld returned 1 exit status
```

**Comment by sergiud** [comment]
According to your log, you seem to be using glog 0.3.5 which is [over 6 years old](https://github.com/google/glog/releases/tag/v0.3.5). This release is no longer supported.

I suggest updating to version 0.6.0 before we can continue investigating. Please also provide the full CMake log.

**Comment by minguofeng** [comment]
> According to your log, you seem to be using glog 0.3.5 which is [over 6 years old](https://github.com/google/glog/releases/tag/v0.3.5). This release is no longer supported.
> 
> I suggest updating to version 0.6.0 before we can continue investigating. Please also provide the full CMake log.

Thank you very much for your response. I have used version 0.6.0 , but it had the same error. I want to know if the glog 0.6.0 support __loongarch__,  it seams no _ULloongarch_get_reg interface. This is the cmake command, and the compilation is successful. "CXX="${GCC_PATH}/bin/g++" LDFLAGS="-L$XCLOUD_HOME/thirdparty/boost-1.68.0/lib" CPPFLAGS="-I/thirdparty/boost-1.68.0/include/" LIBS="-lboost_system" ./configure --with-pic --with-gflags=${GFLAGS_INSTALL} CXXFLAGS="-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1" --host=loongarch64"

**Comment by sergiud** [comment]
Please provide the full logs both for CMake configuration step and the compilation. Without this information it is not possible to determine why the issue occurs.

> This is the cmake command, and the compilation is successful.
> 
> ```
> CXX="${GCC_PATH}/bin/g++" LDFLAGS="-L$XCLOUD_HOME/thirdparty/boost-1.68.0/lib" CPPFLAGS="-I/thirdparty/boost-1.68.0/include/" LIBS="-lboost_system" ./configure --with-pic --with-gflags=${GFLAGS_INSTALL} CXXFLAGS="-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1" --host=loongarch64`
> ```

This is not a CMake command-line but rather the command-line for unsupported autoconf builds.

**Comment by minguofeng** [comment]
@sergiud 
[build_glog.log](https://github.com/google/glog/files/13737274/build_glog.log)

echo "build glog..."
cd $/XXX_HOME/thirdparty/glog-${XCLOUD_GLOG_VERSION}
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${/XXX_HOME}/thirdparty/boost-1.68.0/lib"
LDFLAGS=
CPPFLAGS=
LIBS=
CXXFLAGS=
if [ "${ESB}" = "loong" ]; then
GLOGVERSION=0.3.5
GFLAGS_INSTALL=//XXX_HOME/thirdparty/gflags-2.2.1/third-party-install
if ["${GLOGVERSION}" = "0.3.5"]; then
CXX="${GCC_PATH}/bin/g++" LDFLAGS="-L$/XXX_HOME/thirdparty/boost-1.68.0/lib" CPPFLAGS="-I$/XXX_HOME/thirdparty/boost-1.68.0/include/" LIBS="-lboost_system" ./configure --with-pic --with-gflags=${GFLAGS_INSTALL} CXXFLAGS="-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1" --build=loongarch64-kylin-linux-gnu --host=loongarch64
else
cmake \
  -DCMAKE_CXX_COMPILER="${GCC_PATH}/bin/g++" \
  -DCMAKE_EXE_LINKER_FLAGS="-L$/XXX_HOME/thirdparty/boost-1.68.0/lib" \
  -DCMAKE_CXX_FLAGS="-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1 -I$/XXX_HOME/thirdparty/boost-1.68.0/include/" \
  -DBoost_SYSTEM_LIBRARY="-lboost_system" \
  -DCMAKE_INSTALL_PREFIX=${GFLAGS_INSTALL} \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DHOST_ARCH=loongarch64 \
  -DBUILD_ARCH=loongarch64-kylin-linux-gnu \
  -S . 
fi

# SLES's gcc45-c++ is required for sse2 support (default is 4.3), but crashes
# when building logging_unittest-logging_unittest.o. Telling it to uses the
# stabs format for debugging symbols instead of dwarf exercises a different
# code path to work around this issue.
cat > Makefile.gcc45sles_workaround <<EOF
logging_unittest-logging_unittest.o : CXXFLAGS= -gstabs -O2
EOF
cat Makefile >> Makefile.gcc45sles_workaround
mv Makefile.gcc45sles_workaround Makefile
make -j${CPU}
echo "build glog done"

**Comment by sergiud** [comment]
Your glog is using autoconf which is no longer supported as previously explained. You need to use the latest glog version and build either using CMake or Bazel.

**Comment by minguofeng** [comment]
> Your glog is using autoconf which is no longer supported as previously explained. You need to use the latest glog version and build either using CMake or Bazel.

i use following command, version 0.6.0, and obtained libglogtest.a .
cmake \
  -DCMAKE_CXX_COMPILER="${GCC_PATH}/bin/g++" \
  -DCMAKE_EXE_LINKER_FLAGS="-L$XXX_HOME/thirdparty/boost-1.68.0/lib" \
  -DCMAKE_CXX_FLAGS="-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1 -I$XXX_HOME/thirdparty/boost-1.68.0/include/" \
  -DBoost_SYSTEM_LIBRARY="-lboost_system" \
  -DCMAKE_PREFIX_PATH=${GFLAGS_INSTALL} \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DHOST_ARCH=loongarch64 \
  -DBUILD_ARCH=loongarch64-kylin-linux-gnu \
  -DBUILD_SHARED_LIBS=ON \
  .

when i use  `nm libglogtest.a | grep _Uloongarch_getcontext , got
                 U _Uloongarch_getcontext`

**Comment by sergiud** [comment]
Unfortunately, I don't see how that command-line can be used to compile glog. Some of the options such `HOST_ARCH` and `BUILD_ARCH` are unknown to glog. Also Boost is not a dependency of glog.

If you want to cross-compile glog using CMake you can use a [CMake toolchain file](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#id13). Once you've created one please configure glog using CMake and the toolchain file without specifying any additional options. Please attach the output both for 
1. the CMake configuration and 
2. the build step.

`libglogtest.a` is internal artifact you should not be using.

**Comment by minguofeng** [comment]
I have resolved the issue. The reason was that the system had an incompatible version of the libunwind library. After uninstalling this library, it worked fine.
